// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrivateOrdersV3Api.proto

#include "PrivateOrdersV3Api.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR PrivateOrdersV3Api::PrivateOrdersV3Api(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.clientid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.price_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.quantity_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.amount_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.avgprice_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.remainamount_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.remainquantity_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.lastdealquantity_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.cumulativequantity_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.cumulativeamount_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.market_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.triggerprice_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ocoid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.routefactor_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.symbolid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.marketid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.marketcurrencyid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.currencyid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ordertype_)*/0
  , /*decltype(_impl_.tradetype_)*/0
  , /*decltype(_impl_.ismaker_)*/false
  , /*decltype(_impl_.status_)*/0
  , /*decltype(_impl_.createtime_)*/int64_t{0}
  , /*decltype(_impl_.triggertype_)*/0
  , /*decltype(_impl_.state_)*/0} {}
struct PrivateOrdersV3ApiDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PrivateOrdersV3ApiDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PrivateOrdersV3ApiDefaultTypeInternal() {}
  union {
    PrivateOrdersV3Api _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PrivateOrdersV3ApiDefaultTypeInternal _PrivateOrdersV3Api_default_instance_;
static ::_pb::Metadata file_level_metadata_PrivateOrdersV3Api_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_PrivateOrdersV3Api_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_PrivateOrdersV3Api_2eproto = nullptr;

const uint32_t TableStruct_PrivateOrdersV3Api_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.clientid_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.price_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.quantity_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.amount_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.avgprice_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.ordertype_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.tradetype_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.ismaker_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.remainamount_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.remainquantity_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.lastdealquantity_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.cumulativequantity_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.cumulativeamount_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.createtime_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.market_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.triggertype_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.triggerprice_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.state_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.ocoid_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.routefactor_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.symbolid_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.marketid_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.marketcurrencyid_),
  PROTOBUF_FIELD_OFFSET(::PrivateOrdersV3Api, _impl_.currencyid_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  0,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  1,
  9,
  2,
  10,
  3,
  4,
  5,
  6,
  7,
  8,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 32, -1, sizeof(::PrivateOrdersV3Api)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_PrivateOrdersV3Api_default_instance_._instance,
};

const char descriptor_table_protodef_PrivateOrdersV3Api_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030PrivateOrdersV3Api.proto\"\350\005\n\022PrivateOr"
  "dersV3Api\022\n\n\002id\030\001 \001(\t\022\020\n\010clientId\030\002 \001(\t\022"
  "\r\n\005price\030\003 \001(\t\022\020\n\010quantity\030\004 \001(\t\022\016\n\006amou"
  "nt\030\005 \001(\t\022\020\n\010avgPrice\030\006 \001(\t\022\021\n\torderType\030"
  "\007 \001(\005\022\021\n\ttradeType\030\010 \001(\005\022\017\n\007isMaker\030\t \001("
  "\010\022\024\n\014remainAmount\030\n \001(\t\022\026\n\016remainQuantit"
  "y\030\013 \001(\t\022\035\n\020lastDealQuantity\030\014 \001(\tH\000\210\001\001\022\032"
  "\n\022cumulativeQuantity\030\r \001(\t\022\030\n\020cumulative"
  "Amount\030\016 \001(\t\022\016\n\006status\030\017 \001(\005\022\022\n\ncreateTi"
  "me\030\020 \001(\003\022\023\n\006market\030\021 \001(\tH\001\210\001\001\022\030\n\013trigger"
  "Type\030\022 \001(\005H\002\210\001\001\022\031\n\014triggerPrice\030\023 \001(\tH\003\210"
  "\001\001\022\022\n\005state\030\024 \001(\005H\004\210\001\001\022\022\n\005ocoId\030\025 \001(\tH\005\210"
  "\001\001\022\030\n\013routeFactor\030\026 \001(\tH\006\210\001\001\022\025\n\010symbolId"
  "\030\027 \001(\tH\007\210\001\001\022\025\n\010marketId\030\030 \001(\tH\010\210\001\001\022\035\n\020ma"
  "rketCurrencyId\030\031 \001(\tH\t\210\001\001\022\027\n\ncurrencyId\030"
  "\032 \001(\tH\n\210\001\001B\023\n\021_lastDealQuantityB\t\n\007_mark"
  "etB\016\n\014_triggerTypeB\017\n\r_triggerPriceB\010\n\006_"
  "stateB\010\n\006_ocoIdB\016\n\014_routeFactorB\013\n\t_symb"
  "olIdB\013\n\t_marketIdB\023\n\021_marketCurrencyIdB\r"
  "\n\013_currencyIdB;\n\034com.mxc.push.common.pro"
  "tobufB\027PrivateOrdersV3ApiProtoH\001P\001b\006prot"
  "o3"
  ;
static ::_pbi::once_flag descriptor_table_PrivateOrdersV3Api_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_PrivateOrdersV3Api_2eproto = {
    false, false, 842, descriptor_table_protodef_PrivateOrdersV3Api_2eproto,
    "PrivateOrdersV3Api.proto",
    &descriptor_table_PrivateOrdersV3Api_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_PrivateOrdersV3Api_2eproto::offsets,
    file_level_metadata_PrivateOrdersV3Api_2eproto, file_level_enum_descriptors_PrivateOrdersV3Api_2eproto,
    file_level_service_descriptors_PrivateOrdersV3Api_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_PrivateOrdersV3Api_2eproto_getter() {
  return &descriptor_table_PrivateOrdersV3Api_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_PrivateOrdersV3Api_2eproto(&descriptor_table_PrivateOrdersV3Api_2eproto);

// ===================================================================

class PrivateOrdersV3Api::_Internal {
 public:
  using HasBits = decltype(std::declval<PrivateOrdersV3Api>()._impl_._has_bits_);
  static void set_has_lastdealquantity(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_market(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_triggertype(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static void set_has_triggerprice(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_state(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
  static void set_has_ocoid(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_routefactor(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_symbolid(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_marketid(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_marketcurrencyid(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_currencyid(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
};

PrivateOrdersV3Api::PrivateOrdersV3Api(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PrivateOrdersV3Api)
}
PrivateOrdersV3Api::PrivateOrdersV3Api(const PrivateOrdersV3Api& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PrivateOrdersV3Api* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.id_){}
    , decltype(_impl_.clientid_){}
    , decltype(_impl_.price_){}
    , decltype(_impl_.quantity_){}
    , decltype(_impl_.amount_){}
    , decltype(_impl_.avgprice_){}
    , decltype(_impl_.remainamount_){}
    , decltype(_impl_.remainquantity_){}
    , decltype(_impl_.lastdealquantity_){}
    , decltype(_impl_.cumulativequantity_){}
    , decltype(_impl_.cumulativeamount_){}
    , decltype(_impl_.market_){}
    , decltype(_impl_.triggerprice_){}
    , decltype(_impl_.ocoid_){}
    , decltype(_impl_.routefactor_){}
    , decltype(_impl_.symbolid_){}
    , decltype(_impl_.marketid_){}
    , decltype(_impl_.marketcurrencyid_){}
    , decltype(_impl_.currencyid_){}
    , decltype(_impl_.ordertype_){}
    , decltype(_impl_.tradetype_){}
    , decltype(_impl_.ismaker_){}
    , decltype(_impl_.status_){}
    , decltype(_impl_.createtime_){}
    , decltype(_impl_.triggertype_){}
    , decltype(_impl_.state_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_id().empty()) {
    _this->_impl_.id_.Set(from._internal_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.clientid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.clientid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_clientid().empty()) {
    _this->_impl_.clientid_.Set(from._internal_clientid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.price_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.price_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_price().empty()) {
    _this->_impl_.price_.Set(from._internal_price(), 
      _this->GetArenaForAllocation());
  }
  _impl_.quantity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.quantity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_quantity().empty()) {
    _this->_impl_.quantity_.Set(from._internal_quantity(), 
      _this->GetArenaForAllocation());
  }
  _impl_.amount_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.amount_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_amount().empty()) {
    _this->_impl_.amount_.Set(from._internal_amount(), 
      _this->GetArenaForAllocation());
  }
  _impl_.avgprice_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.avgprice_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_avgprice().empty()) {
    _this->_impl_.avgprice_.Set(from._internal_avgprice(), 
      _this->GetArenaForAllocation());
  }
  _impl_.remainamount_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.remainamount_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_remainamount().empty()) {
    _this->_impl_.remainamount_.Set(from._internal_remainamount(), 
      _this->GetArenaForAllocation());
  }
  _impl_.remainquantity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.remainquantity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_remainquantity().empty()) {
    _this->_impl_.remainquantity_.Set(from._internal_remainquantity(), 
      _this->GetArenaForAllocation());
  }
  _impl_.lastdealquantity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lastdealquantity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_lastdealquantity()) {
    _this->_impl_.lastdealquantity_.Set(from._internal_lastdealquantity(), 
      _this->GetArenaForAllocation());
  }
  _impl_.cumulativequantity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.cumulativequantity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_cumulativequantity().empty()) {
    _this->_impl_.cumulativequantity_.Set(from._internal_cumulativequantity(), 
      _this->GetArenaForAllocation());
  }
  _impl_.cumulativeamount_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.cumulativeamount_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_cumulativeamount().empty()) {
    _this->_impl_.cumulativeamount_.Set(from._internal_cumulativeamount(), 
      _this->GetArenaForAllocation());
  }
  _impl_.market_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.market_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_market()) {
    _this->_impl_.market_.Set(from._internal_market(), 
      _this->GetArenaForAllocation());
  }
  _impl_.triggerprice_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.triggerprice_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_triggerprice()) {
    _this->_impl_.triggerprice_.Set(from._internal_triggerprice(), 
      _this->GetArenaForAllocation());
  }
  _impl_.ocoid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ocoid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_ocoid()) {
    _this->_impl_.ocoid_.Set(from._internal_ocoid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.routefactor_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.routefactor_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_routefactor()) {
    _this->_impl_.routefactor_.Set(from._internal_routefactor(), 
      _this->GetArenaForAllocation());
  }
  _impl_.symbolid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.symbolid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_symbolid()) {
    _this->_impl_.symbolid_.Set(from._internal_symbolid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.marketid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.marketid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_marketid()) {
    _this->_impl_.marketid_.Set(from._internal_marketid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.marketcurrencyid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.marketcurrencyid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_marketcurrencyid()) {
    _this->_impl_.marketcurrencyid_.Set(from._internal_marketcurrencyid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.currencyid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.currencyid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_currencyid()) {
    _this->_impl_.currencyid_.Set(from._internal_currencyid(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.ordertype_, &from._impl_.ordertype_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.state_) -
    reinterpret_cast<char*>(&_impl_.ordertype_)) + sizeof(_impl_.state_));
  // @@protoc_insertion_point(copy_constructor:PrivateOrdersV3Api)
}

inline void PrivateOrdersV3Api::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.id_){}
    , decltype(_impl_.clientid_){}
    , decltype(_impl_.price_){}
    , decltype(_impl_.quantity_){}
    , decltype(_impl_.amount_){}
    , decltype(_impl_.avgprice_){}
    , decltype(_impl_.remainamount_){}
    , decltype(_impl_.remainquantity_){}
    , decltype(_impl_.lastdealquantity_){}
    , decltype(_impl_.cumulativequantity_){}
    , decltype(_impl_.cumulativeamount_){}
    , decltype(_impl_.market_){}
    , decltype(_impl_.triggerprice_){}
    , decltype(_impl_.ocoid_){}
    , decltype(_impl_.routefactor_){}
    , decltype(_impl_.symbolid_){}
    , decltype(_impl_.marketid_){}
    , decltype(_impl_.marketcurrencyid_){}
    , decltype(_impl_.currencyid_){}
    , decltype(_impl_.ordertype_){0}
    , decltype(_impl_.tradetype_){0}
    , decltype(_impl_.ismaker_){false}
    , decltype(_impl_.status_){0}
    , decltype(_impl_.createtime_){int64_t{0}}
    , decltype(_impl_.triggertype_){0}
    , decltype(_impl_.state_){0}
  };
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.clientid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.clientid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.price_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.price_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.quantity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.quantity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.amount_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.amount_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.avgprice_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.avgprice_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.remainamount_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.remainamount_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.remainquantity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.remainquantity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.lastdealquantity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lastdealquantity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.cumulativequantity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.cumulativequantity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.cumulativeamount_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.cumulativeamount_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.market_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.market_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.triggerprice_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.triggerprice_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.ocoid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ocoid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.routefactor_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.routefactor_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.symbolid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.symbolid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.marketid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.marketid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.marketcurrencyid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.marketcurrencyid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.currencyid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.currencyid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PrivateOrdersV3Api::~PrivateOrdersV3Api() {
  // @@protoc_insertion_point(destructor:PrivateOrdersV3Api)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PrivateOrdersV3Api::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.id_.Destroy();
  _impl_.clientid_.Destroy();
  _impl_.price_.Destroy();
  _impl_.quantity_.Destroy();
  _impl_.amount_.Destroy();
  _impl_.avgprice_.Destroy();
  _impl_.remainamount_.Destroy();
  _impl_.remainquantity_.Destroy();
  _impl_.lastdealquantity_.Destroy();
  _impl_.cumulativequantity_.Destroy();
  _impl_.cumulativeamount_.Destroy();
  _impl_.market_.Destroy();
  _impl_.triggerprice_.Destroy();
  _impl_.ocoid_.Destroy();
  _impl_.routefactor_.Destroy();
  _impl_.symbolid_.Destroy();
  _impl_.marketid_.Destroy();
  _impl_.marketcurrencyid_.Destroy();
  _impl_.currencyid_.Destroy();
}

void PrivateOrdersV3Api::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PrivateOrdersV3Api::Clear() {
// @@protoc_insertion_point(message_clear_start:PrivateOrdersV3Api)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _impl_.clientid_.ClearToEmpty();
  _impl_.price_.ClearToEmpty();
  _impl_.quantity_.ClearToEmpty();
  _impl_.amount_.ClearToEmpty();
  _impl_.avgprice_.ClearToEmpty();
  _impl_.remainamount_.ClearToEmpty();
  _impl_.remainquantity_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.lastdealquantity_.ClearNonDefaultToEmpty();
  }
  _impl_.cumulativequantity_.ClearToEmpty();
  _impl_.cumulativeamount_.ClearToEmpty();
  if (cached_has_bits & 0x000000feu) {
    if (cached_has_bits & 0x00000002u) {
      _impl_.market_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.triggerprice_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.ocoid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      _impl_.routefactor_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000020u) {
      _impl_.symbolid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000040u) {
      _impl_.marketid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000080u) {
      _impl_.marketcurrencyid_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00000100u) {
    _impl_.currencyid_.ClearNonDefaultToEmpty();
  }
  ::memset(&_impl_.ordertype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.createtime_) -
      reinterpret_cast<char*>(&_impl_.ordertype_)) + sizeof(_impl_.createtime_));
  if (cached_has_bits & 0x00000600u) {
    ::memset(&_impl_.triggertype_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.state_) -
        reinterpret_cast<char*>(&_impl_.triggertype_)) + sizeof(_impl_.state_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PrivateOrdersV3Api::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.id"));
        } else
          goto handle_unusual;
        continue;
      // string clientId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_clientid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.clientId"));
        } else
          goto handle_unusual;
        continue;
      // string price = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_price();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.price"));
        } else
          goto handle_unusual;
        continue;
      // string quantity = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_quantity();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.quantity"));
        } else
          goto handle_unusual;
        continue;
      // string amount = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_amount();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.amount"));
        } else
          goto handle_unusual;
        continue;
      // string avgPrice = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_avgprice();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.avgPrice"));
        } else
          goto handle_unusual;
        continue;
      // int32 orderType = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.ordertype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 tradeType = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.tradetype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool isMaker = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.ismaker_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string remainAmount = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_remainamount();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.remainAmount"));
        } else
          goto handle_unusual;
        continue;
      // string remainQuantity = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_remainquantity();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.remainQuantity"));
        } else
          goto handle_unusual;
        continue;
      // optional string lastDealQuantity = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          auto str = _internal_mutable_lastdealquantity();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.lastDealQuantity"));
        } else
          goto handle_unusual;
        continue;
      // string cumulativeQuantity = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          auto str = _internal_mutable_cumulativequantity();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.cumulativeQuantity"));
        } else
          goto handle_unusual;
        continue;
      // string cumulativeAmount = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 114)) {
          auto str = _internal_mutable_cumulativeamount();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.cumulativeAmount"));
        } else
          goto handle_unusual;
        continue;
      // int32 status = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 120)) {
          _impl_.status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 createTime = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 128)) {
          _impl_.createtime_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string market = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 138)) {
          auto str = _internal_mutable_market();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.market"));
        } else
          goto handle_unusual;
        continue;
      // optional int32 triggerType = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 144)) {
          _Internal::set_has_triggertype(&has_bits);
          _impl_.triggertype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string triggerPrice = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 154)) {
          auto str = _internal_mutable_triggerprice();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.triggerPrice"));
        } else
          goto handle_unusual;
        continue;
      // optional int32 state = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 160)) {
          _Internal::set_has_state(&has_bits);
          _impl_.state_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string ocoId = 21;
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 170)) {
          auto str = _internal_mutable_ocoid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.ocoId"));
        } else
          goto handle_unusual;
        continue;
      // optional string routeFactor = 22;
      case 22:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 178)) {
          auto str = _internal_mutable_routefactor();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.routeFactor"));
        } else
          goto handle_unusual;
        continue;
      // optional string symbolId = 23;
      case 23:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 186)) {
          auto str = _internal_mutable_symbolid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.symbolId"));
        } else
          goto handle_unusual;
        continue;
      // optional string marketId = 24;
      case 24:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 194)) {
          auto str = _internal_mutable_marketid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.marketId"));
        } else
          goto handle_unusual;
        continue;
      // optional string marketCurrencyId = 25;
      case 25:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 202)) {
          auto str = _internal_mutable_marketcurrencyid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.marketCurrencyId"));
        } else
          goto handle_unusual;
        continue;
      // optional string currencyId = 26;
      case 26:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 210)) {
          auto str = _internal_mutable_currencyid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PrivateOrdersV3Api.currencyId"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PrivateOrdersV3Api::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PrivateOrdersV3Api)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_id(), target);
  }

  // string clientId = 2;
  if (!this->_internal_clientid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_clientid().data(), static_cast<int>(this->_internal_clientid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.clientId");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_clientid(), target);
  }

  // string price = 3;
  if (!this->_internal_price().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_price().data(), static_cast<int>(this->_internal_price().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.price");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_price(), target);
  }

  // string quantity = 4;
  if (!this->_internal_quantity().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_quantity().data(), static_cast<int>(this->_internal_quantity().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.quantity");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_quantity(), target);
  }

  // string amount = 5;
  if (!this->_internal_amount().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_amount().data(), static_cast<int>(this->_internal_amount().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.amount");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_amount(), target);
  }

  // string avgPrice = 6;
  if (!this->_internal_avgprice().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_avgprice().data(), static_cast<int>(this->_internal_avgprice().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.avgPrice");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_avgprice(), target);
  }

  // int32 orderType = 7;
  if (this->_internal_ordertype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_ordertype(), target);
  }

  // int32 tradeType = 8;
  if (this->_internal_tradetype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(8, this->_internal_tradetype(), target);
  }

  // bool isMaker = 9;
  if (this->_internal_ismaker() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(9, this->_internal_ismaker(), target);
  }

  // string remainAmount = 10;
  if (!this->_internal_remainamount().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_remainamount().data(), static_cast<int>(this->_internal_remainamount().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.remainAmount");
    target = stream->WriteStringMaybeAliased(
        10, this->_internal_remainamount(), target);
  }

  // string remainQuantity = 11;
  if (!this->_internal_remainquantity().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_remainquantity().data(), static_cast<int>(this->_internal_remainquantity().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.remainQuantity");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_remainquantity(), target);
  }

  // optional string lastDealQuantity = 12;
  if (_internal_has_lastdealquantity()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_lastdealquantity().data(), static_cast<int>(this->_internal_lastdealquantity().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.lastDealQuantity");
    target = stream->WriteStringMaybeAliased(
        12, this->_internal_lastdealquantity(), target);
  }

  // string cumulativeQuantity = 13;
  if (!this->_internal_cumulativequantity().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_cumulativequantity().data(), static_cast<int>(this->_internal_cumulativequantity().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.cumulativeQuantity");
    target = stream->WriteStringMaybeAliased(
        13, this->_internal_cumulativequantity(), target);
  }

  // string cumulativeAmount = 14;
  if (!this->_internal_cumulativeamount().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_cumulativeamount().data(), static_cast<int>(this->_internal_cumulativeamount().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.cumulativeAmount");
    target = stream->WriteStringMaybeAliased(
        14, this->_internal_cumulativeamount(), target);
  }

  // int32 status = 15;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(15, this->_internal_status(), target);
  }

  // int64 createTime = 16;
  if (this->_internal_createtime() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(16, this->_internal_createtime(), target);
  }

  // optional string market = 17;
  if (_internal_has_market()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_market().data(), static_cast<int>(this->_internal_market().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.market");
    target = stream->WriteStringMaybeAliased(
        17, this->_internal_market(), target);
  }

  // optional int32 triggerType = 18;
  if (_internal_has_triggertype()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(18, this->_internal_triggertype(), target);
  }

  // optional string triggerPrice = 19;
  if (_internal_has_triggerprice()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_triggerprice().data(), static_cast<int>(this->_internal_triggerprice().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.triggerPrice");
    target = stream->WriteStringMaybeAliased(
        19, this->_internal_triggerprice(), target);
  }

  // optional int32 state = 20;
  if (_internal_has_state()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(20, this->_internal_state(), target);
  }

  // optional string ocoId = 21;
  if (_internal_has_ocoid()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ocoid().data(), static_cast<int>(this->_internal_ocoid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.ocoId");
    target = stream->WriteStringMaybeAliased(
        21, this->_internal_ocoid(), target);
  }

  // optional string routeFactor = 22;
  if (_internal_has_routefactor()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_routefactor().data(), static_cast<int>(this->_internal_routefactor().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.routeFactor");
    target = stream->WriteStringMaybeAliased(
        22, this->_internal_routefactor(), target);
  }

  // optional string symbolId = 23;
  if (_internal_has_symbolid()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_symbolid().data(), static_cast<int>(this->_internal_symbolid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.symbolId");
    target = stream->WriteStringMaybeAliased(
        23, this->_internal_symbolid(), target);
  }

  // optional string marketId = 24;
  if (_internal_has_marketid()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_marketid().data(), static_cast<int>(this->_internal_marketid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.marketId");
    target = stream->WriteStringMaybeAliased(
        24, this->_internal_marketid(), target);
  }

  // optional string marketCurrencyId = 25;
  if (_internal_has_marketcurrencyid()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_marketcurrencyid().data(), static_cast<int>(this->_internal_marketcurrencyid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.marketCurrencyId");
    target = stream->WriteStringMaybeAliased(
        25, this->_internal_marketcurrencyid(), target);
  }

  // optional string currencyId = 26;
  if (_internal_has_currencyid()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_currencyid().data(), static_cast<int>(this->_internal_currencyid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PrivateOrdersV3Api.currencyId");
    target = stream->WriteStringMaybeAliased(
        26, this->_internal_currencyid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PrivateOrdersV3Api)
  return target;
}

size_t PrivateOrdersV3Api::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PrivateOrdersV3Api)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  // string clientId = 2;
  if (!this->_internal_clientid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_clientid());
  }

  // string price = 3;
  if (!this->_internal_price().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_price());
  }

  // string quantity = 4;
  if (!this->_internal_quantity().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_quantity());
  }

  // string amount = 5;
  if (!this->_internal_amount().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_amount());
  }

  // string avgPrice = 6;
  if (!this->_internal_avgprice().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_avgprice());
  }

  // string remainAmount = 10;
  if (!this->_internal_remainamount().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_remainamount());
  }

  // string remainQuantity = 11;
  if (!this->_internal_remainquantity().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_remainquantity());
  }

  // optional string lastDealQuantity = 12;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_lastdealquantity());
  }

  // string cumulativeQuantity = 13;
  if (!this->_internal_cumulativequantity().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_cumulativequantity());
  }

  // string cumulativeAmount = 14;
  if (!this->_internal_cumulativeamount().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_cumulativeamount());
  }

  if (cached_has_bits & 0x000000feu) {
    // optional string market = 17;
    if (cached_has_bits & 0x00000002u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_market());
    }

    // optional string triggerPrice = 19;
    if (cached_has_bits & 0x00000004u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_triggerprice());
    }

    // optional string ocoId = 21;
    if (cached_has_bits & 0x00000008u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_ocoid());
    }

    // optional string routeFactor = 22;
    if (cached_has_bits & 0x00000010u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_routefactor());
    }

    // optional string symbolId = 23;
    if (cached_has_bits & 0x00000020u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_symbolid());
    }

    // optional string marketId = 24;
    if (cached_has_bits & 0x00000040u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_marketid());
    }

    // optional string marketCurrencyId = 25;
    if (cached_has_bits & 0x00000080u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_marketcurrencyid());
    }

  }
  // optional string currencyId = 26;
  if (cached_has_bits & 0x00000100u) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_currencyid());
  }

  // int32 orderType = 7;
  if (this->_internal_ordertype() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_ordertype());
  }

  // int32 tradeType = 8;
  if (this->_internal_tradetype() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_tradetype());
  }

  // bool isMaker = 9;
  if (this->_internal_ismaker() != 0) {
    total_size += 1 + 1;
  }

  // int32 status = 15;
  if (this->_internal_status() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_status());
  }

  // int64 createTime = 16;
  if (this->_internal_createtime() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int64Size(
        this->_internal_createtime());
  }

  if (cached_has_bits & 0x00000600u) {
    // optional int32 triggerType = 18;
    if (cached_has_bits & 0x00000200u) {
      total_size += 2 +
        ::_pbi::WireFormatLite::Int32Size(
          this->_internal_triggertype());
    }

    // optional int32 state = 20;
    if (cached_has_bits & 0x00000400u) {
      total_size += 2 +
        ::_pbi::WireFormatLite::Int32Size(
          this->_internal_state());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PrivateOrdersV3Api::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PrivateOrdersV3Api::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PrivateOrdersV3Api::GetClassData() const { return &_class_data_; }


void PrivateOrdersV3Api::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PrivateOrdersV3Api*>(&to_msg);
  auto& from = static_cast<const PrivateOrdersV3Api&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PrivateOrdersV3Api)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (!from._internal_clientid().empty()) {
    _this->_internal_set_clientid(from._internal_clientid());
  }
  if (!from._internal_price().empty()) {
    _this->_internal_set_price(from._internal_price());
  }
  if (!from._internal_quantity().empty()) {
    _this->_internal_set_quantity(from._internal_quantity());
  }
  if (!from._internal_amount().empty()) {
    _this->_internal_set_amount(from._internal_amount());
  }
  if (!from._internal_avgprice().empty()) {
    _this->_internal_set_avgprice(from._internal_avgprice());
  }
  if (!from._internal_remainamount().empty()) {
    _this->_internal_set_remainamount(from._internal_remainamount());
  }
  if (!from._internal_remainquantity().empty()) {
    _this->_internal_set_remainquantity(from._internal_remainquantity());
  }
  if (from._internal_has_lastdealquantity()) {
    _this->_internal_set_lastdealquantity(from._internal_lastdealquantity());
  }
  if (!from._internal_cumulativequantity().empty()) {
    _this->_internal_set_cumulativequantity(from._internal_cumulativequantity());
  }
  if (!from._internal_cumulativeamount().empty()) {
    _this->_internal_set_cumulativeamount(from._internal_cumulativeamount());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000feu) {
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_market(from._internal_market());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_triggerprice(from._internal_triggerprice());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_ocoid(from._internal_ocoid());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_set_routefactor(from._internal_routefactor());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_internal_set_symbolid(from._internal_symbolid());
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_internal_set_marketid(from._internal_marketid());
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_internal_set_marketcurrencyid(from._internal_marketcurrencyid());
    }
  }
  if (cached_has_bits & 0x00000100u) {
    _this->_internal_set_currencyid(from._internal_currencyid());
  }
  if (from._internal_ordertype() != 0) {
    _this->_internal_set_ordertype(from._internal_ordertype());
  }
  if (from._internal_tradetype() != 0) {
    _this->_internal_set_tradetype(from._internal_tradetype());
  }
  if (from._internal_ismaker() != 0) {
    _this->_internal_set_ismaker(from._internal_ismaker());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  if (from._internal_createtime() != 0) {
    _this->_internal_set_createtime(from._internal_createtime());
  }
  if (cached_has_bits & 0x00000600u) {
    if (cached_has_bits & 0x00000200u) {
      _this->_impl_.triggertype_ = from._impl_.triggertype_;
    }
    if (cached_has_bits & 0x00000400u) {
      _this->_impl_.state_ = from._impl_.state_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PrivateOrdersV3Api::CopyFrom(const PrivateOrdersV3Api& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PrivateOrdersV3Api)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PrivateOrdersV3Api::IsInitialized() const {
  return true;
}

void PrivateOrdersV3Api::InternalSwap(PrivateOrdersV3Api* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.id_, lhs_arena,
      &other->_impl_.id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.clientid_, lhs_arena,
      &other->_impl_.clientid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.price_, lhs_arena,
      &other->_impl_.price_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.quantity_, lhs_arena,
      &other->_impl_.quantity_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.amount_, lhs_arena,
      &other->_impl_.amount_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.avgprice_, lhs_arena,
      &other->_impl_.avgprice_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.remainamount_, lhs_arena,
      &other->_impl_.remainamount_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.remainquantity_, lhs_arena,
      &other->_impl_.remainquantity_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.lastdealquantity_, lhs_arena,
      &other->_impl_.lastdealquantity_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.cumulativequantity_, lhs_arena,
      &other->_impl_.cumulativequantity_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.cumulativeamount_, lhs_arena,
      &other->_impl_.cumulativeamount_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.market_, lhs_arena,
      &other->_impl_.market_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.triggerprice_, lhs_arena,
      &other->_impl_.triggerprice_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ocoid_, lhs_arena,
      &other->_impl_.ocoid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.routefactor_, lhs_arena,
      &other->_impl_.routefactor_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.symbolid_, lhs_arena,
      &other->_impl_.symbolid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.marketid_, lhs_arena,
      &other->_impl_.marketid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.marketcurrencyid_, lhs_arena,
      &other->_impl_.marketcurrencyid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.currencyid_, lhs_arena,
      &other->_impl_.currencyid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PrivateOrdersV3Api, _impl_.state_)
      + sizeof(PrivateOrdersV3Api::_impl_.state_)
      - PROTOBUF_FIELD_OFFSET(PrivateOrdersV3Api, _impl_.ordertype_)>(
          reinterpret_cast<char*>(&_impl_.ordertype_),
          reinterpret_cast<char*>(&other->_impl_.ordertype_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PrivateOrdersV3Api::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PrivateOrdersV3Api_2eproto_getter, &descriptor_table_PrivateOrdersV3Api_2eproto_once,
      file_level_metadata_PrivateOrdersV3Api_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PrivateOrdersV3Api*
Arena::CreateMaybeMessage< ::PrivateOrdersV3Api >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PrivateOrdersV3Api >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
