// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrivateDealsV3Api.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PrivateDealsV3Api_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PrivateDealsV3Api_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PrivateDealsV3Api_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PrivateDealsV3Api_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PrivateDealsV3Api_2eproto;
class PrivateDealsV3Api;
struct PrivateDealsV3ApiDefaultTypeInternal;
extern PrivateDealsV3ApiDefaultTypeInternal _PrivateDealsV3Api_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PrivateDealsV3Api* Arena::CreateMaybeMessage<::PrivateDealsV3Api>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PrivateDealsV3Api final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PrivateDealsV3Api) */ {
 public:
  inline PrivateDealsV3Api() : PrivateDealsV3Api(nullptr) {}
  ~PrivateDealsV3Api() override;
  explicit PROTOBUF_CONSTEXPR PrivateDealsV3Api(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PrivateDealsV3Api(const PrivateDealsV3Api& from);
  PrivateDealsV3Api(PrivateDealsV3Api&& from) noexcept
    : PrivateDealsV3Api() {
    *this = ::std::move(from);
  }

  inline PrivateDealsV3Api& operator=(const PrivateDealsV3Api& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrivateDealsV3Api& operator=(PrivateDealsV3Api&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PrivateDealsV3Api& default_instance() {
    return *internal_default_instance();
  }
  static inline const PrivateDealsV3Api* internal_default_instance() {
    return reinterpret_cast<const PrivateDealsV3Api*>(
               &_PrivateDealsV3Api_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PrivateDealsV3Api& a, PrivateDealsV3Api& b) {
    a.Swap(&b);
  }
  inline void Swap(PrivateDealsV3Api* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrivateDealsV3Api* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PrivateDealsV3Api* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PrivateDealsV3Api>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PrivateDealsV3Api& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PrivateDealsV3Api& from) {
    PrivateDealsV3Api::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrivateDealsV3Api* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PrivateDealsV3Api";
  }
  protected:
  explicit PrivateDealsV3Api(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPriceFieldNumber = 1,
    kQuantityFieldNumber = 2,
    kAmountFieldNumber = 3,
    kTradeIdFieldNumber = 7,
    kClientOrderIdFieldNumber = 8,
    kOrderIdFieldNumber = 9,
    kFeeAmountFieldNumber = 10,
    kFeeCurrencyFieldNumber = 11,
    kTradeTypeFieldNumber = 4,
    kIsMakerFieldNumber = 5,
    kIsSelfTradeFieldNumber = 6,
    kTimeFieldNumber = 12,
  };
  // string price = 1;
  void clear_price();
  const std::string& price() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_price(ArgT0&& arg0, ArgT... args);
  std::string* mutable_price();
  PROTOBUF_NODISCARD std::string* release_price();
  void set_allocated_price(std::string* price);
  private:
  const std::string& _internal_price() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_price(const std::string& value);
  std::string* _internal_mutable_price();
  public:

  // string quantity = 2;
  void clear_quantity();
  const std::string& quantity() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_quantity(ArgT0&& arg0, ArgT... args);
  std::string* mutable_quantity();
  PROTOBUF_NODISCARD std::string* release_quantity();
  void set_allocated_quantity(std::string* quantity);
  private:
  const std::string& _internal_quantity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_quantity(const std::string& value);
  std::string* _internal_mutable_quantity();
  public:

  // string amount = 3;
  void clear_amount();
  const std::string& amount() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_amount(ArgT0&& arg0, ArgT... args);
  std::string* mutable_amount();
  PROTOBUF_NODISCARD std::string* release_amount();
  void set_allocated_amount(std::string* amount);
  private:
  const std::string& _internal_amount() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_amount(const std::string& value);
  std::string* _internal_mutable_amount();
  public:

  // string tradeId = 7;
  void clear_tradeid();
  const std::string& tradeid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_tradeid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_tradeid();
  PROTOBUF_NODISCARD std::string* release_tradeid();
  void set_allocated_tradeid(std::string* tradeid);
  private:
  const std::string& _internal_tradeid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tradeid(const std::string& value);
  std::string* _internal_mutable_tradeid();
  public:

  // string clientOrderId = 8;
  void clear_clientorderid();
  const std::string& clientorderid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_clientorderid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_clientorderid();
  PROTOBUF_NODISCARD std::string* release_clientorderid();
  void set_allocated_clientorderid(std::string* clientorderid);
  private:
  const std::string& _internal_clientorderid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_clientorderid(const std::string& value);
  std::string* _internal_mutable_clientorderid();
  public:

  // string orderId = 9;
  void clear_orderid();
  const std::string& orderid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_orderid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_orderid();
  PROTOBUF_NODISCARD std::string* release_orderid();
  void set_allocated_orderid(std::string* orderid);
  private:
  const std::string& _internal_orderid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_orderid(const std::string& value);
  std::string* _internal_mutable_orderid();
  public:

  // string feeAmount = 10;
  void clear_feeamount();
  const std::string& feeamount() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_feeamount(ArgT0&& arg0, ArgT... args);
  std::string* mutable_feeamount();
  PROTOBUF_NODISCARD std::string* release_feeamount();
  void set_allocated_feeamount(std::string* feeamount);
  private:
  const std::string& _internal_feeamount() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_feeamount(const std::string& value);
  std::string* _internal_mutable_feeamount();
  public:

  // string feeCurrency = 11;
  void clear_feecurrency();
  const std::string& feecurrency() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_feecurrency(ArgT0&& arg0, ArgT... args);
  std::string* mutable_feecurrency();
  PROTOBUF_NODISCARD std::string* release_feecurrency();
  void set_allocated_feecurrency(std::string* feecurrency);
  private:
  const std::string& _internal_feecurrency() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_feecurrency(const std::string& value);
  std::string* _internal_mutable_feecurrency();
  public:

  // int32 tradeType = 4;
  void clear_tradetype();
  int32_t tradetype() const;
  void set_tradetype(int32_t value);
  private:
  int32_t _internal_tradetype() const;
  void _internal_set_tradetype(int32_t value);
  public:

  // bool isMaker = 5;
  void clear_ismaker();
  bool ismaker() const;
  void set_ismaker(bool value);
  private:
  bool _internal_ismaker() const;
  void _internal_set_ismaker(bool value);
  public:

  // bool isSelfTrade = 6;
  void clear_isselftrade();
  bool isselftrade() const;
  void set_isselftrade(bool value);
  private:
  bool _internal_isselftrade() const;
  void _internal_set_isselftrade(bool value);
  public:

  // int64 time = 12;
  void clear_time();
  int64_t time() const;
  void set_time(int64_t value);
  private:
  int64_t _internal_time() const;
  void _internal_set_time(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:PrivateDealsV3Api)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr price_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr quantity_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr amount_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tradeid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr clientorderid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr orderid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr feeamount_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr feecurrency_;
    int32_t tradetype_;
    bool ismaker_;
    bool isselftrade_;
    int64_t time_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PrivateDealsV3Api_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PrivateDealsV3Api

// string price = 1;
inline void PrivateDealsV3Api::clear_price() {
  _impl_.price_.ClearToEmpty();
}
inline const std::string& PrivateDealsV3Api::price() const {
  // @@protoc_insertion_point(field_get:PrivateDealsV3Api.price)
  return _internal_price();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateDealsV3Api::set_price(ArgT0&& arg0, ArgT... args) {
 
 _impl_.price_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateDealsV3Api.price)
}
inline std::string* PrivateDealsV3Api::mutable_price() {
  std::string* _s = _internal_mutable_price();
  // @@protoc_insertion_point(field_mutable:PrivateDealsV3Api.price)
  return _s;
}
inline const std::string& PrivateDealsV3Api::_internal_price() const {
  return _impl_.price_.Get();
}
inline void PrivateDealsV3Api::_internal_set_price(const std::string& value) {
  
  _impl_.price_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::_internal_mutable_price() {
  
  return _impl_.price_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::release_price() {
  // @@protoc_insertion_point(field_release:PrivateDealsV3Api.price)
  return _impl_.price_.Release();
}
inline void PrivateDealsV3Api::set_allocated_price(std::string* price) {
  if (price != nullptr) {
    
  } else {
    
  }
  _impl_.price_.SetAllocated(price, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.price_.IsDefault()) {
    _impl_.price_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateDealsV3Api.price)
}

// string quantity = 2;
inline void PrivateDealsV3Api::clear_quantity() {
  _impl_.quantity_.ClearToEmpty();
}
inline const std::string& PrivateDealsV3Api::quantity() const {
  // @@protoc_insertion_point(field_get:PrivateDealsV3Api.quantity)
  return _internal_quantity();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateDealsV3Api::set_quantity(ArgT0&& arg0, ArgT... args) {
 
 _impl_.quantity_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateDealsV3Api.quantity)
}
inline std::string* PrivateDealsV3Api::mutable_quantity() {
  std::string* _s = _internal_mutable_quantity();
  // @@protoc_insertion_point(field_mutable:PrivateDealsV3Api.quantity)
  return _s;
}
inline const std::string& PrivateDealsV3Api::_internal_quantity() const {
  return _impl_.quantity_.Get();
}
inline void PrivateDealsV3Api::_internal_set_quantity(const std::string& value) {
  
  _impl_.quantity_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::_internal_mutable_quantity() {
  
  return _impl_.quantity_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::release_quantity() {
  // @@protoc_insertion_point(field_release:PrivateDealsV3Api.quantity)
  return _impl_.quantity_.Release();
}
inline void PrivateDealsV3Api::set_allocated_quantity(std::string* quantity) {
  if (quantity != nullptr) {
    
  } else {
    
  }
  _impl_.quantity_.SetAllocated(quantity, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.quantity_.IsDefault()) {
    _impl_.quantity_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateDealsV3Api.quantity)
}

// string amount = 3;
inline void PrivateDealsV3Api::clear_amount() {
  _impl_.amount_.ClearToEmpty();
}
inline const std::string& PrivateDealsV3Api::amount() const {
  // @@protoc_insertion_point(field_get:PrivateDealsV3Api.amount)
  return _internal_amount();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateDealsV3Api::set_amount(ArgT0&& arg0, ArgT... args) {
 
 _impl_.amount_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateDealsV3Api.amount)
}
inline std::string* PrivateDealsV3Api::mutable_amount() {
  std::string* _s = _internal_mutable_amount();
  // @@protoc_insertion_point(field_mutable:PrivateDealsV3Api.amount)
  return _s;
}
inline const std::string& PrivateDealsV3Api::_internal_amount() const {
  return _impl_.amount_.Get();
}
inline void PrivateDealsV3Api::_internal_set_amount(const std::string& value) {
  
  _impl_.amount_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::_internal_mutable_amount() {
  
  return _impl_.amount_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::release_amount() {
  // @@protoc_insertion_point(field_release:PrivateDealsV3Api.amount)
  return _impl_.amount_.Release();
}
inline void PrivateDealsV3Api::set_allocated_amount(std::string* amount) {
  if (amount != nullptr) {
    
  } else {
    
  }
  _impl_.amount_.SetAllocated(amount, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.amount_.IsDefault()) {
    _impl_.amount_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateDealsV3Api.amount)
}

// int32 tradeType = 4;
inline void PrivateDealsV3Api::clear_tradetype() {
  _impl_.tradetype_ = 0;
}
inline int32_t PrivateDealsV3Api::_internal_tradetype() const {
  return _impl_.tradetype_;
}
inline int32_t PrivateDealsV3Api::tradetype() const {
  // @@protoc_insertion_point(field_get:PrivateDealsV3Api.tradeType)
  return _internal_tradetype();
}
inline void PrivateDealsV3Api::_internal_set_tradetype(int32_t value) {
  
  _impl_.tradetype_ = value;
}
inline void PrivateDealsV3Api::set_tradetype(int32_t value) {
  _internal_set_tradetype(value);
  // @@protoc_insertion_point(field_set:PrivateDealsV3Api.tradeType)
}

// bool isMaker = 5;
inline void PrivateDealsV3Api::clear_ismaker() {
  _impl_.ismaker_ = false;
}
inline bool PrivateDealsV3Api::_internal_ismaker() const {
  return _impl_.ismaker_;
}
inline bool PrivateDealsV3Api::ismaker() const {
  // @@protoc_insertion_point(field_get:PrivateDealsV3Api.isMaker)
  return _internal_ismaker();
}
inline void PrivateDealsV3Api::_internal_set_ismaker(bool value) {
  
  _impl_.ismaker_ = value;
}
inline void PrivateDealsV3Api::set_ismaker(bool value) {
  _internal_set_ismaker(value);
  // @@protoc_insertion_point(field_set:PrivateDealsV3Api.isMaker)
}

// bool isSelfTrade = 6;
inline void PrivateDealsV3Api::clear_isselftrade() {
  _impl_.isselftrade_ = false;
}
inline bool PrivateDealsV3Api::_internal_isselftrade() const {
  return _impl_.isselftrade_;
}
inline bool PrivateDealsV3Api::isselftrade() const {
  // @@protoc_insertion_point(field_get:PrivateDealsV3Api.isSelfTrade)
  return _internal_isselftrade();
}
inline void PrivateDealsV3Api::_internal_set_isselftrade(bool value) {
  
  _impl_.isselftrade_ = value;
}
inline void PrivateDealsV3Api::set_isselftrade(bool value) {
  _internal_set_isselftrade(value);
  // @@protoc_insertion_point(field_set:PrivateDealsV3Api.isSelfTrade)
}

// string tradeId = 7;
inline void PrivateDealsV3Api::clear_tradeid() {
  _impl_.tradeid_.ClearToEmpty();
}
inline const std::string& PrivateDealsV3Api::tradeid() const {
  // @@protoc_insertion_point(field_get:PrivateDealsV3Api.tradeId)
  return _internal_tradeid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateDealsV3Api::set_tradeid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.tradeid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateDealsV3Api.tradeId)
}
inline std::string* PrivateDealsV3Api::mutable_tradeid() {
  std::string* _s = _internal_mutable_tradeid();
  // @@protoc_insertion_point(field_mutable:PrivateDealsV3Api.tradeId)
  return _s;
}
inline const std::string& PrivateDealsV3Api::_internal_tradeid() const {
  return _impl_.tradeid_.Get();
}
inline void PrivateDealsV3Api::_internal_set_tradeid(const std::string& value) {
  
  _impl_.tradeid_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::_internal_mutable_tradeid() {
  
  return _impl_.tradeid_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::release_tradeid() {
  // @@protoc_insertion_point(field_release:PrivateDealsV3Api.tradeId)
  return _impl_.tradeid_.Release();
}
inline void PrivateDealsV3Api::set_allocated_tradeid(std::string* tradeid) {
  if (tradeid != nullptr) {
    
  } else {
    
  }
  _impl_.tradeid_.SetAllocated(tradeid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.tradeid_.IsDefault()) {
    _impl_.tradeid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateDealsV3Api.tradeId)
}

// string clientOrderId = 8;
inline void PrivateDealsV3Api::clear_clientorderid() {
  _impl_.clientorderid_.ClearToEmpty();
}
inline const std::string& PrivateDealsV3Api::clientorderid() const {
  // @@protoc_insertion_point(field_get:PrivateDealsV3Api.clientOrderId)
  return _internal_clientorderid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateDealsV3Api::set_clientorderid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.clientorderid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateDealsV3Api.clientOrderId)
}
inline std::string* PrivateDealsV3Api::mutable_clientorderid() {
  std::string* _s = _internal_mutable_clientorderid();
  // @@protoc_insertion_point(field_mutable:PrivateDealsV3Api.clientOrderId)
  return _s;
}
inline const std::string& PrivateDealsV3Api::_internal_clientorderid() const {
  return _impl_.clientorderid_.Get();
}
inline void PrivateDealsV3Api::_internal_set_clientorderid(const std::string& value) {
  
  _impl_.clientorderid_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::_internal_mutable_clientorderid() {
  
  return _impl_.clientorderid_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::release_clientorderid() {
  // @@protoc_insertion_point(field_release:PrivateDealsV3Api.clientOrderId)
  return _impl_.clientorderid_.Release();
}
inline void PrivateDealsV3Api::set_allocated_clientorderid(std::string* clientorderid) {
  if (clientorderid != nullptr) {
    
  } else {
    
  }
  _impl_.clientorderid_.SetAllocated(clientorderid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.clientorderid_.IsDefault()) {
    _impl_.clientorderid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateDealsV3Api.clientOrderId)
}

// string orderId = 9;
inline void PrivateDealsV3Api::clear_orderid() {
  _impl_.orderid_.ClearToEmpty();
}
inline const std::string& PrivateDealsV3Api::orderid() const {
  // @@protoc_insertion_point(field_get:PrivateDealsV3Api.orderId)
  return _internal_orderid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateDealsV3Api::set_orderid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.orderid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateDealsV3Api.orderId)
}
inline std::string* PrivateDealsV3Api::mutable_orderid() {
  std::string* _s = _internal_mutable_orderid();
  // @@protoc_insertion_point(field_mutable:PrivateDealsV3Api.orderId)
  return _s;
}
inline const std::string& PrivateDealsV3Api::_internal_orderid() const {
  return _impl_.orderid_.Get();
}
inline void PrivateDealsV3Api::_internal_set_orderid(const std::string& value) {
  
  _impl_.orderid_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::_internal_mutable_orderid() {
  
  return _impl_.orderid_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::release_orderid() {
  // @@protoc_insertion_point(field_release:PrivateDealsV3Api.orderId)
  return _impl_.orderid_.Release();
}
inline void PrivateDealsV3Api::set_allocated_orderid(std::string* orderid) {
  if (orderid != nullptr) {
    
  } else {
    
  }
  _impl_.orderid_.SetAllocated(orderid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.orderid_.IsDefault()) {
    _impl_.orderid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateDealsV3Api.orderId)
}

// string feeAmount = 10;
inline void PrivateDealsV3Api::clear_feeamount() {
  _impl_.feeamount_.ClearToEmpty();
}
inline const std::string& PrivateDealsV3Api::feeamount() const {
  // @@protoc_insertion_point(field_get:PrivateDealsV3Api.feeAmount)
  return _internal_feeamount();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateDealsV3Api::set_feeamount(ArgT0&& arg0, ArgT... args) {
 
 _impl_.feeamount_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateDealsV3Api.feeAmount)
}
inline std::string* PrivateDealsV3Api::mutable_feeamount() {
  std::string* _s = _internal_mutable_feeamount();
  // @@protoc_insertion_point(field_mutable:PrivateDealsV3Api.feeAmount)
  return _s;
}
inline const std::string& PrivateDealsV3Api::_internal_feeamount() const {
  return _impl_.feeamount_.Get();
}
inline void PrivateDealsV3Api::_internal_set_feeamount(const std::string& value) {
  
  _impl_.feeamount_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::_internal_mutable_feeamount() {
  
  return _impl_.feeamount_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::release_feeamount() {
  // @@protoc_insertion_point(field_release:PrivateDealsV3Api.feeAmount)
  return _impl_.feeamount_.Release();
}
inline void PrivateDealsV3Api::set_allocated_feeamount(std::string* feeamount) {
  if (feeamount != nullptr) {
    
  } else {
    
  }
  _impl_.feeamount_.SetAllocated(feeamount, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.feeamount_.IsDefault()) {
    _impl_.feeamount_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateDealsV3Api.feeAmount)
}

// string feeCurrency = 11;
inline void PrivateDealsV3Api::clear_feecurrency() {
  _impl_.feecurrency_.ClearToEmpty();
}
inline const std::string& PrivateDealsV3Api::feecurrency() const {
  // @@protoc_insertion_point(field_get:PrivateDealsV3Api.feeCurrency)
  return _internal_feecurrency();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateDealsV3Api::set_feecurrency(ArgT0&& arg0, ArgT... args) {
 
 _impl_.feecurrency_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateDealsV3Api.feeCurrency)
}
inline std::string* PrivateDealsV3Api::mutable_feecurrency() {
  std::string* _s = _internal_mutable_feecurrency();
  // @@protoc_insertion_point(field_mutable:PrivateDealsV3Api.feeCurrency)
  return _s;
}
inline const std::string& PrivateDealsV3Api::_internal_feecurrency() const {
  return _impl_.feecurrency_.Get();
}
inline void PrivateDealsV3Api::_internal_set_feecurrency(const std::string& value) {
  
  _impl_.feecurrency_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::_internal_mutable_feecurrency() {
  
  return _impl_.feecurrency_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateDealsV3Api::release_feecurrency() {
  // @@protoc_insertion_point(field_release:PrivateDealsV3Api.feeCurrency)
  return _impl_.feecurrency_.Release();
}
inline void PrivateDealsV3Api::set_allocated_feecurrency(std::string* feecurrency) {
  if (feecurrency != nullptr) {
    
  } else {
    
  }
  _impl_.feecurrency_.SetAllocated(feecurrency, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.feecurrency_.IsDefault()) {
    _impl_.feecurrency_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateDealsV3Api.feeCurrency)
}

// int64 time = 12;
inline void PrivateDealsV3Api::clear_time() {
  _impl_.time_ = int64_t{0};
}
inline int64_t PrivateDealsV3Api::_internal_time() const {
  return _impl_.time_;
}
inline int64_t PrivateDealsV3Api::time() const {
  // @@protoc_insertion_point(field_get:PrivateDealsV3Api.time)
  return _internal_time();
}
inline void PrivateDealsV3Api::_internal_set_time(int64_t value) {
  
  _impl_.time_ = value;
}
inline void PrivateDealsV3Api::set_time(int64_t value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:PrivateDealsV3Api.time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PrivateDealsV3Api_2eproto
