// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrivateOrdersV3Api.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PrivateOrdersV3Api_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PrivateOrdersV3Api_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PrivateOrdersV3Api_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PrivateOrdersV3Api_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PrivateOrdersV3Api_2eproto;
class PrivateOrdersV3Api;
struct PrivateOrdersV3ApiDefaultTypeInternal;
extern PrivateOrdersV3ApiDefaultTypeInternal _PrivateOrdersV3Api_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PrivateOrdersV3Api* Arena::CreateMaybeMessage<::PrivateOrdersV3Api>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PrivateOrdersV3Api final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PrivateOrdersV3Api) */ {
 public:
  inline PrivateOrdersV3Api() : PrivateOrdersV3Api(nullptr) {}
  ~PrivateOrdersV3Api() override;
  explicit PROTOBUF_CONSTEXPR PrivateOrdersV3Api(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PrivateOrdersV3Api(const PrivateOrdersV3Api& from);
  PrivateOrdersV3Api(PrivateOrdersV3Api&& from) noexcept
    : PrivateOrdersV3Api() {
    *this = ::std::move(from);
  }

  inline PrivateOrdersV3Api& operator=(const PrivateOrdersV3Api& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrivateOrdersV3Api& operator=(PrivateOrdersV3Api&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PrivateOrdersV3Api& default_instance() {
    return *internal_default_instance();
  }
  static inline const PrivateOrdersV3Api* internal_default_instance() {
    return reinterpret_cast<const PrivateOrdersV3Api*>(
               &_PrivateOrdersV3Api_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PrivateOrdersV3Api& a, PrivateOrdersV3Api& b) {
    a.Swap(&b);
  }
  inline void Swap(PrivateOrdersV3Api* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrivateOrdersV3Api* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PrivateOrdersV3Api* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PrivateOrdersV3Api>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PrivateOrdersV3Api& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PrivateOrdersV3Api& from) {
    PrivateOrdersV3Api::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrivateOrdersV3Api* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PrivateOrdersV3Api";
  }
  protected:
  explicit PrivateOrdersV3Api(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kClientIdFieldNumber = 2,
    kPriceFieldNumber = 3,
    kQuantityFieldNumber = 4,
    kAmountFieldNumber = 5,
    kAvgPriceFieldNumber = 6,
    kRemainAmountFieldNumber = 10,
    kRemainQuantityFieldNumber = 11,
    kLastDealQuantityFieldNumber = 12,
    kCumulativeQuantityFieldNumber = 13,
    kCumulativeAmountFieldNumber = 14,
    kMarketFieldNumber = 17,
    kTriggerPriceFieldNumber = 19,
    kOcoIdFieldNumber = 21,
    kRouteFactorFieldNumber = 22,
    kSymbolIdFieldNumber = 23,
    kMarketIdFieldNumber = 24,
    kMarketCurrencyIdFieldNumber = 25,
    kCurrencyIdFieldNumber = 26,
    kOrderTypeFieldNumber = 7,
    kTradeTypeFieldNumber = 8,
    kIsMakerFieldNumber = 9,
    kStatusFieldNumber = 15,
    kCreateTimeFieldNumber = 16,
    kTriggerTypeFieldNumber = 18,
    kStateFieldNumber = 20,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string clientId = 2;
  void clear_clientid();
  const std::string& clientid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_clientid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_clientid();
  PROTOBUF_NODISCARD std::string* release_clientid();
  void set_allocated_clientid(std::string* clientid);
  private:
  const std::string& _internal_clientid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_clientid(const std::string& value);
  std::string* _internal_mutable_clientid();
  public:

  // string price = 3;
  void clear_price();
  const std::string& price() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_price(ArgT0&& arg0, ArgT... args);
  std::string* mutable_price();
  PROTOBUF_NODISCARD std::string* release_price();
  void set_allocated_price(std::string* price);
  private:
  const std::string& _internal_price() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_price(const std::string& value);
  std::string* _internal_mutable_price();
  public:

  // string quantity = 4;
  void clear_quantity();
  const std::string& quantity() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_quantity(ArgT0&& arg0, ArgT... args);
  std::string* mutable_quantity();
  PROTOBUF_NODISCARD std::string* release_quantity();
  void set_allocated_quantity(std::string* quantity);
  private:
  const std::string& _internal_quantity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_quantity(const std::string& value);
  std::string* _internal_mutable_quantity();
  public:

  // string amount = 5;
  void clear_amount();
  const std::string& amount() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_amount(ArgT0&& arg0, ArgT... args);
  std::string* mutable_amount();
  PROTOBUF_NODISCARD std::string* release_amount();
  void set_allocated_amount(std::string* amount);
  private:
  const std::string& _internal_amount() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_amount(const std::string& value);
  std::string* _internal_mutable_amount();
  public:

  // string avgPrice = 6;
  void clear_avgprice();
  const std::string& avgprice() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_avgprice(ArgT0&& arg0, ArgT... args);
  std::string* mutable_avgprice();
  PROTOBUF_NODISCARD std::string* release_avgprice();
  void set_allocated_avgprice(std::string* avgprice);
  private:
  const std::string& _internal_avgprice() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_avgprice(const std::string& value);
  std::string* _internal_mutable_avgprice();
  public:

  // string remainAmount = 10;
  void clear_remainamount();
  const std::string& remainamount() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_remainamount(ArgT0&& arg0, ArgT... args);
  std::string* mutable_remainamount();
  PROTOBUF_NODISCARD std::string* release_remainamount();
  void set_allocated_remainamount(std::string* remainamount);
  private:
  const std::string& _internal_remainamount() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_remainamount(const std::string& value);
  std::string* _internal_mutable_remainamount();
  public:

  // string remainQuantity = 11;
  void clear_remainquantity();
  const std::string& remainquantity() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_remainquantity(ArgT0&& arg0, ArgT... args);
  std::string* mutable_remainquantity();
  PROTOBUF_NODISCARD std::string* release_remainquantity();
  void set_allocated_remainquantity(std::string* remainquantity);
  private:
  const std::string& _internal_remainquantity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_remainquantity(const std::string& value);
  std::string* _internal_mutable_remainquantity();
  public:

  // optional string lastDealQuantity = 12;
  bool has_lastdealquantity() const;
  private:
  bool _internal_has_lastdealquantity() const;
  public:
  void clear_lastdealquantity();
  const std::string& lastdealquantity() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_lastdealquantity(ArgT0&& arg0, ArgT... args);
  std::string* mutable_lastdealquantity();
  PROTOBUF_NODISCARD std::string* release_lastdealquantity();
  void set_allocated_lastdealquantity(std::string* lastdealquantity);
  private:
  const std::string& _internal_lastdealquantity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_lastdealquantity(const std::string& value);
  std::string* _internal_mutable_lastdealquantity();
  public:

  // string cumulativeQuantity = 13;
  void clear_cumulativequantity();
  const std::string& cumulativequantity() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_cumulativequantity(ArgT0&& arg0, ArgT... args);
  std::string* mutable_cumulativequantity();
  PROTOBUF_NODISCARD std::string* release_cumulativequantity();
  void set_allocated_cumulativequantity(std::string* cumulativequantity);
  private:
  const std::string& _internal_cumulativequantity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cumulativequantity(const std::string& value);
  std::string* _internal_mutable_cumulativequantity();
  public:

  // string cumulativeAmount = 14;
  void clear_cumulativeamount();
  const std::string& cumulativeamount() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_cumulativeamount(ArgT0&& arg0, ArgT... args);
  std::string* mutable_cumulativeamount();
  PROTOBUF_NODISCARD std::string* release_cumulativeamount();
  void set_allocated_cumulativeamount(std::string* cumulativeamount);
  private:
  const std::string& _internal_cumulativeamount() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cumulativeamount(const std::string& value);
  std::string* _internal_mutable_cumulativeamount();
  public:

  // optional string market = 17;
  bool has_market() const;
  private:
  bool _internal_has_market() const;
  public:
  void clear_market();
  const std::string& market() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_market(ArgT0&& arg0, ArgT... args);
  std::string* mutable_market();
  PROTOBUF_NODISCARD std::string* release_market();
  void set_allocated_market(std::string* market);
  private:
  const std::string& _internal_market() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_market(const std::string& value);
  std::string* _internal_mutable_market();
  public:

  // optional string triggerPrice = 19;
  bool has_triggerprice() const;
  private:
  bool _internal_has_triggerprice() const;
  public:
  void clear_triggerprice();
  const std::string& triggerprice() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_triggerprice(ArgT0&& arg0, ArgT... args);
  std::string* mutable_triggerprice();
  PROTOBUF_NODISCARD std::string* release_triggerprice();
  void set_allocated_triggerprice(std::string* triggerprice);
  private:
  const std::string& _internal_triggerprice() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_triggerprice(const std::string& value);
  std::string* _internal_mutable_triggerprice();
  public:

  // optional string ocoId = 21;
  bool has_ocoid() const;
  private:
  bool _internal_has_ocoid() const;
  public:
  void clear_ocoid();
  const std::string& ocoid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ocoid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ocoid();
  PROTOBUF_NODISCARD std::string* release_ocoid();
  void set_allocated_ocoid(std::string* ocoid);
  private:
  const std::string& _internal_ocoid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ocoid(const std::string& value);
  std::string* _internal_mutable_ocoid();
  public:

  // optional string routeFactor = 22;
  bool has_routefactor() const;
  private:
  bool _internal_has_routefactor() const;
  public:
  void clear_routefactor();
  const std::string& routefactor() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_routefactor(ArgT0&& arg0, ArgT... args);
  std::string* mutable_routefactor();
  PROTOBUF_NODISCARD std::string* release_routefactor();
  void set_allocated_routefactor(std::string* routefactor);
  private:
  const std::string& _internal_routefactor() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_routefactor(const std::string& value);
  std::string* _internal_mutable_routefactor();
  public:

  // optional string symbolId = 23;
  bool has_symbolid() const;
  private:
  bool _internal_has_symbolid() const;
  public:
  void clear_symbolid();
  const std::string& symbolid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_symbolid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_symbolid();
  PROTOBUF_NODISCARD std::string* release_symbolid();
  void set_allocated_symbolid(std::string* symbolid);
  private:
  const std::string& _internal_symbolid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_symbolid(const std::string& value);
  std::string* _internal_mutable_symbolid();
  public:

  // optional string marketId = 24;
  bool has_marketid() const;
  private:
  bool _internal_has_marketid() const;
  public:
  void clear_marketid();
  const std::string& marketid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_marketid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_marketid();
  PROTOBUF_NODISCARD std::string* release_marketid();
  void set_allocated_marketid(std::string* marketid);
  private:
  const std::string& _internal_marketid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_marketid(const std::string& value);
  std::string* _internal_mutable_marketid();
  public:

  // optional string marketCurrencyId = 25;
  bool has_marketcurrencyid() const;
  private:
  bool _internal_has_marketcurrencyid() const;
  public:
  void clear_marketcurrencyid();
  const std::string& marketcurrencyid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_marketcurrencyid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_marketcurrencyid();
  PROTOBUF_NODISCARD std::string* release_marketcurrencyid();
  void set_allocated_marketcurrencyid(std::string* marketcurrencyid);
  private:
  const std::string& _internal_marketcurrencyid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_marketcurrencyid(const std::string& value);
  std::string* _internal_mutable_marketcurrencyid();
  public:

  // optional string currencyId = 26;
  bool has_currencyid() const;
  private:
  bool _internal_has_currencyid() const;
  public:
  void clear_currencyid();
  const std::string& currencyid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_currencyid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_currencyid();
  PROTOBUF_NODISCARD std::string* release_currencyid();
  void set_allocated_currencyid(std::string* currencyid);
  private:
  const std::string& _internal_currencyid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_currencyid(const std::string& value);
  std::string* _internal_mutable_currencyid();
  public:

  // int32 orderType = 7;
  void clear_ordertype();
  int32_t ordertype() const;
  void set_ordertype(int32_t value);
  private:
  int32_t _internal_ordertype() const;
  void _internal_set_ordertype(int32_t value);
  public:

  // int32 tradeType = 8;
  void clear_tradetype();
  int32_t tradetype() const;
  void set_tradetype(int32_t value);
  private:
  int32_t _internal_tradetype() const;
  void _internal_set_tradetype(int32_t value);
  public:

  // bool isMaker = 9;
  void clear_ismaker();
  bool ismaker() const;
  void set_ismaker(bool value);
  private:
  bool _internal_ismaker() const;
  void _internal_set_ismaker(bool value);
  public:

  // int32 status = 15;
  void clear_status();
  int32_t status() const;
  void set_status(int32_t value);
  private:
  int32_t _internal_status() const;
  void _internal_set_status(int32_t value);
  public:

  // int64 createTime = 16;
  void clear_createtime();
  int64_t createtime() const;
  void set_createtime(int64_t value);
  private:
  int64_t _internal_createtime() const;
  void _internal_set_createtime(int64_t value);
  public:

  // optional int32 triggerType = 18;
  bool has_triggertype() const;
  private:
  bool _internal_has_triggertype() const;
  public:
  void clear_triggertype();
  int32_t triggertype() const;
  void set_triggertype(int32_t value);
  private:
  int32_t _internal_triggertype() const;
  void _internal_set_triggertype(int32_t value);
  public:

  // optional int32 state = 20;
  bool has_state() const;
  private:
  bool _internal_has_state() const;
  public:
  void clear_state();
  int32_t state() const;
  void set_state(int32_t value);
  private:
  int32_t _internal_state() const;
  void _internal_set_state(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PrivateOrdersV3Api)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr clientid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr price_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr quantity_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr amount_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr avgprice_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr remainamount_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr remainquantity_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lastdealquantity_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cumulativequantity_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cumulativeamount_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr market_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr triggerprice_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ocoid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr routefactor_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr symbolid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr marketid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr marketcurrencyid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr currencyid_;
    int32_t ordertype_;
    int32_t tradetype_;
    bool ismaker_;
    int32_t status_;
    int64_t createtime_;
    int32_t triggertype_;
    int32_t state_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PrivateOrdersV3Api_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PrivateOrdersV3Api

// string id = 1;
inline void PrivateOrdersV3Api::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& PrivateOrdersV3Api::id() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.id)
}
inline std::string* PrivateOrdersV3Api::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.id)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_id() const {
  return _impl_.id_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_id(const std::string& value) {
  
  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_id() {
  
  return _impl_.id_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_id() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.id)
  return _impl_.id_.Release();
}
inline void PrivateOrdersV3Api::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  _impl_.id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.id)
}

// string clientId = 2;
inline void PrivateOrdersV3Api::clear_clientid() {
  _impl_.clientid_.ClearToEmpty();
}
inline const std::string& PrivateOrdersV3Api::clientid() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.clientId)
  return _internal_clientid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_clientid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.clientid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.clientId)
}
inline std::string* PrivateOrdersV3Api::mutable_clientid() {
  std::string* _s = _internal_mutable_clientid();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.clientId)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_clientid() const {
  return _impl_.clientid_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_clientid(const std::string& value) {
  
  _impl_.clientid_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_clientid() {
  
  return _impl_.clientid_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_clientid() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.clientId)
  return _impl_.clientid_.Release();
}
inline void PrivateOrdersV3Api::set_allocated_clientid(std::string* clientid) {
  if (clientid != nullptr) {
    
  } else {
    
  }
  _impl_.clientid_.SetAllocated(clientid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.clientid_.IsDefault()) {
    _impl_.clientid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.clientId)
}

// string price = 3;
inline void PrivateOrdersV3Api::clear_price() {
  _impl_.price_.ClearToEmpty();
}
inline const std::string& PrivateOrdersV3Api::price() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.price)
  return _internal_price();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_price(ArgT0&& arg0, ArgT... args) {
 
 _impl_.price_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.price)
}
inline std::string* PrivateOrdersV3Api::mutable_price() {
  std::string* _s = _internal_mutable_price();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.price)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_price() const {
  return _impl_.price_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_price(const std::string& value) {
  
  _impl_.price_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_price() {
  
  return _impl_.price_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_price() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.price)
  return _impl_.price_.Release();
}
inline void PrivateOrdersV3Api::set_allocated_price(std::string* price) {
  if (price != nullptr) {
    
  } else {
    
  }
  _impl_.price_.SetAllocated(price, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.price_.IsDefault()) {
    _impl_.price_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.price)
}

// string quantity = 4;
inline void PrivateOrdersV3Api::clear_quantity() {
  _impl_.quantity_.ClearToEmpty();
}
inline const std::string& PrivateOrdersV3Api::quantity() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.quantity)
  return _internal_quantity();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_quantity(ArgT0&& arg0, ArgT... args) {
 
 _impl_.quantity_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.quantity)
}
inline std::string* PrivateOrdersV3Api::mutable_quantity() {
  std::string* _s = _internal_mutable_quantity();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.quantity)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_quantity() const {
  return _impl_.quantity_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_quantity(const std::string& value) {
  
  _impl_.quantity_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_quantity() {
  
  return _impl_.quantity_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_quantity() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.quantity)
  return _impl_.quantity_.Release();
}
inline void PrivateOrdersV3Api::set_allocated_quantity(std::string* quantity) {
  if (quantity != nullptr) {
    
  } else {
    
  }
  _impl_.quantity_.SetAllocated(quantity, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.quantity_.IsDefault()) {
    _impl_.quantity_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.quantity)
}

// string amount = 5;
inline void PrivateOrdersV3Api::clear_amount() {
  _impl_.amount_.ClearToEmpty();
}
inline const std::string& PrivateOrdersV3Api::amount() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.amount)
  return _internal_amount();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_amount(ArgT0&& arg0, ArgT... args) {
 
 _impl_.amount_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.amount)
}
inline std::string* PrivateOrdersV3Api::mutable_amount() {
  std::string* _s = _internal_mutable_amount();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.amount)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_amount() const {
  return _impl_.amount_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_amount(const std::string& value) {
  
  _impl_.amount_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_amount() {
  
  return _impl_.amount_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_amount() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.amount)
  return _impl_.amount_.Release();
}
inline void PrivateOrdersV3Api::set_allocated_amount(std::string* amount) {
  if (amount != nullptr) {
    
  } else {
    
  }
  _impl_.amount_.SetAllocated(amount, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.amount_.IsDefault()) {
    _impl_.amount_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.amount)
}

// string avgPrice = 6;
inline void PrivateOrdersV3Api::clear_avgprice() {
  _impl_.avgprice_.ClearToEmpty();
}
inline const std::string& PrivateOrdersV3Api::avgprice() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.avgPrice)
  return _internal_avgprice();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_avgprice(ArgT0&& arg0, ArgT... args) {
 
 _impl_.avgprice_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.avgPrice)
}
inline std::string* PrivateOrdersV3Api::mutable_avgprice() {
  std::string* _s = _internal_mutable_avgprice();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.avgPrice)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_avgprice() const {
  return _impl_.avgprice_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_avgprice(const std::string& value) {
  
  _impl_.avgprice_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_avgprice() {
  
  return _impl_.avgprice_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_avgprice() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.avgPrice)
  return _impl_.avgprice_.Release();
}
inline void PrivateOrdersV3Api::set_allocated_avgprice(std::string* avgprice) {
  if (avgprice != nullptr) {
    
  } else {
    
  }
  _impl_.avgprice_.SetAllocated(avgprice, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.avgprice_.IsDefault()) {
    _impl_.avgprice_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.avgPrice)
}

// int32 orderType = 7;
inline void PrivateOrdersV3Api::clear_ordertype() {
  _impl_.ordertype_ = 0;
}
inline int32_t PrivateOrdersV3Api::_internal_ordertype() const {
  return _impl_.ordertype_;
}
inline int32_t PrivateOrdersV3Api::ordertype() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.orderType)
  return _internal_ordertype();
}
inline void PrivateOrdersV3Api::_internal_set_ordertype(int32_t value) {
  
  _impl_.ordertype_ = value;
}
inline void PrivateOrdersV3Api::set_ordertype(int32_t value) {
  _internal_set_ordertype(value);
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.orderType)
}

// int32 tradeType = 8;
inline void PrivateOrdersV3Api::clear_tradetype() {
  _impl_.tradetype_ = 0;
}
inline int32_t PrivateOrdersV3Api::_internal_tradetype() const {
  return _impl_.tradetype_;
}
inline int32_t PrivateOrdersV3Api::tradetype() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.tradeType)
  return _internal_tradetype();
}
inline void PrivateOrdersV3Api::_internal_set_tradetype(int32_t value) {
  
  _impl_.tradetype_ = value;
}
inline void PrivateOrdersV3Api::set_tradetype(int32_t value) {
  _internal_set_tradetype(value);
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.tradeType)
}

// bool isMaker = 9;
inline void PrivateOrdersV3Api::clear_ismaker() {
  _impl_.ismaker_ = false;
}
inline bool PrivateOrdersV3Api::_internal_ismaker() const {
  return _impl_.ismaker_;
}
inline bool PrivateOrdersV3Api::ismaker() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.isMaker)
  return _internal_ismaker();
}
inline void PrivateOrdersV3Api::_internal_set_ismaker(bool value) {
  
  _impl_.ismaker_ = value;
}
inline void PrivateOrdersV3Api::set_ismaker(bool value) {
  _internal_set_ismaker(value);
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.isMaker)
}

// string remainAmount = 10;
inline void PrivateOrdersV3Api::clear_remainamount() {
  _impl_.remainamount_.ClearToEmpty();
}
inline const std::string& PrivateOrdersV3Api::remainamount() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.remainAmount)
  return _internal_remainamount();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_remainamount(ArgT0&& arg0, ArgT... args) {
 
 _impl_.remainamount_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.remainAmount)
}
inline std::string* PrivateOrdersV3Api::mutable_remainamount() {
  std::string* _s = _internal_mutable_remainamount();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.remainAmount)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_remainamount() const {
  return _impl_.remainamount_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_remainamount(const std::string& value) {
  
  _impl_.remainamount_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_remainamount() {
  
  return _impl_.remainamount_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_remainamount() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.remainAmount)
  return _impl_.remainamount_.Release();
}
inline void PrivateOrdersV3Api::set_allocated_remainamount(std::string* remainamount) {
  if (remainamount != nullptr) {
    
  } else {
    
  }
  _impl_.remainamount_.SetAllocated(remainamount, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.remainamount_.IsDefault()) {
    _impl_.remainamount_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.remainAmount)
}

// string remainQuantity = 11;
inline void PrivateOrdersV3Api::clear_remainquantity() {
  _impl_.remainquantity_.ClearToEmpty();
}
inline const std::string& PrivateOrdersV3Api::remainquantity() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.remainQuantity)
  return _internal_remainquantity();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_remainquantity(ArgT0&& arg0, ArgT... args) {
 
 _impl_.remainquantity_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.remainQuantity)
}
inline std::string* PrivateOrdersV3Api::mutable_remainquantity() {
  std::string* _s = _internal_mutable_remainquantity();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.remainQuantity)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_remainquantity() const {
  return _impl_.remainquantity_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_remainquantity(const std::string& value) {
  
  _impl_.remainquantity_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_remainquantity() {
  
  return _impl_.remainquantity_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_remainquantity() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.remainQuantity)
  return _impl_.remainquantity_.Release();
}
inline void PrivateOrdersV3Api::set_allocated_remainquantity(std::string* remainquantity) {
  if (remainquantity != nullptr) {
    
  } else {
    
  }
  _impl_.remainquantity_.SetAllocated(remainquantity, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.remainquantity_.IsDefault()) {
    _impl_.remainquantity_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.remainQuantity)
}

// optional string lastDealQuantity = 12;
inline bool PrivateOrdersV3Api::_internal_has_lastdealquantity() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PrivateOrdersV3Api::has_lastdealquantity() const {
  return _internal_has_lastdealquantity();
}
inline void PrivateOrdersV3Api::clear_lastdealquantity() {
  _impl_.lastdealquantity_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PrivateOrdersV3Api::lastdealquantity() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.lastDealQuantity)
  return _internal_lastdealquantity();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_lastdealquantity(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.lastdealquantity_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.lastDealQuantity)
}
inline std::string* PrivateOrdersV3Api::mutable_lastdealquantity() {
  std::string* _s = _internal_mutable_lastdealquantity();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.lastDealQuantity)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_lastdealquantity() const {
  return _impl_.lastdealquantity_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_lastdealquantity(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.lastdealquantity_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_lastdealquantity() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.lastdealquantity_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_lastdealquantity() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.lastDealQuantity)
  if (!_internal_has_lastdealquantity()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.lastdealquantity_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.lastdealquantity_.IsDefault()) {
    _impl_.lastdealquantity_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PrivateOrdersV3Api::set_allocated_lastdealquantity(std::string* lastdealquantity) {
  if (lastdealquantity != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.lastdealquantity_.SetAllocated(lastdealquantity, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.lastdealquantity_.IsDefault()) {
    _impl_.lastdealquantity_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.lastDealQuantity)
}

// string cumulativeQuantity = 13;
inline void PrivateOrdersV3Api::clear_cumulativequantity() {
  _impl_.cumulativequantity_.ClearToEmpty();
}
inline const std::string& PrivateOrdersV3Api::cumulativequantity() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.cumulativeQuantity)
  return _internal_cumulativequantity();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_cumulativequantity(ArgT0&& arg0, ArgT... args) {
 
 _impl_.cumulativequantity_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.cumulativeQuantity)
}
inline std::string* PrivateOrdersV3Api::mutable_cumulativequantity() {
  std::string* _s = _internal_mutable_cumulativequantity();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.cumulativeQuantity)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_cumulativequantity() const {
  return _impl_.cumulativequantity_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_cumulativequantity(const std::string& value) {
  
  _impl_.cumulativequantity_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_cumulativequantity() {
  
  return _impl_.cumulativequantity_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_cumulativequantity() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.cumulativeQuantity)
  return _impl_.cumulativequantity_.Release();
}
inline void PrivateOrdersV3Api::set_allocated_cumulativequantity(std::string* cumulativequantity) {
  if (cumulativequantity != nullptr) {
    
  } else {
    
  }
  _impl_.cumulativequantity_.SetAllocated(cumulativequantity, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.cumulativequantity_.IsDefault()) {
    _impl_.cumulativequantity_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.cumulativeQuantity)
}

// string cumulativeAmount = 14;
inline void PrivateOrdersV3Api::clear_cumulativeamount() {
  _impl_.cumulativeamount_.ClearToEmpty();
}
inline const std::string& PrivateOrdersV3Api::cumulativeamount() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.cumulativeAmount)
  return _internal_cumulativeamount();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_cumulativeamount(ArgT0&& arg0, ArgT... args) {
 
 _impl_.cumulativeamount_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.cumulativeAmount)
}
inline std::string* PrivateOrdersV3Api::mutable_cumulativeamount() {
  std::string* _s = _internal_mutable_cumulativeamount();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.cumulativeAmount)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_cumulativeamount() const {
  return _impl_.cumulativeamount_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_cumulativeamount(const std::string& value) {
  
  _impl_.cumulativeamount_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_cumulativeamount() {
  
  return _impl_.cumulativeamount_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_cumulativeamount() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.cumulativeAmount)
  return _impl_.cumulativeamount_.Release();
}
inline void PrivateOrdersV3Api::set_allocated_cumulativeamount(std::string* cumulativeamount) {
  if (cumulativeamount != nullptr) {
    
  } else {
    
  }
  _impl_.cumulativeamount_.SetAllocated(cumulativeamount, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.cumulativeamount_.IsDefault()) {
    _impl_.cumulativeamount_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.cumulativeAmount)
}

// int32 status = 15;
inline void PrivateOrdersV3Api::clear_status() {
  _impl_.status_ = 0;
}
inline int32_t PrivateOrdersV3Api::_internal_status() const {
  return _impl_.status_;
}
inline int32_t PrivateOrdersV3Api::status() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.status)
  return _internal_status();
}
inline void PrivateOrdersV3Api::_internal_set_status(int32_t value) {
  
  _impl_.status_ = value;
}
inline void PrivateOrdersV3Api::set_status(int32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.status)
}

// int64 createTime = 16;
inline void PrivateOrdersV3Api::clear_createtime() {
  _impl_.createtime_ = int64_t{0};
}
inline int64_t PrivateOrdersV3Api::_internal_createtime() const {
  return _impl_.createtime_;
}
inline int64_t PrivateOrdersV3Api::createtime() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.createTime)
  return _internal_createtime();
}
inline void PrivateOrdersV3Api::_internal_set_createtime(int64_t value) {
  
  _impl_.createtime_ = value;
}
inline void PrivateOrdersV3Api::set_createtime(int64_t value) {
  _internal_set_createtime(value);
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.createTime)
}

// optional string market = 17;
inline bool PrivateOrdersV3Api::_internal_has_market() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PrivateOrdersV3Api::has_market() const {
  return _internal_has_market();
}
inline void PrivateOrdersV3Api::clear_market() {
  _impl_.market_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& PrivateOrdersV3Api::market() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.market)
  return _internal_market();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_market(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.market_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.market)
}
inline std::string* PrivateOrdersV3Api::mutable_market() {
  std::string* _s = _internal_mutable_market();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.market)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_market() const {
  return _impl_.market_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_market(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.market_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_market() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.market_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_market() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.market)
  if (!_internal_has_market()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.market_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.market_.IsDefault()) {
    _impl_.market_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PrivateOrdersV3Api::set_allocated_market(std::string* market) {
  if (market != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.market_.SetAllocated(market, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.market_.IsDefault()) {
    _impl_.market_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.market)
}

// optional int32 triggerType = 18;
inline bool PrivateOrdersV3Api::_internal_has_triggertype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool PrivateOrdersV3Api::has_triggertype() const {
  return _internal_has_triggertype();
}
inline void PrivateOrdersV3Api::clear_triggertype() {
  _impl_.triggertype_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline int32_t PrivateOrdersV3Api::_internal_triggertype() const {
  return _impl_.triggertype_;
}
inline int32_t PrivateOrdersV3Api::triggertype() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.triggerType)
  return _internal_triggertype();
}
inline void PrivateOrdersV3Api::_internal_set_triggertype(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000200u;
  _impl_.triggertype_ = value;
}
inline void PrivateOrdersV3Api::set_triggertype(int32_t value) {
  _internal_set_triggertype(value);
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.triggerType)
}

// optional string triggerPrice = 19;
inline bool PrivateOrdersV3Api::_internal_has_triggerprice() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool PrivateOrdersV3Api::has_triggerprice() const {
  return _internal_has_triggerprice();
}
inline void PrivateOrdersV3Api::clear_triggerprice() {
  _impl_.triggerprice_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& PrivateOrdersV3Api::triggerprice() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.triggerPrice)
  return _internal_triggerprice();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_triggerprice(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.triggerprice_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.triggerPrice)
}
inline std::string* PrivateOrdersV3Api::mutable_triggerprice() {
  std::string* _s = _internal_mutable_triggerprice();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.triggerPrice)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_triggerprice() const {
  return _impl_.triggerprice_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_triggerprice(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.triggerprice_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_triggerprice() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.triggerprice_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_triggerprice() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.triggerPrice)
  if (!_internal_has_triggerprice()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.triggerprice_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.triggerprice_.IsDefault()) {
    _impl_.triggerprice_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PrivateOrdersV3Api::set_allocated_triggerprice(std::string* triggerprice) {
  if (triggerprice != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.triggerprice_.SetAllocated(triggerprice, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.triggerprice_.IsDefault()) {
    _impl_.triggerprice_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.triggerPrice)
}

// optional int32 state = 20;
inline bool PrivateOrdersV3Api::_internal_has_state() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool PrivateOrdersV3Api::has_state() const {
  return _internal_has_state();
}
inline void PrivateOrdersV3Api::clear_state() {
  _impl_.state_ = 0;
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline int32_t PrivateOrdersV3Api::_internal_state() const {
  return _impl_.state_;
}
inline int32_t PrivateOrdersV3Api::state() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.state)
  return _internal_state();
}
inline void PrivateOrdersV3Api::_internal_set_state(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000400u;
  _impl_.state_ = value;
}
inline void PrivateOrdersV3Api::set_state(int32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.state)
}

// optional string ocoId = 21;
inline bool PrivateOrdersV3Api::_internal_has_ocoid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool PrivateOrdersV3Api::has_ocoid() const {
  return _internal_has_ocoid();
}
inline void PrivateOrdersV3Api::clear_ocoid() {
  _impl_.ocoid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& PrivateOrdersV3Api::ocoid() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.ocoId)
  return _internal_ocoid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_ocoid(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000008u;
 _impl_.ocoid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.ocoId)
}
inline std::string* PrivateOrdersV3Api::mutable_ocoid() {
  std::string* _s = _internal_mutable_ocoid();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.ocoId)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_ocoid() const {
  return _impl_.ocoid_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_ocoid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.ocoid_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_ocoid() {
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.ocoid_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_ocoid() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.ocoId)
  if (!_internal_has_ocoid()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* p = _impl_.ocoid_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ocoid_.IsDefault()) {
    _impl_.ocoid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PrivateOrdersV3Api::set_allocated_ocoid(std::string* ocoid) {
  if (ocoid != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.ocoid_.SetAllocated(ocoid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ocoid_.IsDefault()) {
    _impl_.ocoid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.ocoId)
}

// optional string routeFactor = 22;
inline bool PrivateOrdersV3Api::_internal_has_routefactor() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool PrivateOrdersV3Api::has_routefactor() const {
  return _internal_has_routefactor();
}
inline void PrivateOrdersV3Api::clear_routefactor() {
  _impl_.routefactor_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const std::string& PrivateOrdersV3Api::routefactor() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.routeFactor)
  return _internal_routefactor();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_routefactor(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000010u;
 _impl_.routefactor_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.routeFactor)
}
inline std::string* PrivateOrdersV3Api::mutable_routefactor() {
  std::string* _s = _internal_mutable_routefactor();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.routeFactor)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_routefactor() const {
  return _impl_.routefactor_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_routefactor(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.routefactor_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_routefactor() {
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.routefactor_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_routefactor() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.routeFactor)
  if (!_internal_has_routefactor()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* p = _impl_.routefactor_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.routefactor_.IsDefault()) {
    _impl_.routefactor_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PrivateOrdersV3Api::set_allocated_routefactor(std::string* routefactor) {
  if (routefactor != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.routefactor_.SetAllocated(routefactor, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.routefactor_.IsDefault()) {
    _impl_.routefactor_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.routeFactor)
}

// optional string symbolId = 23;
inline bool PrivateOrdersV3Api::_internal_has_symbolid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool PrivateOrdersV3Api::has_symbolid() const {
  return _internal_has_symbolid();
}
inline void PrivateOrdersV3Api::clear_symbolid() {
  _impl_.symbolid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const std::string& PrivateOrdersV3Api::symbolid() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.symbolId)
  return _internal_symbolid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_symbolid(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000020u;
 _impl_.symbolid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.symbolId)
}
inline std::string* PrivateOrdersV3Api::mutable_symbolid() {
  std::string* _s = _internal_mutable_symbolid();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.symbolId)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_symbolid() const {
  return _impl_.symbolid_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_symbolid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.symbolid_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_symbolid() {
  _impl_._has_bits_[0] |= 0x00000020u;
  return _impl_.symbolid_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_symbolid() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.symbolId)
  if (!_internal_has_symbolid()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020u;
  auto* p = _impl_.symbolid_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.symbolid_.IsDefault()) {
    _impl_.symbolid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PrivateOrdersV3Api::set_allocated_symbolid(std::string* symbolid) {
  if (symbolid != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.symbolid_.SetAllocated(symbolid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.symbolid_.IsDefault()) {
    _impl_.symbolid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.symbolId)
}

// optional string marketId = 24;
inline bool PrivateOrdersV3Api::_internal_has_marketid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool PrivateOrdersV3Api::has_marketid() const {
  return _internal_has_marketid();
}
inline void PrivateOrdersV3Api::clear_marketid() {
  _impl_.marketid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline const std::string& PrivateOrdersV3Api::marketid() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.marketId)
  return _internal_marketid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_marketid(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000040u;
 _impl_.marketid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.marketId)
}
inline std::string* PrivateOrdersV3Api::mutable_marketid() {
  std::string* _s = _internal_mutable_marketid();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.marketId)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_marketid() const {
  return _impl_.marketid_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_marketid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.marketid_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_marketid() {
  _impl_._has_bits_[0] |= 0x00000040u;
  return _impl_.marketid_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_marketid() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.marketId)
  if (!_internal_has_marketid()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000040u;
  auto* p = _impl_.marketid_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.marketid_.IsDefault()) {
    _impl_.marketid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PrivateOrdersV3Api::set_allocated_marketid(std::string* marketid) {
  if (marketid != nullptr) {
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }
  _impl_.marketid_.SetAllocated(marketid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.marketid_.IsDefault()) {
    _impl_.marketid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.marketId)
}

// optional string marketCurrencyId = 25;
inline bool PrivateOrdersV3Api::_internal_has_marketcurrencyid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool PrivateOrdersV3Api::has_marketcurrencyid() const {
  return _internal_has_marketcurrencyid();
}
inline void PrivateOrdersV3Api::clear_marketcurrencyid() {
  _impl_.marketcurrencyid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline const std::string& PrivateOrdersV3Api::marketcurrencyid() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.marketCurrencyId)
  return _internal_marketcurrencyid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_marketcurrencyid(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000080u;
 _impl_.marketcurrencyid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.marketCurrencyId)
}
inline std::string* PrivateOrdersV3Api::mutable_marketcurrencyid() {
  std::string* _s = _internal_mutable_marketcurrencyid();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.marketCurrencyId)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_marketcurrencyid() const {
  return _impl_.marketcurrencyid_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_marketcurrencyid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.marketcurrencyid_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_marketcurrencyid() {
  _impl_._has_bits_[0] |= 0x00000080u;
  return _impl_.marketcurrencyid_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_marketcurrencyid() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.marketCurrencyId)
  if (!_internal_has_marketcurrencyid()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000080u;
  auto* p = _impl_.marketcurrencyid_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.marketcurrencyid_.IsDefault()) {
    _impl_.marketcurrencyid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PrivateOrdersV3Api::set_allocated_marketcurrencyid(std::string* marketcurrencyid) {
  if (marketcurrencyid != nullptr) {
    _impl_._has_bits_[0] |= 0x00000080u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000080u;
  }
  _impl_.marketcurrencyid_.SetAllocated(marketcurrencyid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.marketcurrencyid_.IsDefault()) {
    _impl_.marketcurrencyid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.marketCurrencyId)
}

// optional string currencyId = 26;
inline bool PrivateOrdersV3Api::_internal_has_currencyid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool PrivateOrdersV3Api::has_currencyid() const {
  return _internal_has_currencyid();
}
inline void PrivateOrdersV3Api::clear_currencyid() {
  _impl_.currencyid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline const std::string& PrivateOrdersV3Api::currencyid() const {
  // @@protoc_insertion_point(field_get:PrivateOrdersV3Api.currencyId)
  return _internal_currencyid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PrivateOrdersV3Api::set_currencyid(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000100u;
 _impl_.currencyid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PrivateOrdersV3Api.currencyId)
}
inline std::string* PrivateOrdersV3Api::mutable_currencyid() {
  std::string* _s = _internal_mutable_currencyid();
  // @@protoc_insertion_point(field_mutable:PrivateOrdersV3Api.currencyId)
  return _s;
}
inline const std::string& PrivateOrdersV3Api::_internal_currencyid() const {
  return _impl_.currencyid_.Get();
}
inline void PrivateOrdersV3Api::_internal_set_currencyid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.currencyid_.Set(value, GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::_internal_mutable_currencyid() {
  _impl_._has_bits_[0] |= 0x00000100u;
  return _impl_.currencyid_.Mutable(GetArenaForAllocation());
}
inline std::string* PrivateOrdersV3Api::release_currencyid() {
  // @@protoc_insertion_point(field_release:PrivateOrdersV3Api.currencyId)
  if (!_internal_has_currencyid()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000100u;
  auto* p = _impl_.currencyid_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.currencyid_.IsDefault()) {
    _impl_.currencyid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PrivateOrdersV3Api::set_allocated_currencyid(std::string* currencyid) {
  if (currencyid != nullptr) {
    _impl_._has_bits_[0] |= 0x00000100u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000100u;
  }
  _impl_.currencyid_.SetAllocated(currencyid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.currencyid_.IsDefault()) {
    _impl_.currencyid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PrivateOrdersV3Api.currencyId)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PrivateOrdersV3Api_2eproto
