// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicDealsV3Api.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PublicDealsV3Api_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PublicDealsV3Api_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PublicDealsV3Api_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PublicDealsV3Api_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PublicDealsV3Api_2eproto;
class PublicDealsV3Api;
struct PublicDealsV3ApiDefaultTypeInternal;
extern PublicDealsV3ApiDefaultTypeInternal _PublicDealsV3Api_default_instance_;
class PublicDealsV3ApiItem;
struct PublicDealsV3ApiItemDefaultTypeInternal;
extern PublicDealsV3ApiItemDefaultTypeInternal _PublicDealsV3ApiItem_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PublicDealsV3Api* Arena::CreateMaybeMessage<::PublicDealsV3Api>(Arena*);
template<> ::PublicDealsV3ApiItem* Arena::CreateMaybeMessage<::PublicDealsV3ApiItem>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PublicDealsV3Api final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PublicDealsV3Api) */ {
 public:
  inline PublicDealsV3Api() : PublicDealsV3Api(nullptr) {}
  ~PublicDealsV3Api() override;
  explicit PROTOBUF_CONSTEXPR PublicDealsV3Api(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PublicDealsV3Api(const PublicDealsV3Api& from);
  PublicDealsV3Api(PublicDealsV3Api&& from) noexcept
    : PublicDealsV3Api() {
    *this = ::std::move(from);
  }

  inline PublicDealsV3Api& operator=(const PublicDealsV3Api& from) {
    CopyFrom(from);
    return *this;
  }
  inline PublicDealsV3Api& operator=(PublicDealsV3Api&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PublicDealsV3Api& default_instance() {
    return *internal_default_instance();
  }
  static inline const PublicDealsV3Api* internal_default_instance() {
    return reinterpret_cast<const PublicDealsV3Api*>(
               &_PublicDealsV3Api_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PublicDealsV3Api& a, PublicDealsV3Api& b) {
    a.Swap(&b);
  }
  inline void Swap(PublicDealsV3Api* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PublicDealsV3Api* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PublicDealsV3Api* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PublicDealsV3Api>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PublicDealsV3Api& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PublicDealsV3Api& from) {
    PublicDealsV3Api::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PublicDealsV3Api* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PublicDealsV3Api";
  }
  protected:
  explicit PublicDealsV3Api(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDealsFieldNumber = 1,
    kEventTypeFieldNumber = 2,
  };
  // repeated .PublicDealsV3ApiItem deals = 1;
  int deals_size() const;
  private:
  int _internal_deals_size() const;
  public:
  void clear_deals();
  ::PublicDealsV3ApiItem* mutable_deals(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PublicDealsV3ApiItem >*
      mutable_deals();
  private:
  const ::PublicDealsV3ApiItem& _internal_deals(int index) const;
  ::PublicDealsV3ApiItem* _internal_add_deals();
  public:
  const ::PublicDealsV3ApiItem& deals(int index) const;
  ::PublicDealsV3ApiItem* add_deals();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PublicDealsV3ApiItem >&
      deals() const;

  // string eventType = 2;
  void clear_eventtype();
  const std::string& eventtype() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_eventtype(ArgT0&& arg0, ArgT... args);
  std::string* mutable_eventtype();
  PROTOBUF_NODISCARD std::string* release_eventtype();
  void set_allocated_eventtype(std::string* eventtype);
  private:
  const std::string& _internal_eventtype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_eventtype(const std::string& value);
  std::string* _internal_mutable_eventtype();
  public:

  // @@protoc_insertion_point(class_scope:PublicDealsV3Api)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PublicDealsV3ApiItem > deals_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr eventtype_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PublicDealsV3Api_2eproto;
};
// -------------------------------------------------------------------

class PublicDealsV3ApiItem final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PublicDealsV3ApiItem) */ {
 public:
  inline PublicDealsV3ApiItem() : PublicDealsV3ApiItem(nullptr) {}
  ~PublicDealsV3ApiItem() override;
  explicit PROTOBUF_CONSTEXPR PublicDealsV3ApiItem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PublicDealsV3ApiItem(const PublicDealsV3ApiItem& from);
  PublicDealsV3ApiItem(PublicDealsV3ApiItem&& from) noexcept
    : PublicDealsV3ApiItem() {
    *this = ::std::move(from);
  }

  inline PublicDealsV3ApiItem& operator=(const PublicDealsV3ApiItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline PublicDealsV3ApiItem& operator=(PublicDealsV3ApiItem&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PublicDealsV3ApiItem& default_instance() {
    return *internal_default_instance();
  }
  static inline const PublicDealsV3ApiItem* internal_default_instance() {
    return reinterpret_cast<const PublicDealsV3ApiItem*>(
               &_PublicDealsV3ApiItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PublicDealsV3ApiItem& a, PublicDealsV3ApiItem& b) {
    a.Swap(&b);
  }
  inline void Swap(PublicDealsV3ApiItem* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PublicDealsV3ApiItem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PublicDealsV3ApiItem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PublicDealsV3ApiItem>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PublicDealsV3ApiItem& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PublicDealsV3ApiItem& from) {
    PublicDealsV3ApiItem::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PublicDealsV3ApiItem* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PublicDealsV3ApiItem";
  }
  protected:
  explicit PublicDealsV3ApiItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPriceFieldNumber = 1,
    kQuantityFieldNumber = 2,
    kTimeFieldNumber = 4,
    kTradeTypeFieldNumber = 3,
  };
  // string price = 1;
  void clear_price();
  const std::string& price() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_price(ArgT0&& arg0, ArgT... args);
  std::string* mutable_price();
  PROTOBUF_NODISCARD std::string* release_price();
  void set_allocated_price(std::string* price);
  private:
  const std::string& _internal_price() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_price(const std::string& value);
  std::string* _internal_mutable_price();
  public:

  // string quantity = 2;
  void clear_quantity();
  const std::string& quantity() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_quantity(ArgT0&& arg0, ArgT... args);
  std::string* mutable_quantity();
  PROTOBUF_NODISCARD std::string* release_quantity();
  void set_allocated_quantity(std::string* quantity);
  private:
  const std::string& _internal_quantity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_quantity(const std::string& value);
  std::string* _internal_mutable_quantity();
  public:

  // int64 time = 4;
  void clear_time();
  int64_t time() const;
  void set_time(int64_t value);
  private:
  int64_t _internal_time() const;
  void _internal_set_time(int64_t value);
  public:

  // int32 tradeType = 3;
  void clear_tradetype();
  int32_t tradetype() const;
  void set_tradetype(int32_t value);
  private:
  int32_t _internal_tradetype() const;
  void _internal_set_tradetype(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PublicDealsV3ApiItem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr price_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr quantity_;
    int64_t time_;
    int32_t tradetype_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PublicDealsV3Api_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PublicDealsV3Api

// repeated .PublicDealsV3ApiItem deals = 1;
inline int PublicDealsV3Api::_internal_deals_size() const {
  return _impl_.deals_.size();
}
inline int PublicDealsV3Api::deals_size() const {
  return _internal_deals_size();
}
inline void PublicDealsV3Api::clear_deals() {
  _impl_.deals_.Clear();
}
inline ::PublicDealsV3ApiItem* PublicDealsV3Api::mutable_deals(int index) {
  // @@protoc_insertion_point(field_mutable:PublicDealsV3Api.deals)
  return _impl_.deals_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PublicDealsV3ApiItem >*
PublicDealsV3Api::mutable_deals() {
  // @@protoc_insertion_point(field_mutable_list:PublicDealsV3Api.deals)
  return &_impl_.deals_;
}
inline const ::PublicDealsV3ApiItem& PublicDealsV3Api::_internal_deals(int index) const {
  return _impl_.deals_.Get(index);
}
inline const ::PublicDealsV3ApiItem& PublicDealsV3Api::deals(int index) const {
  // @@protoc_insertion_point(field_get:PublicDealsV3Api.deals)
  return _internal_deals(index);
}
inline ::PublicDealsV3ApiItem* PublicDealsV3Api::_internal_add_deals() {
  return _impl_.deals_.Add();
}
inline ::PublicDealsV3ApiItem* PublicDealsV3Api::add_deals() {
  ::PublicDealsV3ApiItem* _add = _internal_add_deals();
  // @@protoc_insertion_point(field_add:PublicDealsV3Api.deals)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PublicDealsV3ApiItem >&
PublicDealsV3Api::deals() const {
  // @@protoc_insertion_point(field_list:PublicDealsV3Api.deals)
  return _impl_.deals_;
}

// string eventType = 2;
inline void PublicDealsV3Api::clear_eventtype() {
  _impl_.eventtype_.ClearToEmpty();
}
inline const std::string& PublicDealsV3Api::eventtype() const {
  // @@protoc_insertion_point(field_get:PublicDealsV3Api.eventType)
  return _internal_eventtype();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PublicDealsV3Api::set_eventtype(ArgT0&& arg0, ArgT... args) {
 
 _impl_.eventtype_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PublicDealsV3Api.eventType)
}
inline std::string* PublicDealsV3Api::mutable_eventtype() {
  std::string* _s = _internal_mutable_eventtype();
  // @@protoc_insertion_point(field_mutable:PublicDealsV3Api.eventType)
  return _s;
}
inline const std::string& PublicDealsV3Api::_internal_eventtype() const {
  return _impl_.eventtype_.Get();
}
inline void PublicDealsV3Api::_internal_set_eventtype(const std::string& value) {
  
  _impl_.eventtype_.Set(value, GetArenaForAllocation());
}
inline std::string* PublicDealsV3Api::_internal_mutable_eventtype() {
  
  return _impl_.eventtype_.Mutable(GetArenaForAllocation());
}
inline std::string* PublicDealsV3Api::release_eventtype() {
  // @@protoc_insertion_point(field_release:PublicDealsV3Api.eventType)
  return _impl_.eventtype_.Release();
}
inline void PublicDealsV3Api::set_allocated_eventtype(std::string* eventtype) {
  if (eventtype != nullptr) {
    
  } else {
    
  }
  _impl_.eventtype_.SetAllocated(eventtype, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.eventtype_.IsDefault()) {
    _impl_.eventtype_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PublicDealsV3Api.eventType)
}

// -------------------------------------------------------------------

// PublicDealsV3ApiItem

// string price = 1;
inline void PublicDealsV3ApiItem::clear_price() {
  _impl_.price_.ClearToEmpty();
}
inline const std::string& PublicDealsV3ApiItem::price() const {
  // @@protoc_insertion_point(field_get:PublicDealsV3ApiItem.price)
  return _internal_price();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PublicDealsV3ApiItem::set_price(ArgT0&& arg0, ArgT... args) {
 
 _impl_.price_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PublicDealsV3ApiItem.price)
}
inline std::string* PublicDealsV3ApiItem::mutable_price() {
  std::string* _s = _internal_mutable_price();
  // @@protoc_insertion_point(field_mutable:PublicDealsV3ApiItem.price)
  return _s;
}
inline const std::string& PublicDealsV3ApiItem::_internal_price() const {
  return _impl_.price_.Get();
}
inline void PublicDealsV3ApiItem::_internal_set_price(const std::string& value) {
  
  _impl_.price_.Set(value, GetArenaForAllocation());
}
inline std::string* PublicDealsV3ApiItem::_internal_mutable_price() {
  
  return _impl_.price_.Mutable(GetArenaForAllocation());
}
inline std::string* PublicDealsV3ApiItem::release_price() {
  // @@protoc_insertion_point(field_release:PublicDealsV3ApiItem.price)
  return _impl_.price_.Release();
}
inline void PublicDealsV3ApiItem::set_allocated_price(std::string* price) {
  if (price != nullptr) {
    
  } else {
    
  }
  _impl_.price_.SetAllocated(price, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.price_.IsDefault()) {
    _impl_.price_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PublicDealsV3ApiItem.price)
}

// string quantity = 2;
inline void PublicDealsV3ApiItem::clear_quantity() {
  _impl_.quantity_.ClearToEmpty();
}
inline const std::string& PublicDealsV3ApiItem::quantity() const {
  // @@protoc_insertion_point(field_get:PublicDealsV3ApiItem.quantity)
  return _internal_quantity();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PublicDealsV3ApiItem::set_quantity(ArgT0&& arg0, ArgT... args) {
 
 _impl_.quantity_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PublicDealsV3ApiItem.quantity)
}
inline std::string* PublicDealsV3ApiItem::mutable_quantity() {
  std::string* _s = _internal_mutable_quantity();
  // @@protoc_insertion_point(field_mutable:PublicDealsV3ApiItem.quantity)
  return _s;
}
inline const std::string& PublicDealsV3ApiItem::_internal_quantity() const {
  return _impl_.quantity_.Get();
}
inline void PublicDealsV3ApiItem::_internal_set_quantity(const std::string& value) {
  
  _impl_.quantity_.Set(value, GetArenaForAllocation());
}
inline std::string* PublicDealsV3ApiItem::_internal_mutable_quantity() {
  
  return _impl_.quantity_.Mutable(GetArenaForAllocation());
}
inline std::string* PublicDealsV3ApiItem::release_quantity() {
  // @@protoc_insertion_point(field_release:PublicDealsV3ApiItem.quantity)
  return _impl_.quantity_.Release();
}
inline void PublicDealsV3ApiItem::set_allocated_quantity(std::string* quantity) {
  if (quantity != nullptr) {
    
  } else {
    
  }
  _impl_.quantity_.SetAllocated(quantity, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.quantity_.IsDefault()) {
    _impl_.quantity_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PublicDealsV3ApiItem.quantity)
}

// int32 tradeType = 3;
inline void PublicDealsV3ApiItem::clear_tradetype() {
  _impl_.tradetype_ = 0;
}
inline int32_t PublicDealsV3ApiItem::_internal_tradetype() const {
  return _impl_.tradetype_;
}
inline int32_t PublicDealsV3ApiItem::tradetype() const {
  // @@protoc_insertion_point(field_get:PublicDealsV3ApiItem.tradeType)
  return _internal_tradetype();
}
inline void PublicDealsV3ApiItem::_internal_set_tradetype(int32_t value) {
  
  _impl_.tradetype_ = value;
}
inline void PublicDealsV3ApiItem::set_tradetype(int32_t value) {
  _internal_set_tradetype(value);
  // @@protoc_insertion_point(field_set:PublicDealsV3ApiItem.tradeType)
}

// int64 time = 4;
inline void PublicDealsV3ApiItem::clear_time() {
  _impl_.time_ = int64_t{0};
}
inline int64_t PublicDealsV3ApiItem::_internal_time() const {
  return _impl_.time_;
}
inline int64_t PublicDealsV3ApiItem::time() const {
  // @@protoc_insertion_point(field_get:PublicDealsV3ApiItem.time)
  return _internal_time();
}
inline void PublicDealsV3ApiItem::_internal_set_time(int64_t value) {
  
  _impl_.time_ = value;
}
inline void PublicDealsV3ApiItem::set_time(int64_t value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:PublicDealsV3ApiItem.time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PublicDealsV3Api_2eproto
