// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicSpotKlineV3Api.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PublicSpotKlineV3Api_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PublicSpotKlineV3Api_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PublicSpotKlineV3Api_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PublicSpotKlineV3Api_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PublicSpotKlineV3Api_2eproto;
class PublicSpotKlineV3Api;
struct PublicSpotKlineV3ApiDefaultTypeInternal;
extern PublicSpotKlineV3ApiDefaultTypeInternal _PublicSpotKlineV3Api_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PublicSpotKlineV3Api* Arena::CreateMaybeMessage<::PublicSpotKlineV3Api>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PublicSpotKlineV3Api final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PublicSpotKlineV3Api) */ {
 public:
  inline PublicSpotKlineV3Api() : PublicSpotKlineV3Api(nullptr) {}
  ~PublicSpotKlineV3Api() override;
  explicit PROTOBUF_CONSTEXPR PublicSpotKlineV3Api(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PublicSpotKlineV3Api(const PublicSpotKlineV3Api& from);
  PublicSpotKlineV3Api(PublicSpotKlineV3Api&& from) noexcept
    : PublicSpotKlineV3Api() {
    *this = ::std::move(from);
  }

  inline PublicSpotKlineV3Api& operator=(const PublicSpotKlineV3Api& from) {
    CopyFrom(from);
    return *this;
  }
  inline PublicSpotKlineV3Api& operator=(PublicSpotKlineV3Api&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PublicSpotKlineV3Api& default_instance() {
    return *internal_default_instance();
  }
  static inline const PublicSpotKlineV3Api* internal_default_instance() {
    return reinterpret_cast<const PublicSpotKlineV3Api*>(
               &_PublicSpotKlineV3Api_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PublicSpotKlineV3Api& a, PublicSpotKlineV3Api& b) {
    a.Swap(&b);
  }
  inline void Swap(PublicSpotKlineV3Api* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PublicSpotKlineV3Api* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PublicSpotKlineV3Api* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PublicSpotKlineV3Api>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PublicSpotKlineV3Api& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PublicSpotKlineV3Api& from) {
    PublicSpotKlineV3Api::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PublicSpotKlineV3Api* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PublicSpotKlineV3Api";
  }
  protected:
  explicit PublicSpotKlineV3Api(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIntervalFieldNumber = 1,
    kOpeningPriceFieldNumber = 3,
    kClosingPriceFieldNumber = 4,
    kHighestPriceFieldNumber = 5,
    kLowestPriceFieldNumber = 6,
    kVolumeFieldNumber = 7,
    kAmountFieldNumber = 8,
    kWindowStartFieldNumber = 2,
    kWindowEndFieldNumber = 9,
  };
  // string interval = 1;
  void clear_interval();
  const std::string& interval() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_interval(ArgT0&& arg0, ArgT... args);
  std::string* mutable_interval();
  PROTOBUF_NODISCARD std::string* release_interval();
  void set_allocated_interval(std::string* interval);
  private:
  const std::string& _internal_interval() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_interval(const std::string& value);
  std::string* _internal_mutable_interval();
  public:

  // string openingPrice = 3;
  void clear_openingprice();
  const std::string& openingprice() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_openingprice(ArgT0&& arg0, ArgT... args);
  std::string* mutable_openingprice();
  PROTOBUF_NODISCARD std::string* release_openingprice();
  void set_allocated_openingprice(std::string* openingprice);
  private:
  const std::string& _internal_openingprice() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_openingprice(const std::string& value);
  std::string* _internal_mutable_openingprice();
  public:

  // string closingPrice = 4;
  void clear_closingprice();
  const std::string& closingprice() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_closingprice(ArgT0&& arg0, ArgT... args);
  std::string* mutable_closingprice();
  PROTOBUF_NODISCARD std::string* release_closingprice();
  void set_allocated_closingprice(std::string* closingprice);
  private:
  const std::string& _internal_closingprice() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_closingprice(const std::string& value);
  std::string* _internal_mutable_closingprice();
  public:

  // string highestPrice = 5;
  void clear_highestprice();
  const std::string& highestprice() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_highestprice(ArgT0&& arg0, ArgT... args);
  std::string* mutable_highestprice();
  PROTOBUF_NODISCARD std::string* release_highestprice();
  void set_allocated_highestprice(std::string* highestprice);
  private:
  const std::string& _internal_highestprice() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_highestprice(const std::string& value);
  std::string* _internal_mutable_highestprice();
  public:

  // string lowestPrice = 6;
  void clear_lowestprice();
  const std::string& lowestprice() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_lowestprice(ArgT0&& arg0, ArgT... args);
  std::string* mutable_lowestprice();
  PROTOBUF_NODISCARD std::string* release_lowestprice();
  void set_allocated_lowestprice(std::string* lowestprice);
  private:
  const std::string& _internal_lowestprice() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_lowestprice(const std::string& value);
  std::string* _internal_mutable_lowestprice();
  public:

  // string volume = 7;
  void clear_volume();
  const std::string& volume() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_volume(ArgT0&& arg0, ArgT... args);
  std::string* mutable_volume();
  PROTOBUF_NODISCARD std::string* release_volume();
  void set_allocated_volume(std::string* volume);
  private:
  const std::string& _internal_volume() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_volume(const std::string& value);
  std::string* _internal_mutable_volume();
  public:

  // string amount = 8;
  void clear_amount();
  const std::string& amount() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_amount(ArgT0&& arg0, ArgT... args);
  std::string* mutable_amount();
  PROTOBUF_NODISCARD std::string* release_amount();
  void set_allocated_amount(std::string* amount);
  private:
  const std::string& _internal_amount() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_amount(const std::string& value);
  std::string* _internal_mutable_amount();
  public:

  // int64 windowStart = 2;
  void clear_windowstart();
  int64_t windowstart() const;
  void set_windowstart(int64_t value);
  private:
  int64_t _internal_windowstart() const;
  void _internal_set_windowstart(int64_t value);
  public:

  // int64 windowEnd = 9;
  void clear_windowend();
  int64_t windowend() const;
  void set_windowend(int64_t value);
  private:
  int64_t _internal_windowend() const;
  void _internal_set_windowend(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:PublicSpotKlineV3Api)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr interval_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr openingprice_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr closingprice_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr highestprice_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lowestprice_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr volume_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr amount_;
    int64_t windowstart_;
    int64_t windowend_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PublicSpotKlineV3Api_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PublicSpotKlineV3Api

// string interval = 1;
inline void PublicSpotKlineV3Api::clear_interval() {
  _impl_.interval_.ClearToEmpty();
}
inline const std::string& PublicSpotKlineV3Api::interval() const {
  // @@protoc_insertion_point(field_get:PublicSpotKlineV3Api.interval)
  return _internal_interval();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PublicSpotKlineV3Api::set_interval(ArgT0&& arg0, ArgT... args) {
 
 _impl_.interval_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PublicSpotKlineV3Api.interval)
}
inline std::string* PublicSpotKlineV3Api::mutable_interval() {
  std::string* _s = _internal_mutable_interval();
  // @@protoc_insertion_point(field_mutable:PublicSpotKlineV3Api.interval)
  return _s;
}
inline const std::string& PublicSpotKlineV3Api::_internal_interval() const {
  return _impl_.interval_.Get();
}
inline void PublicSpotKlineV3Api::_internal_set_interval(const std::string& value) {
  
  _impl_.interval_.Set(value, GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::_internal_mutable_interval() {
  
  return _impl_.interval_.Mutable(GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::release_interval() {
  // @@protoc_insertion_point(field_release:PublicSpotKlineV3Api.interval)
  return _impl_.interval_.Release();
}
inline void PublicSpotKlineV3Api::set_allocated_interval(std::string* interval) {
  if (interval != nullptr) {
    
  } else {
    
  }
  _impl_.interval_.SetAllocated(interval, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.interval_.IsDefault()) {
    _impl_.interval_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PublicSpotKlineV3Api.interval)
}

// int64 windowStart = 2;
inline void PublicSpotKlineV3Api::clear_windowstart() {
  _impl_.windowstart_ = int64_t{0};
}
inline int64_t PublicSpotKlineV3Api::_internal_windowstart() const {
  return _impl_.windowstart_;
}
inline int64_t PublicSpotKlineV3Api::windowstart() const {
  // @@protoc_insertion_point(field_get:PublicSpotKlineV3Api.windowStart)
  return _internal_windowstart();
}
inline void PublicSpotKlineV3Api::_internal_set_windowstart(int64_t value) {
  
  _impl_.windowstart_ = value;
}
inline void PublicSpotKlineV3Api::set_windowstart(int64_t value) {
  _internal_set_windowstart(value);
  // @@protoc_insertion_point(field_set:PublicSpotKlineV3Api.windowStart)
}

// string openingPrice = 3;
inline void PublicSpotKlineV3Api::clear_openingprice() {
  _impl_.openingprice_.ClearToEmpty();
}
inline const std::string& PublicSpotKlineV3Api::openingprice() const {
  // @@protoc_insertion_point(field_get:PublicSpotKlineV3Api.openingPrice)
  return _internal_openingprice();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PublicSpotKlineV3Api::set_openingprice(ArgT0&& arg0, ArgT... args) {
 
 _impl_.openingprice_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PublicSpotKlineV3Api.openingPrice)
}
inline std::string* PublicSpotKlineV3Api::mutable_openingprice() {
  std::string* _s = _internal_mutable_openingprice();
  // @@protoc_insertion_point(field_mutable:PublicSpotKlineV3Api.openingPrice)
  return _s;
}
inline const std::string& PublicSpotKlineV3Api::_internal_openingprice() const {
  return _impl_.openingprice_.Get();
}
inline void PublicSpotKlineV3Api::_internal_set_openingprice(const std::string& value) {
  
  _impl_.openingprice_.Set(value, GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::_internal_mutable_openingprice() {
  
  return _impl_.openingprice_.Mutable(GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::release_openingprice() {
  // @@protoc_insertion_point(field_release:PublicSpotKlineV3Api.openingPrice)
  return _impl_.openingprice_.Release();
}
inline void PublicSpotKlineV3Api::set_allocated_openingprice(std::string* openingprice) {
  if (openingprice != nullptr) {
    
  } else {
    
  }
  _impl_.openingprice_.SetAllocated(openingprice, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.openingprice_.IsDefault()) {
    _impl_.openingprice_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PublicSpotKlineV3Api.openingPrice)
}

// string closingPrice = 4;
inline void PublicSpotKlineV3Api::clear_closingprice() {
  _impl_.closingprice_.ClearToEmpty();
}
inline const std::string& PublicSpotKlineV3Api::closingprice() const {
  // @@protoc_insertion_point(field_get:PublicSpotKlineV3Api.closingPrice)
  return _internal_closingprice();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PublicSpotKlineV3Api::set_closingprice(ArgT0&& arg0, ArgT... args) {
 
 _impl_.closingprice_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PublicSpotKlineV3Api.closingPrice)
}
inline std::string* PublicSpotKlineV3Api::mutable_closingprice() {
  std::string* _s = _internal_mutable_closingprice();
  // @@protoc_insertion_point(field_mutable:PublicSpotKlineV3Api.closingPrice)
  return _s;
}
inline const std::string& PublicSpotKlineV3Api::_internal_closingprice() const {
  return _impl_.closingprice_.Get();
}
inline void PublicSpotKlineV3Api::_internal_set_closingprice(const std::string& value) {
  
  _impl_.closingprice_.Set(value, GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::_internal_mutable_closingprice() {
  
  return _impl_.closingprice_.Mutable(GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::release_closingprice() {
  // @@protoc_insertion_point(field_release:PublicSpotKlineV3Api.closingPrice)
  return _impl_.closingprice_.Release();
}
inline void PublicSpotKlineV3Api::set_allocated_closingprice(std::string* closingprice) {
  if (closingprice != nullptr) {
    
  } else {
    
  }
  _impl_.closingprice_.SetAllocated(closingprice, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.closingprice_.IsDefault()) {
    _impl_.closingprice_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PublicSpotKlineV3Api.closingPrice)
}

// string highestPrice = 5;
inline void PublicSpotKlineV3Api::clear_highestprice() {
  _impl_.highestprice_.ClearToEmpty();
}
inline const std::string& PublicSpotKlineV3Api::highestprice() const {
  // @@protoc_insertion_point(field_get:PublicSpotKlineV3Api.highestPrice)
  return _internal_highestprice();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PublicSpotKlineV3Api::set_highestprice(ArgT0&& arg0, ArgT... args) {
 
 _impl_.highestprice_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PublicSpotKlineV3Api.highestPrice)
}
inline std::string* PublicSpotKlineV3Api::mutable_highestprice() {
  std::string* _s = _internal_mutable_highestprice();
  // @@protoc_insertion_point(field_mutable:PublicSpotKlineV3Api.highestPrice)
  return _s;
}
inline const std::string& PublicSpotKlineV3Api::_internal_highestprice() const {
  return _impl_.highestprice_.Get();
}
inline void PublicSpotKlineV3Api::_internal_set_highestprice(const std::string& value) {
  
  _impl_.highestprice_.Set(value, GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::_internal_mutable_highestprice() {
  
  return _impl_.highestprice_.Mutable(GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::release_highestprice() {
  // @@protoc_insertion_point(field_release:PublicSpotKlineV3Api.highestPrice)
  return _impl_.highestprice_.Release();
}
inline void PublicSpotKlineV3Api::set_allocated_highestprice(std::string* highestprice) {
  if (highestprice != nullptr) {
    
  } else {
    
  }
  _impl_.highestprice_.SetAllocated(highestprice, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.highestprice_.IsDefault()) {
    _impl_.highestprice_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PublicSpotKlineV3Api.highestPrice)
}

// string lowestPrice = 6;
inline void PublicSpotKlineV3Api::clear_lowestprice() {
  _impl_.lowestprice_.ClearToEmpty();
}
inline const std::string& PublicSpotKlineV3Api::lowestprice() const {
  // @@protoc_insertion_point(field_get:PublicSpotKlineV3Api.lowestPrice)
  return _internal_lowestprice();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PublicSpotKlineV3Api::set_lowestprice(ArgT0&& arg0, ArgT... args) {
 
 _impl_.lowestprice_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PublicSpotKlineV3Api.lowestPrice)
}
inline std::string* PublicSpotKlineV3Api::mutable_lowestprice() {
  std::string* _s = _internal_mutable_lowestprice();
  // @@protoc_insertion_point(field_mutable:PublicSpotKlineV3Api.lowestPrice)
  return _s;
}
inline const std::string& PublicSpotKlineV3Api::_internal_lowestprice() const {
  return _impl_.lowestprice_.Get();
}
inline void PublicSpotKlineV3Api::_internal_set_lowestprice(const std::string& value) {
  
  _impl_.lowestprice_.Set(value, GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::_internal_mutable_lowestprice() {
  
  return _impl_.lowestprice_.Mutable(GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::release_lowestprice() {
  // @@protoc_insertion_point(field_release:PublicSpotKlineV3Api.lowestPrice)
  return _impl_.lowestprice_.Release();
}
inline void PublicSpotKlineV3Api::set_allocated_lowestprice(std::string* lowestprice) {
  if (lowestprice != nullptr) {
    
  } else {
    
  }
  _impl_.lowestprice_.SetAllocated(lowestprice, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.lowestprice_.IsDefault()) {
    _impl_.lowestprice_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PublicSpotKlineV3Api.lowestPrice)
}

// string volume = 7;
inline void PublicSpotKlineV3Api::clear_volume() {
  _impl_.volume_.ClearToEmpty();
}
inline const std::string& PublicSpotKlineV3Api::volume() const {
  // @@protoc_insertion_point(field_get:PublicSpotKlineV3Api.volume)
  return _internal_volume();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PublicSpotKlineV3Api::set_volume(ArgT0&& arg0, ArgT... args) {
 
 _impl_.volume_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PublicSpotKlineV3Api.volume)
}
inline std::string* PublicSpotKlineV3Api::mutable_volume() {
  std::string* _s = _internal_mutable_volume();
  // @@protoc_insertion_point(field_mutable:PublicSpotKlineV3Api.volume)
  return _s;
}
inline const std::string& PublicSpotKlineV3Api::_internal_volume() const {
  return _impl_.volume_.Get();
}
inline void PublicSpotKlineV3Api::_internal_set_volume(const std::string& value) {
  
  _impl_.volume_.Set(value, GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::_internal_mutable_volume() {
  
  return _impl_.volume_.Mutable(GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::release_volume() {
  // @@protoc_insertion_point(field_release:PublicSpotKlineV3Api.volume)
  return _impl_.volume_.Release();
}
inline void PublicSpotKlineV3Api::set_allocated_volume(std::string* volume) {
  if (volume != nullptr) {
    
  } else {
    
  }
  _impl_.volume_.SetAllocated(volume, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.volume_.IsDefault()) {
    _impl_.volume_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PublicSpotKlineV3Api.volume)
}

// string amount = 8;
inline void PublicSpotKlineV3Api::clear_amount() {
  _impl_.amount_.ClearToEmpty();
}
inline const std::string& PublicSpotKlineV3Api::amount() const {
  // @@protoc_insertion_point(field_get:PublicSpotKlineV3Api.amount)
  return _internal_amount();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PublicSpotKlineV3Api::set_amount(ArgT0&& arg0, ArgT... args) {
 
 _impl_.amount_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PublicSpotKlineV3Api.amount)
}
inline std::string* PublicSpotKlineV3Api::mutable_amount() {
  std::string* _s = _internal_mutable_amount();
  // @@protoc_insertion_point(field_mutable:PublicSpotKlineV3Api.amount)
  return _s;
}
inline const std::string& PublicSpotKlineV3Api::_internal_amount() const {
  return _impl_.amount_.Get();
}
inline void PublicSpotKlineV3Api::_internal_set_amount(const std::string& value) {
  
  _impl_.amount_.Set(value, GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::_internal_mutable_amount() {
  
  return _impl_.amount_.Mutable(GetArenaForAllocation());
}
inline std::string* PublicSpotKlineV3Api::release_amount() {
  // @@protoc_insertion_point(field_release:PublicSpotKlineV3Api.amount)
  return _impl_.amount_.Release();
}
inline void PublicSpotKlineV3Api::set_allocated_amount(std::string* amount) {
  if (amount != nullptr) {
    
  } else {
    
  }
  _impl_.amount_.SetAllocated(amount, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.amount_.IsDefault()) {
    _impl_.amount_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PublicSpotKlineV3Api.amount)
}

// int64 windowEnd = 9;
inline void PublicSpotKlineV3Api::clear_windowend() {
  _impl_.windowend_ = int64_t{0};
}
inline int64_t PublicSpotKlineV3Api::_internal_windowend() const {
  return _impl_.windowend_;
}
inline int64_t PublicSpotKlineV3Api::windowend() const {
  // @@protoc_insertion_point(field_get:PublicSpotKlineV3Api.windowEnd)
  return _internal_windowend();
}
inline void PublicSpotKlineV3Api::_internal_set_windowend(int64_t value) {
  
  _impl_.windowend_ = value;
}
inline void PublicSpotKlineV3Api::set_windowend(int64_t value) {
  _internal_set_windowend(value);
  // @@protoc_insertion_point(field_set:PublicSpotKlineV3Api.windowEnd)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PublicSpotKlineV3Api_2eproto
