// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicAggreDealsV3Api.proto

#include "PublicAggreDealsV3Api.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR PublicAggreDealsV3Api::PublicAggreDealsV3Api(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.deals_)*/{}
  , /*decltype(_impl_.eventtype_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PublicAggreDealsV3ApiDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PublicAggreDealsV3ApiDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PublicAggreDealsV3ApiDefaultTypeInternal() {}
  union {
    PublicAggreDealsV3Api _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PublicAggreDealsV3ApiDefaultTypeInternal _PublicAggreDealsV3Api_default_instance_;
PROTOBUF_CONSTEXPR PublicAggreDealsV3ApiItem::PublicAggreDealsV3ApiItem(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.price_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.quantity_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.time_)*/int64_t{0}
  , /*decltype(_impl_.tradetype_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PublicAggreDealsV3ApiItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PublicAggreDealsV3ApiItemDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PublicAggreDealsV3ApiItemDefaultTypeInternal() {}
  union {
    PublicAggreDealsV3ApiItem _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PublicAggreDealsV3ApiItemDefaultTypeInternal _PublicAggreDealsV3ApiItem_default_instance_;
static ::_pb::Metadata file_level_metadata_PublicAggreDealsV3Api_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_PublicAggreDealsV3Api_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_PublicAggreDealsV3Api_2eproto = nullptr;

const uint32_t TableStruct_PublicAggreDealsV3Api_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PublicAggreDealsV3Api, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PublicAggreDealsV3Api, _impl_.deals_),
  PROTOBUF_FIELD_OFFSET(::PublicAggreDealsV3Api, _impl_.eventtype_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PublicAggreDealsV3ApiItem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PublicAggreDealsV3ApiItem, _impl_.price_),
  PROTOBUF_FIELD_OFFSET(::PublicAggreDealsV3ApiItem, _impl_.quantity_),
  PROTOBUF_FIELD_OFFSET(::PublicAggreDealsV3ApiItem, _impl_.tradetype_),
  PROTOBUF_FIELD_OFFSET(::PublicAggreDealsV3ApiItem, _impl_.time_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::PublicAggreDealsV3Api)},
  { 8, -1, -1, sizeof(::PublicAggreDealsV3ApiItem)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_PublicAggreDealsV3Api_default_instance_._instance,
  &::_PublicAggreDealsV3ApiItem_default_instance_._instance,
};

const char descriptor_table_protodef_PublicAggreDealsV3Api_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033PublicAggreDealsV3Api.proto\"U\n\025PublicA"
  "ggreDealsV3Api\022)\n\005deals\030\001 \003(\0132\032.PublicAg"
  "greDealsV3ApiItem\022\021\n\teventType\030\002 \001(\t\"]\n\031"
  "PublicAggreDealsV3ApiItem\022\r\n\005price\030\001 \001(\t"
  "\022\020\n\010quantity\030\002 \001(\t\022\021\n\ttradeType\030\003 \001(\005\022\014\n"
  "\004time\030\004 \001(\003B>\n\034com.mxc.push.common.proto"
  "bufB\032PublicAggreDealsV3ApiProtoH\001P\001b\006pro"
  "to3"
  ;
static ::_pbi::once_flag descriptor_table_PublicAggreDealsV3Api_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_PublicAggreDealsV3Api_2eproto = {
    false, false, 283, descriptor_table_protodef_PublicAggreDealsV3Api_2eproto,
    "PublicAggreDealsV3Api.proto",
    &descriptor_table_PublicAggreDealsV3Api_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_PublicAggreDealsV3Api_2eproto::offsets,
    file_level_metadata_PublicAggreDealsV3Api_2eproto, file_level_enum_descriptors_PublicAggreDealsV3Api_2eproto,
    file_level_service_descriptors_PublicAggreDealsV3Api_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_PublicAggreDealsV3Api_2eproto_getter() {
  return &descriptor_table_PublicAggreDealsV3Api_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_PublicAggreDealsV3Api_2eproto(&descriptor_table_PublicAggreDealsV3Api_2eproto);

// ===================================================================

class PublicAggreDealsV3Api::_Internal {
 public:
};

PublicAggreDealsV3Api::PublicAggreDealsV3Api(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PublicAggreDealsV3Api)
}
PublicAggreDealsV3Api::PublicAggreDealsV3Api(const PublicAggreDealsV3Api& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PublicAggreDealsV3Api* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.deals_){from._impl_.deals_}
    , decltype(_impl_.eventtype_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.eventtype_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.eventtype_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_eventtype().empty()) {
    _this->_impl_.eventtype_.Set(from._internal_eventtype(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:PublicAggreDealsV3Api)
}

inline void PublicAggreDealsV3Api::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.deals_){arena}
    , decltype(_impl_.eventtype_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.eventtype_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.eventtype_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PublicAggreDealsV3Api::~PublicAggreDealsV3Api() {
  // @@protoc_insertion_point(destructor:PublicAggreDealsV3Api)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PublicAggreDealsV3Api::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.deals_.~RepeatedPtrField();
  _impl_.eventtype_.Destroy();
}

void PublicAggreDealsV3Api::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PublicAggreDealsV3Api::Clear() {
// @@protoc_insertion_point(message_clear_start:PublicAggreDealsV3Api)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.deals_.Clear();
  _impl_.eventtype_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PublicAggreDealsV3Api::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .PublicAggreDealsV3ApiItem deals = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_deals(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // string eventType = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_eventtype();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicAggreDealsV3Api.eventType"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PublicAggreDealsV3Api::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PublicAggreDealsV3Api)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .PublicAggreDealsV3ApiItem deals = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_deals_size()); i < n; i++) {
    const auto& repfield = this->_internal_deals(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // string eventType = 2;
  if (!this->_internal_eventtype().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_eventtype().data(), static_cast<int>(this->_internal_eventtype().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicAggreDealsV3Api.eventType");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_eventtype(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PublicAggreDealsV3Api)
  return target;
}

size_t PublicAggreDealsV3Api::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PublicAggreDealsV3Api)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .PublicAggreDealsV3ApiItem deals = 1;
  total_size += 1UL * this->_internal_deals_size();
  for (const auto& msg : this->_impl_.deals_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string eventType = 2;
  if (!this->_internal_eventtype().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_eventtype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PublicAggreDealsV3Api::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PublicAggreDealsV3Api::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PublicAggreDealsV3Api::GetClassData() const { return &_class_data_; }


void PublicAggreDealsV3Api::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PublicAggreDealsV3Api*>(&to_msg);
  auto& from = static_cast<const PublicAggreDealsV3Api&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PublicAggreDealsV3Api)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.deals_.MergeFrom(from._impl_.deals_);
  if (!from._internal_eventtype().empty()) {
    _this->_internal_set_eventtype(from._internal_eventtype());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PublicAggreDealsV3Api::CopyFrom(const PublicAggreDealsV3Api& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PublicAggreDealsV3Api)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PublicAggreDealsV3Api::IsInitialized() const {
  return true;
}

void PublicAggreDealsV3Api::InternalSwap(PublicAggreDealsV3Api* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.deals_.InternalSwap(&other->_impl_.deals_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.eventtype_, lhs_arena,
      &other->_impl_.eventtype_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata PublicAggreDealsV3Api::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PublicAggreDealsV3Api_2eproto_getter, &descriptor_table_PublicAggreDealsV3Api_2eproto_once,
      file_level_metadata_PublicAggreDealsV3Api_2eproto[0]);
}

// ===================================================================

class PublicAggreDealsV3ApiItem::_Internal {
 public:
};

PublicAggreDealsV3ApiItem::PublicAggreDealsV3ApiItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PublicAggreDealsV3ApiItem)
}
PublicAggreDealsV3ApiItem::PublicAggreDealsV3ApiItem(const PublicAggreDealsV3ApiItem& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PublicAggreDealsV3ApiItem* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.price_){}
    , decltype(_impl_.quantity_){}
    , decltype(_impl_.time_){}
    , decltype(_impl_.tradetype_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.price_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.price_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_price().empty()) {
    _this->_impl_.price_.Set(from._internal_price(), 
      _this->GetArenaForAllocation());
  }
  _impl_.quantity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.quantity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_quantity().empty()) {
    _this->_impl_.quantity_.Set(from._internal_quantity(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.time_, &from._impl_.time_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.tradetype_) -
    reinterpret_cast<char*>(&_impl_.time_)) + sizeof(_impl_.tradetype_));
  // @@protoc_insertion_point(copy_constructor:PublicAggreDealsV3ApiItem)
}

inline void PublicAggreDealsV3ApiItem::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.price_){}
    , decltype(_impl_.quantity_){}
    , decltype(_impl_.time_){int64_t{0}}
    , decltype(_impl_.tradetype_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.price_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.price_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.quantity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.quantity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PublicAggreDealsV3ApiItem::~PublicAggreDealsV3ApiItem() {
  // @@protoc_insertion_point(destructor:PublicAggreDealsV3ApiItem)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PublicAggreDealsV3ApiItem::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.price_.Destroy();
  _impl_.quantity_.Destroy();
}

void PublicAggreDealsV3ApiItem::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PublicAggreDealsV3ApiItem::Clear() {
// @@protoc_insertion_point(message_clear_start:PublicAggreDealsV3ApiItem)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.price_.ClearToEmpty();
  _impl_.quantity_.ClearToEmpty();
  ::memset(&_impl_.time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.tradetype_) -
      reinterpret_cast<char*>(&_impl_.time_)) + sizeof(_impl_.tradetype_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PublicAggreDealsV3ApiItem::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string price = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_price();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicAggreDealsV3ApiItem.price"));
        } else
          goto handle_unusual;
        continue;
      // string quantity = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_quantity();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicAggreDealsV3ApiItem.quantity"));
        } else
          goto handle_unusual;
        continue;
      // int32 tradeType = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.tradetype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 time = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PublicAggreDealsV3ApiItem::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PublicAggreDealsV3ApiItem)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string price = 1;
  if (!this->_internal_price().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_price().data(), static_cast<int>(this->_internal_price().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicAggreDealsV3ApiItem.price");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_price(), target);
  }

  // string quantity = 2;
  if (!this->_internal_quantity().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_quantity().data(), static_cast<int>(this->_internal_quantity().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicAggreDealsV3ApiItem.quantity");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_quantity(), target);
  }

  // int32 tradeType = 3;
  if (this->_internal_tradetype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_tradetype(), target);
  }

  // int64 time = 4;
  if (this->_internal_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PublicAggreDealsV3ApiItem)
  return target;
}

size_t PublicAggreDealsV3ApiItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PublicAggreDealsV3ApiItem)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string price = 1;
  if (!this->_internal_price().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_price());
  }

  // string quantity = 2;
  if (!this->_internal_quantity().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_quantity());
  }

  // int64 time = 4;
  if (this->_internal_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_time());
  }

  // int32 tradeType = 3;
  if (this->_internal_tradetype() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_tradetype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PublicAggreDealsV3ApiItem::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PublicAggreDealsV3ApiItem::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PublicAggreDealsV3ApiItem::GetClassData() const { return &_class_data_; }


void PublicAggreDealsV3ApiItem::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PublicAggreDealsV3ApiItem*>(&to_msg);
  auto& from = static_cast<const PublicAggreDealsV3ApiItem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PublicAggreDealsV3ApiItem)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_price().empty()) {
    _this->_internal_set_price(from._internal_price());
  }
  if (!from._internal_quantity().empty()) {
    _this->_internal_set_quantity(from._internal_quantity());
  }
  if (from._internal_time() != 0) {
    _this->_internal_set_time(from._internal_time());
  }
  if (from._internal_tradetype() != 0) {
    _this->_internal_set_tradetype(from._internal_tradetype());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PublicAggreDealsV3ApiItem::CopyFrom(const PublicAggreDealsV3ApiItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PublicAggreDealsV3ApiItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PublicAggreDealsV3ApiItem::IsInitialized() const {
  return true;
}

void PublicAggreDealsV3ApiItem::InternalSwap(PublicAggreDealsV3ApiItem* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.price_, lhs_arena,
      &other->_impl_.price_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.quantity_, lhs_arena,
      &other->_impl_.quantity_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PublicAggreDealsV3ApiItem, _impl_.tradetype_)
      + sizeof(PublicAggreDealsV3ApiItem::_impl_.tradetype_)
      - PROTOBUF_FIELD_OFFSET(PublicAggreDealsV3ApiItem, _impl_.time_)>(
          reinterpret_cast<char*>(&_impl_.time_),
          reinterpret_cast<char*>(&other->_impl_.time_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PublicAggreDealsV3ApiItem::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PublicAggreDealsV3Api_2eproto_getter, &descriptor_table_PublicAggreDealsV3Api_2eproto_once,
      file_level_metadata_PublicAggreDealsV3Api_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PublicAggreDealsV3Api*
Arena::CreateMaybeMessage< ::PublicAggreDealsV3Api >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PublicAggreDealsV3Api >(arena);
}
template<> PROTOBUF_NOINLINE ::PublicAggreDealsV3ApiItem*
Arena::CreateMaybeMessage< ::PublicAggreDealsV3ApiItem >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PublicAggreDealsV3ApiItem >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
