// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicMiniTickerV3Api.proto

#include "PublicMiniTickerV3Api.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR PublicMiniTickerV3Api::PublicMiniTickerV3Api(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.symbol_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.price_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.rate_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.zonedrate_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.high_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.low_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.volume_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.quantity_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.lastcloserate_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.lastclosezonedrate_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.lastclosehigh_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.lastcloselow_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PublicMiniTickerV3ApiDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PublicMiniTickerV3ApiDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PublicMiniTickerV3ApiDefaultTypeInternal() {}
  union {
    PublicMiniTickerV3Api _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PublicMiniTickerV3ApiDefaultTypeInternal _PublicMiniTickerV3Api_default_instance_;
static ::_pb::Metadata file_level_metadata_PublicMiniTickerV3Api_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_PublicMiniTickerV3Api_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_PublicMiniTickerV3Api_2eproto = nullptr;

const uint32_t TableStruct_PublicMiniTickerV3Api_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PublicMiniTickerV3Api, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PublicMiniTickerV3Api, _impl_.symbol_),
  PROTOBUF_FIELD_OFFSET(::PublicMiniTickerV3Api, _impl_.price_),
  PROTOBUF_FIELD_OFFSET(::PublicMiniTickerV3Api, _impl_.rate_),
  PROTOBUF_FIELD_OFFSET(::PublicMiniTickerV3Api, _impl_.zonedrate_),
  PROTOBUF_FIELD_OFFSET(::PublicMiniTickerV3Api, _impl_.high_),
  PROTOBUF_FIELD_OFFSET(::PublicMiniTickerV3Api, _impl_.low_),
  PROTOBUF_FIELD_OFFSET(::PublicMiniTickerV3Api, _impl_.volume_),
  PROTOBUF_FIELD_OFFSET(::PublicMiniTickerV3Api, _impl_.quantity_),
  PROTOBUF_FIELD_OFFSET(::PublicMiniTickerV3Api, _impl_.lastcloserate_),
  PROTOBUF_FIELD_OFFSET(::PublicMiniTickerV3Api, _impl_.lastclosezonedrate_),
  PROTOBUF_FIELD_OFFSET(::PublicMiniTickerV3Api, _impl_.lastclosehigh_),
  PROTOBUF_FIELD_OFFSET(::PublicMiniTickerV3Api, _impl_.lastcloselow_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::PublicMiniTickerV3Api)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_PublicMiniTickerV3Api_default_instance_._instance,
};

const char descriptor_table_protodef_PublicMiniTickerV3Api_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033PublicMiniTickerV3Api.proto\"\364\001\n\025Public"
  "MiniTickerV3Api\022\016\n\006symbol\030\001 \001(\t\022\r\n\005price"
  "\030\002 \001(\t\022\014\n\004rate\030\003 \001(\t\022\021\n\tzonedRate\030\004 \001(\t\022"
  "\014\n\004high\030\005 \001(\t\022\013\n\003low\030\006 \001(\t\022\016\n\006volume\030\007 \001"
  "(\t\022\020\n\010quantity\030\010 \001(\t\022\025\n\rlastCloseRate\030\t "
  "\001(\t\022\032\n\022lastCloseZonedRate\030\n \001(\t\022\025\n\rlastC"
  "loseHigh\030\013 \001(\t\022\024\n\014lastCloseLow\030\014 \001(\tB>\n\034"
  "com.mxc.push.common.protobufB\032PublicMini"
  "TickerV3ApiProtoH\001P\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_PublicMiniTickerV3Api_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_PublicMiniTickerV3Api_2eproto = {
    false, false, 348, descriptor_table_protodef_PublicMiniTickerV3Api_2eproto,
    "PublicMiniTickerV3Api.proto",
    &descriptor_table_PublicMiniTickerV3Api_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_PublicMiniTickerV3Api_2eproto::offsets,
    file_level_metadata_PublicMiniTickerV3Api_2eproto, file_level_enum_descriptors_PublicMiniTickerV3Api_2eproto,
    file_level_service_descriptors_PublicMiniTickerV3Api_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_PublicMiniTickerV3Api_2eproto_getter() {
  return &descriptor_table_PublicMiniTickerV3Api_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_PublicMiniTickerV3Api_2eproto(&descriptor_table_PublicMiniTickerV3Api_2eproto);

// ===================================================================

class PublicMiniTickerV3Api::_Internal {
 public:
};

PublicMiniTickerV3Api::PublicMiniTickerV3Api(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PublicMiniTickerV3Api)
}
PublicMiniTickerV3Api::PublicMiniTickerV3Api(const PublicMiniTickerV3Api& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PublicMiniTickerV3Api* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.symbol_){}
    , decltype(_impl_.price_){}
    , decltype(_impl_.rate_){}
    , decltype(_impl_.zonedrate_){}
    , decltype(_impl_.high_){}
    , decltype(_impl_.low_){}
    , decltype(_impl_.volume_){}
    , decltype(_impl_.quantity_){}
    , decltype(_impl_.lastcloserate_){}
    , decltype(_impl_.lastclosezonedrate_){}
    , decltype(_impl_.lastclosehigh_){}
    , decltype(_impl_.lastcloselow_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.symbol_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.symbol_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_symbol().empty()) {
    _this->_impl_.symbol_.Set(from._internal_symbol(), 
      _this->GetArenaForAllocation());
  }
  _impl_.price_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.price_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_price().empty()) {
    _this->_impl_.price_.Set(from._internal_price(), 
      _this->GetArenaForAllocation());
  }
  _impl_.rate_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rate_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_rate().empty()) {
    _this->_impl_.rate_.Set(from._internal_rate(), 
      _this->GetArenaForAllocation());
  }
  _impl_.zonedrate_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.zonedrate_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_zonedrate().empty()) {
    _this->_impl_.zonedrate_.Set(from._internal_zonedrate(), 
      _this->GetArenaForAllocation());
  }
  _impl_.high_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.high_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_high().empty()) {
    _this->_impl_.high_.Set(from._internal_high(), 
      _this->GetArenaForAllocation());
  }
  _impl_.low_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.low_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_low().empty()) {
    _this->_impl_.low_.Set(from._internal_low(), 
      _this->GetArenaForAllocation());
  }
  _impl_.volume_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.volume_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_volume().empty()) {
    _this->_impl_.volume_.Set(from._internal_volume(), 
      _this->GetArenaForAllocation());
  }
  _impl_.quantity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.quantity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_quantity().empty()) {
    _this->_impl_.quantity_.Set(from._internal_quantity(), 
      _this->GetArenaForAllocation());
  }
  _impl_.lastcloserate_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lastcloserate_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_lastcloserate().empty()) {
    _this->_impl_.lastcloserate_.Set(from._internal_lastcloserate(), 
      _this->GetArenaForAllocation());
  }
  _impl_.lastclosezonedrate_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lastclosezonedrate_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_lastclosezonedrate().empty()) {
    _this->_impl_.lastclosezonedrate_.Set(from._internal_lastclosezonedrate(), 
      _this->GetArenaForAllocation());
  }
  _impl_.lastclosehigh_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lastclosehigh_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_lastclosehigh().empty()) {
    _this->_impl_.lastclosehigh_.Set(from._internal_lastclosehigh(), 
      _this->GetArenaForAllocation());
  }
  _impl_.lastcloselow_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lastcloselow_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_lastcloselow().empty()) {
    _this->_impl_.lastcloselow_.Set(from._internal_lastcloselow(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:PublicMiniTickerV3Api)
}

inline void PublicMiniTickerV3Api::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.symbol_){}
    , decltype(_impl_.price_){}
    , decltype(_impl_.rate_){}
    , decltype(_impl_.zonedrate_){}
    , decltype(_impl_.high_){}
    , decltype(_impl_.low_){}
    , decltype(_impl_.volume_){}
    , decltype(_impl_.quantity_){}
    , decltype(_impl_.lastcloserate_){}
    , decltype(_impl_.lastclosezonedrate_){}
    , decltype(_impl_.lastclosehigh_){}
    , decltype(_impl_.lastcloselow_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.symbol_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.symbol_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.price_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.price_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.rate_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rate_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.zonedrate_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.zonedrate_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.high_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.high_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.low_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.low_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.volume_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.volume_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.quantity_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.quantity_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.lastcloserate_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lastcloserate_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.lastclosezonedrate_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lastclosezonedrate_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.lastclosehigh_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lastclosehigh_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.lastcloselow_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lastcloselow_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PublicMiniTickerV3Api::~PublicMiniTickerV3Api() {
  // @@protoc_insertion_point(destructor:PublicMiniTickerV3Api)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PublicMiniTickerV3Api::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.symbol_.Destroy();
  _impl_.price_.Destroy();
  _impl_.rate_.Destroy();
  _impl_.zonedrate_.Destroy();
  _impl_.high_.Destroy();
  _impl_.low_.Destroy();
  _impl_.volume_.Destroy();
  _impl_.quantity_.Destroy();
  _impl_.lastcloserate_.Destroy();
  _impl_.lastclosezonedrate_.Destroy();
  _impl_.lastclosehigh_.Destroy();
  _impl_.lastcloselow_.Destroy();
}

void PublicMiniTickerV3Api::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PublicMiniTickerV3Api::Clear() {
// @@protoc_insertion_point(message_clear_start:PublicMiniTickerV3Api)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.symbol_.ClearToEmpty();
  _impl_.price_.ClearToEmpty();
  _impl_.rate_.ClearToEmpty();
  _impl_.zonedrate_.ClearToEmpty();
  _impl_.high_.ClearToEmpty();
  _impl_.low_.ClearToEmpty();
  _impl_.volume_.ClearToEmpty();
  _impl_.quantity_.ClearToEmpty();
  _impl_.lastcloserate_.ClearToEmpty();
  _impl_.lastclosezonedrate_.ClearToEmpty();
  _impl_.lastclosehigh_.ClearToEmpty();
  _impl_.lastcloselow_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PublicMiniTickerV3Api::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string symbol = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_symbol();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicMiniTickerV3Api.symbol"));
        } else
          goto handle_unusual;
        continue;
      // string price = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_price();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicMiniTickerV3Api.price"));
        } else
          goto handle_unusual;
        continue;
      // string rate = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_rate();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicMiniTickerV3Api.rate"));
        } else
          goto handle_unusual;
        continue;
      // string zonedRate = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_zonedrate();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicMiniTickerV3Api.zonedRate"));
        } else
          goto handle_unusual;
        continue;
      // string high = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_high();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicMiniTickerV3Api.high"));
        } else
          goto handle_unusual;
        continue;
      // string low = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_low();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicMiniTickerV3Api.low"));
        } else
          goto handle_unusual;
        continue;
      // string volume = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_volume();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicMiniTickerV3Api.volume"));
        } else
          goto handle_unusual;
        continue;
      // string quantity = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_quantity();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicMiniTickerV3Api.quantity"));
        } else
          goto handle_unusual;
        continue;
      // string lastCloseRate = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_lastcloserate();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicMiniTickerV3Api.lastCloseRate"));
        } else
          goto handle_unusual;
        continue;
      // string lastCloseZonedRate = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_lastclosezonedrate();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicMiniTickerV3Api.lastCloseZonedRate"));
        } else
          goto handle_unusual;
        continue;
      // string lastCloseHigh = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_lastclosehigh();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicMiniTickerV3Api.lastCloseHigh"));
        } else
          goto handle_unusual;
        continue;
      // string lastCloseLow = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          auto str = _internal_mutable_lastcloselow();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PublicMiniTickerV3Api.lastCloseLow"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PublicMiniTickerV3Api::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PublicMiniTickerV3Api)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string symbol = 1;
  if (!this->_internal_symbol().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_symbol().data(), static_cast<int>(this->_internal_symbol().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicMiniTickerV3Api.symbol");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_symbol(), target);
  }

  // string price = 2;
  if (!this->_internal_price().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_price().data(), static_cast<int>(this->_internal_price().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicMiniTickerV3Api.price");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_price(), target);
  }

  // string rate = 3;
  if (!this->_internal_rate().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_rate().data(), static_cast<int>(this->_internal_rate().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicMiniTickerV3Api.rate");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_rate(), target);
  }

  // string zonedRate = 4;
  if (!this->_internal_zonedrate().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_zonedrate().data(), static_cast<int>(this->_internal_zonedrate().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicMiniTickerV3Api.zonedRate");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_zonedrate(), target);
  }

  // string high = 5;
  if (!this->_internal_high().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_high().data(), static_cast<int>(this->_internal_high().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicMiniTickerV3Api.high");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_high(), target);
  }

  // string low = 6;
  if (!this->_internal_low().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_low().data(), static_cast<int>(this->_internal_low().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicMiniTickerV3Api.low");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_low(), target);
  }

  // string volume = 7;
  if (!this->_internal_volume().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_volume().data(), static_cast<int>(this->_internal_volume().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicMiniTickerV3Api.volume");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_volume(), target);
  }

  // string quantity = 8;
  if (!this->_internal_quantity().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_quantity().data(), static_cast<int>(this->_internal_quantity().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicMiniTickerV3Api.quantity");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_quantity(), target);
  }

  // string lastCloseRate = 9;
  if (!this->_internal_lastcloserate().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_lastcloserate().data(), static_cast<int>(this->_internal_lastcloserate().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicMiniTickerV3Api.lastCloseRate");
    target = stream->WriteStringMaybeAliased(
        9, this->_internal_lastcloserate(), target);
  }

  // string lastCloseZonedRate = 10;
  if (!this->_internal_lastclosezonedrate().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_lastclosezonedrate().data(), static_cast<int>(this->_internal_lastclosezonedrate().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicMiniTickerV3Api.lastCloseZonedRate");
    target = stream->WriteStringMaybeAliased(
        10, this->_internal_lastclosezonedrate(), target);
  }

  // string lastCloseHigh = 11;
  if (!this->_internal_lastclosehigh().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_lastclosehigh().data(), static_cast<int>(this->_internal_lastclosehigh().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicMiniTickerV3Api.lastCloseHigh");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_lastclosehigh(), target);
  }

  // string lastCloseLow = 12;
  if (!this->_internal_lastcloselow().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_lastcloselow().data(), static_cast<int>(this->_internal_lastcloselow().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicMiniTickerV3Api.lastCloseLow");
    target = stream->WriteStringMaybeAliased(
        12, this->_internal_lastcloselow(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PublicMiniTickerV3Api)
  return target;
}

size_t PublicMiniTickerV3Api::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PublicMiniTickerV3Api)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string symbol = 1;
  if (!this->_internal_symbol().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_symbol());
  }

  // string price = 2;
  if (!this->_internal_price().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_price());
  }

  // string rate = 3;
  if (!this->_internal_rate().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_rate());
  }

  // string zonedRate = 4;
  if (!this->_internal_zonedrate().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_zonedrate());
  }

  // string high = 5;
  if (!this->_internal_high().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_high());
  }

  // string low = 6;
  if (!this->_internal_low().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_low());
  }

  // string volume = 7;
  if (!this->_internal_volume().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_volume());
  }

  // string quantity = 8;
  if (!this->_internal_quantity().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_quantity());
  }

  // string lastCloseRate = 9;
  if (!this->_internal_lastcloserate().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_lastcloserate());
  }

  // string lastCloseZonedRate = 10;
  if (!this->_internal_lastclosezonedrate().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_lastclosezonedrate());
  }

  // string lastCloseHigh = 11;
  if (!this->_internal_lastclosehigh().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_lastclosehigh());
  }

  // string lastCloseLow = 12;
  if (!this->_internal_lastcloselow().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_lastcloselow());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PublicMiniTickerV3Api::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PublicMiniTickerV3Api::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PublicMiniTickerV3Api::GetClassData() const { return &_class_data_; }


void PublicMiniTickerV3Api::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PublicMiniTickerV3Api*>(&to_msg);
  auto& from = static_cast<const PublicMiniTickerV3Api&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PublicMiniTickerV3Api)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_symbol().empty()) {
    _this->_internal_set_symbol(from._internal_symbol());
  }
  if (!from._internal_price().empty()) {
    _this->_internal_set_price(from._internal_price());
  }
  if (!from._internal_rate().empty()) {
    _this->_internal_set_rate(from._internal_rate());
  }
  if (!from._internal_zonedrate().empty()) {
    _this->_internal_set_zonedrate(from._internal_zonedrate());
  }
  if (!from._internal_high().empty()) {
    _this->_internal_set_high(from._internal_high());
  }
  if (!from._internal_low().empty()) {
    _this->_internal_set_low(from._internal_low());
  }
  if (!from._internal_volume().empty()) {
    _this->_internal_set_volume(from._internal_volume());
  }
  if (!from._internal_quantity().empty()) {
    _this->_internal_set_quantity(from._internal_quantity());
  }
  if (!from._internal_lastcloserate().empty()) {
    _this->_internal_set_lastcloserate(from._internal_lastcloserate());
  }
  if (!from._internal_lastclosezonedrate().empty()) {
    _this->_internal_set_lastclosezonedrate(from._internal_lastclosezonedrate());
  }
  if (!from._internal_lastclosehigh().empty()) {
    _this->_internal_set_lastclosehigh(from._internal_lastclosehigh());
  }
  if (!from._internal_lastcloselow().empty()) {
    _this->_internal_set_lastcloselow(from._internal_lastcloselow());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PublicMiniTickerV3Api::CopyFrom(const PublicMiniTickerV3Api& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PublicMiniTickerV3Api)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PublicMiniTickerV3Api::IsInitialized() const {
  return true;
}

void PublicMiniTickerV3Api::InternalSwap(PublicMiniTickerV3Api* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.symbol_, lhs_arena,
      &other->_impl_.symbol_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.price_, lhs_arena,
      &other->_impl_.price_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.rate_, lhs_arena,
      &other->_impl_.rate_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.zonedrate_, lhs_arena,
      &other->_impl_.zonedrate_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.high_, lhs_arena,
      &other->_impl_.high_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.low_, lhs_arena,
      &other->_impl_.low_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.volume_, lhs_arena,
      &other->_impl_.volume_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.quantity_, lhs_arena,
      &other->_impl_.quantity_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.lastcloserate_, lhs_arena,
      &other->_impl_.lastcloserate_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.lastclosezonedrate_, lhs_arena,
      &other->_impl_.lastclosezonedrate_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.lastclosehigh_, lhs_arena,
      &other->_impl_.lastclosehigh_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.lastcloselow_, lhs_arena,
      &other->_impl_.lastcloselow_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata PublicMiniTickerV3Api::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PublicMiniTickerV3Api_2eproto_getter, &descriptor_table_PublicMiniTickerV3Api_2eproto_once,
      file_level_metadata_PublicMiniTickerV3Api_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PublicMiniTickerV3Api*
Arena::CreateMaybeMessage< ::PublicMiniTickerV3Api >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PublicMiniTickerV3Api >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
