// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushDataV3ApiWrapper.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PushDataV3ApiWrapper_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PushDataV3ApiWrapper_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "PublicDealsV3Api.pb.h"
#include "PublicIncreaseDepthsV3Api.pb.h"
#include "PublicLimitDepthsV3Api.pb.h"
#include "PrivateOrdersV3Api.pb.h"
#include "PublicBookTickerV3Api.pb.h"
#include "PrivateDealsV3Api.pb.h"
#include "PrivateAccountV3Api.pb.h"
#include "PublicSpotKlineV3Api.pb.h"
#include "PublicMiniTickerV3Api.pb.h"
#include "PublicMiniTickersV3Api.pb.h"
#include "PublicBookTickerBatchV3Api.pb.h"
#include "PublicIncreaseDepthsBatchV3Api.pb.h"
#include "PublicAggreDepthsV3Api.pb.h"
#include "PublicAggreDealsV3Api.pb.h"
#include "PublicAggreBookTickerV3Api.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PushDataV3ApiWrapper_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PushDataV3ApiWrapper_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PushDataV3ApiWrapper_2eproto;
class PushDataV3ApiWrapper;
struct PushDataV3ApiWrapperDefaultTypeInternal;
extern PushDataV3ApiWrapperDefaultTypeInternal _PushDataV3ApiWrapper_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PushDataV3ApiWrapper* Arena::CreateMaybeMessage<::PushDataV3ApiWrapper>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PushDataV3ApiWrapper final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PushDataV3ApiWrapper) */ {
 public:
  inline PushDataV3ApiWrapper() : PushDataV3ApiWrapper(nullptr) {}
  ~PushDataV3ApiWrapper() override;
  explicit PROTOBUF_CONSTEXPR PushDataV3ApiWrapper(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PushDataV3ApiWrapper(const PushDataV3ApiWrapper& from);
  PushDataV3ApiWrapper(PushDataV3ApiWrapper&& from) noexcept
    : PushDataV3ApiWrapper() {
    *this = ::std::move(from);
  }

  inline PushDataV3ApiWrapper& operator=(const PushDataV3ApiWrapper& from) {
    CopyFrom(from);
    return *this;
  }
  inline PushDataV3ApiWrapper& operator=(PushDataV3ApiWrapper&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PushDataV3ApiWrapper& default_instance() {
    return *internal_default_instance();
  }
  enum BodyCase {
    kPublicDeals = 301,
    kPublicIncreaseDepths = 302,
    kPublicLimitDepths = 303,
    kPrivateOrders = 304,
    kPublicBookTicker = 305,
    kPrivateDeals = 306,
    kPrivateAccount = 307,
    kPublicSpotKline = 308,
    kPublicMiniTicker = 309,
    kPublicMiniTickers = 310,
    kPublicBookTickerBatch = 311,
    kPublicIncreaseDepthsBatch = 312,
    kPublicAggreDepths = 313,
    kPublicAggreDeals = 314,
    kPublicAggreBookTicker = 315,
    BODY_NOT_SET = 0,
  };

  static inline const PushDataV3ApiWrapper* internal_default_instance() {
    return reinterpret_cast<const PushDataV3ApiWrapper*>(
               &_PushDataV3ApiWrapper_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PushDataV3ApiWrapper& a, PushDataV3ApiWrapper& b) {
    a.Swap(&b);
  }
  inline void Swap(PushDataV3ApiWrapper* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PushDataV3ApiWrapper* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PushDataV3ApiWrapper* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PushDataV3ApiWrapper>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PushDataV3ApiWrapper& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PushDataV3ApiWrapper& from) {
    PushDataV3ApiWrapper::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PushDataV3ApiWrapper* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PushDataV3ApiWrapper";
  }
  protected:
  explicit PushDataV3ApiWrapper(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChannelFieldNumber = 1,
    kSymbolFieldNumber = 3,
    kSymbolIdFieldNumber = 4,
    kCreateTimeFieldNumber = 5,
    kSendTimeFieldNumber = 6,
    kPublicDealsFieldNumber = 301,
    kPublicIncreaseDepthsFieldNumber = 302,
    kPublicLimitDepthsFieldNumber = 303,
    kPrivateOrdersFieldNumber = 304,
    kPublicBookTickerFieldNumber = 305,
    kPrivateDealsFieldNumber = 306,
    kPrivateAccountFieldNumber = 307,
    kPublicSpotKlineFieldNumber = 308,
    kPublicMiniTickerFieldNumber = 309,
    kPublicMiniTickersFieldNumber = 310,
    kPublicBookTickerBatchFieldNumber = 311,
    kPublicIncreaseDepthsBatchFieldNumber = 312,
    kPublicAggreDepthsFieldNumber = 313,
    kPublicAggreDealsFieldNumber = 314,
    kPublicAggreBookTickerFieldNumber = 315,
  };
  // string channel = 1;
  void clear_channel();
  const std::string& channel() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_channel(ArgT0&& arg0, ArgT... args);
  std::string* mutable_channel();
  PROTOBUF_NODISCARD std::string* release_channel();
  void set_allocated_channel(std::string* channel);
  private:
  const std::string& _internal_channel() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_channel(const std::string& value);
  std::string* _internal_mutable_channel();
  public:

  // optional string symbol = 3;
  bool has_symbol() const;
  private:
  bool _internal_has_symbol() const;
  public:
  void clear_symbol();
  const std::string& symbol() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_symbol(ArgT0&& arg0, ArgT... args);
  std::string* mutable_symbol();
  PROTOBUF_NODISCARD std::string* release_symbol();
  void set_allocated_symbol(std::string* symbol);
  private:
  const std::string& _internal_symbol() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_symbol(const std::string& value);
  std::string* _internal_mutable_symbol();
  public:

  // optional string symbolId = 4;
  bool has_symbolid() const;
  private:
  bool _internal_has_symbolid() const;
  public:
  void clear_symbolid();
  const std::string& symbolid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_symbolid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_symbolid();
  PROTOBUF_NODISCARD std::string* release_symbolid();
  void set_allocated_symbolid(std::string* symbolid);
  private:
  const std::string& _internal_symbolid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_symbolid(const std::string& value);
  std::string* _internal_mutable_symbolid();
  public:

  // optional int64 createTime = 5;
  bool has_createtime() const;
  private:
  bool _internal_has_createtime() const;
  public:
  void clear_createtime();
  int64_t createtime() const;
  void set_createtime(int64_t value);
  private:
  int64_t _internal_createtime() const;
  void _internal_set_createtime(int64_t value);
  public:

  // optional int64 sendTime = 6;
  bool has_sendtime() const;
  private:
  bool _internal_has_sendtime() const;
  public:
  void clear_sendtime();
  int64_t sendtime() const;
  void set_sendtime(int64_t value);
  private:
  int64_t _internal_sendtime() const;
  void _internal_set_sendtime(int64_t value);
  public:

  // .PublicDealsV3Api publicDeals = 301;
  bool has_publicdeals() const;
  private:
  bool _internal_has_publicdeals() const;
  public:
  void clear_publicdeals();
  const ::PublicDealsV3Api& publicdeals() const;
  PROTOBUF_NODISCARD ::PublicDealsV3Api* release_publicdeals();
  ::PublicDealsV3Api* mutable_publicdeals();
  void set_allocated_publicdeals(::PublicDealsV3Api* publicdeals);
  private:
  const ::PublicDealsV3Api& _internal_publicdeals() const;
  ::PublicDealsV3Api* _internal_mutable_publicdeals();
  public:
  void unsafe_arena_set_allocated_publicdeals(
      ::PublicDealsV3Api* publicdeals);
  ::PublicDealsV3Api* unsafe_arena_release_publicdeals();

  // .PublicIncreaseDepthsV3Api publicIncreaseDepths = 302;
  bool has_publicincreasedepths() const;
  private:
  bool _internal_has_publicincreasedepths() const;
  public:
  void clear_publicincreasedepths();
  const ::PublicIncreaseDepthsV3Api& publicincreasedepths() const;
  PROTOBUF_NODISCARD ::PublicIncreaseDepthsV3Api* release_publicincreasedepths();
  ::PublicIncreaseDepthsV3Api* mutable_publicincreasedepths();
  void set_allocated_publicincreasedepths(::PublicIncreaseDepthsV3Api* publicincreasedepths);
  private:
  const ::PublicIncreaseDepthsV3Api& _internal_publicincreasedepths() const;
  ::PublicIncreaseDepthsV3Api* _internal_mutable_publicincreasedepths();
  public:
  void unsafe_arena_set_allocated_publicincreasedepths(
      ::PublicIncreaseDepthsV3Api* publicincreasedepths);
  ::PublicIncreaseDepthsV3Api* unsafe_arena_release_publicincreasedepths();

  // .PublicLimitDepthsV3Api publicLimitDepths = 303;
  bool has_publiclimitdepths() const;
  private:
  bool _internal_has_publiclimitdepths() const;
  public:
  void clear_publiclimitdepths();
  const ::PublicLimitDepthsV3Api& publiclimitdepths() const;
  PROTOBUF_NODISCARD ::PublicLimitDepthsV3Api* release_publiclimitdepths();
  ::PublicLimitDepthsV3Api* mutable_publiclimitdepths();
  void set_allocated_publiclimitdepths(::PublicLimitDepthsV3Api* publiclimitdepths);
  private:
  const ::PublicLimitDepthsV3Api& _internal_publiclimitdepths() const;
  ::PublicLimitDepthsV3Api* _internal_mutable_publiclimitdepths();
  public:
  void unsafe_arena_set_allocated_publiclimitdepths(
      ::PublicLimitDepthsV3Api* publiclimitdepths);
  ::PublicLimitDepthsV3Api* unsafe_arena_release_publiclimitdepths();

  // .PrivateOrdersV3Api privateOrders = 304;
  bool has_privateorders() const;
  private:
  bool _internal_has_privateorders() const;
  public:
  void clear_privateorders();
  const ::PrivateOrdersV3Api& privateorders() const;
  PROTOBUF_NODISCARD ::PrivateOrdersV3Api* release_privateorders();
  ::PrivateOrdersV3Api* mutable_privateorders();
  void set_allocated_privateorders(::PrivateOrdersV3Api* privateorders);
  private:
  const ::PrivateOrdersV3Api& _internal_privateorders() const;
  ::PrivateOrdersV3Api* _internal_mutable_privateorders();
  public:
  void unsafe_arena_set_allocated_privateorders(
      ::PrivateOrdersV3Api* privateorders);
  ::PrivateOrdersV3Api* unsafe_arena_release_privateorders();

  // .PublicBookTickerV3Api publicBookTicker = 305;
  bool has_publicbookticker() const;
  private:
  bool _internal_has_publicbookticker() const;
  public:
  void clear_publicbookticker();
  const ::PublicBookTickerV3Api& publicbookticker() const;
  PROTOBUF_NODISCARD ::PublicBookTickerV3Api* release_publicbookticker();
  ::PublicBookTickerV3Api* mutable_publicbookticker();
  void set_allocated_publicbookticker(::PublicBookTickerV3Api* publicbookticker);
  private:
  const ::PublicBookTickerV3Api& _internal_publicbookticker() const;
  ::PublicBookTickerV3Api* _internal_mutable_publicbookticker();
  public:
  void unsafe_arena_set_allocated_publicbookticker(
      ::PublicBookTickerV3Api* publicbookticker);
  ::PublicBookTickerV3Api* unsafe_arena_release_publicbookticker();

  // .PrivateDealsV3Api privateDeals = 306;
  bool has_privatedeals() const;
  private:
  bool _internal_has_privatedeals() const;
  public:
  void clear_privatedeals();
  const ::PrivateDealsV3Api& privatedeals() const;
  PROTOBUF_NODISCARD ::PrivateDealsV3Api* release_privatedeals();
  ::PrivateDealsV3Api* mutable_privatedeals();
  void set_allocated_privatedeals(::PrivateDealsV3Api* privatedeals);
  private:
  const ::PrivateDealsV3Api& _internal_privatedeals() const;
  ::PrivateDealsV3Api* _internal_mutable_privatedeals();
  public:
  void unsafe_arena_set_allocated_privatedeals(
      ::PrivateDealsV3Api* privatedeals);
  ::PrivateDealsV3Api* unsafe_arena_release_privatedeals();

  // .PrivateAccountV3Api privateAccount = 307;
  bool has_privateaccount() const;
  private:
  bool _internal_has_privateaccount() const;
  public:
  void clear_privateaccount();
  const ::PrivateAccountV3Api& privateaccount() const;
  PROTOBUF_NODISCARD ::PrivateAccountV3Api* release_privateaccount();
  ::PrivateAccountV3Api* mutable_privateaccount();
  void set_allocated_privateaccount(::PrivateAccountV3Api* privateaccount);
  private:
  const ::PrivateAccountV3Api& _internal_privateaccount() const;
  ::PrivateAccountV3Api* _internal_mutable_privateaccount();
  public:
  void unsafe_arena_set_allocated_privateaccount(
      ::PrivateAccountV3Api* privateaccount);
  ::PrivateAccountV3Api* unsafe_arena_release_privateaccount();

  // .PublicSpotKlineV3Api publicSpotKline = 308;
  bool has_publicspotkline() const;
  private:
  bool _internal_has_publicspotkline() const;
  public:
  void clear_publicspotkline();
  const ::PublicSpotKlineV3Api& publicspotkline() const;
  PROTOBUF_NODISCARD ::PublicSpotKlineV3Api* release_publicspotkline();
  ::PublicSpotKlineV3Api* mutable_publicspotkline();
  void set_allocated_publicspotkline(::PublicSpotKlineV3Api* publicspotkline);
  private:
  const ::PublicSpotKlineV3Api& _internal_publicspotkline() const;
  ::PublicSpotKlineV3Api* _internal_mutable_publicspotkline();
  public:
  void unsafe_arena_set_allocated_publicspotkline(
      ::PublicSpotKlineV3Api* publicspotkline);
  ::PublicSpotKlineV3Api* unsafe_arena_release_publicspotkline();

  // .PublicMiniTickerV3Api publicMiniTicker = 309;
  bool has_publicminiticker() const;
  private:
  bool _internal_has_publicminiticker() const;
  public:
  void clear_publicminiticker();
  const ::PublicMiniTickerV3Api& publicminiticker() const;
  PROTOBUF_NODISCARD ::PublicMiniTickerV3Api* release_publicminiticker();
  ::PublicMiniTickerV3Api* mutable_publicminiticker();
  void set_allocated_publicminiticker(::PublicMiniTickerV3Api* publicminiticker);
  private:
  const ::PublicMiniTickerV3Api& _internal_publicminiticker() const;
  ::PublicMiniTickerV3Api* _internal_mutable_publicminiticker();
  public:
  void unsafe_arena_set_allocated_publicminiticker(
      ::PublicMiniTickerV3Api* publicminiticker);
  ::PublicMiniTickerV3Api* unsafe_arena_release_publicminiticker();

  // .PublicMiniTickersV3Api publicMiniTickers = 310;
  bool has_publicminitickers() const;
  private:
  bool _internal_has_publicminitickers() const;
  public:
  void clear_publicminitickers();
  const ::PublicMiniTickersV3Api& publicminitickers() const;
  PROTOBUF_NODISCARD ::PublicMiniTickersV3Api* release_publicminitickers();
  ::PublicMiniTickersV3Api* mutable_publicminitickers();
  void set_allocated_publicminitickers(::PublicMiniTickersV3Api* publicminitickers);
  private:
  const ::PublicMiniTickersV3Api& _internal_publicminitickers() const;
  ::PublicMiniTickersV3Api* _internal_mutable_publicminitickers();
  public:
  void unsafe_arena_set_allocated_publicminitickers(
      ::PublicMiniTickersV3Api* publicminitickers);
  ::PublicMiniTickersV3Api* unsafe_arena_release_publicminitickers();

  // .PublicBookTickerBatchV3Api publicBookTickerBatch = 311;
  bool has_publicbooktickerbatch() const;
  private:
  bool _internal_has_publicbooktickerbatch() const;
  public:
  void clear_publicbooktickerbatch();
  const ::PublicBookTickerBatchV3Api& publicbooktickerbatch() const;
  PROTOBUF_NODISCARD ::PublicBookTickerBatchV3Api* release_publicbooktickerbatch();
  ::PublicBookTickerBatchV3Api* mutable_publicbooktickerbatch();
  void set_allocated_publicbooktickerbatch(::PublicBookTickerBatchV3Api* publicbooktickerbatch);
  private:
  const ::PublicBookTickerBatchV3Api& _internal_publicbooktickerbatch() const;
  ::PublicBookTickerBatchV3Api* _internal_mutable_publicbooktickerbatch();
  public:
  void unsafe_arena_set_allocated_publicbooktickerbatch(
      ::PublicBookTickerBatchV3Api* publicbooktickerbatch);
  ::PublicBookTickerBatchV3Api* unsafe_arena_release_publicbooktickerbatch();

  // .PublicIncreaseDepthsBatchV3Api publicIncreaseDepthsBatch = 312;
  bool has_publicincreasedepthsbatch() const;
  private:
  bool _internal_has_publicincreasedepthsbatch() const;
  public:
  void clear_publicincreasedepthsbatch();
  const ::PublicIncreaseDepthsBatchV3Api& publicincreasedepthsbatch() const;
  PROTOBUF_NODISCARD ::PublicIncreaseDepthsBatchV3Api* release_publicincreasedepthsbatch();
  ::PublicIncreaseDepthsBatchV3Api* mutable_publicincreasedepthsbatch();
  void set_allocated_publicincreasedepthsbatch(::PublicIncreaseDepthsBatchV3Api* publicincreasedepthsbatch);
  private:
  const ::PublicIncreaseDepthsBatchV3Api& _internal_publicincreasedepthsbatch() const;
  ::PublicIncreaseDepthsBatchV3Api* _internal_mutable_publicincreasedepthsbatch();
  public:
  void unsafe_arena_set_allocated_publicincreasedepthsbatch(
      ::PublicIncreaseDepthsBatchV3Api* publicincreasedepthsbatch);
  ::PublicIncreaseDepthsBatchV3Api* unsafe_arena_release_publicincreasedepthsbatch();

  // .PublicAggreDepthsV3Api publicAggreDepths = 313;
  bool has_publicaggredepths() const;
  private:
  bool _internal_has_publicaggredepths() const;
  public:
  void clear_publicaggredepths();
  const ::PublicAggreDepthsV3Api& publicaggredepths() const;
  PROTOBUF_NODISCARD ::PublicAggreDepthsV3Api* release_publicaggredepths();
  ::PublicAggreDepthsV3Api* mutable_publicaggredepths();
  void set_allocated_publicaggredepths(::PublicAggreDepthsV3Api* publicaggredepths);
  private:
  const ::PublicAggreDepthsV3Api& _internal_publicaggredepths() const;
  ::PublicAggreDepthsV3Api* _internal_mutable_publicaggredepths();
  public:
  void unsafe_arena_set_allocated_publicaggredepths(
      ::PublicAggreDepthsV3Api* publicaggredepths);
  ::PublicAggreDepthsV3Api* unsafe_arena_release_publicaggredepths();

  // .PublicAggreDealsV3Api publicAggreDeals = 314;
  bool has_publicaggredeals() const;
  private:
  bool _internal_has_publicaggredeals() const;
  public:
  void clear_publicaggredeals();
  const ::PublicAggreDealsV3Api& publicaggredeals() const;
  PROTOBUF_NODISCARD ::PublicAggreDealsV3Api* release_publicaggredeals();
  ::PublicAggreDealsV3Api* mutable_publicaggredeals();
  void set_allocated_publicaggredeals(::PublicAggreDealsV3Api* publicaggredeals);
  private:
  const ::PublicAggreDealsV3Api& _internal_publicaggredeals() const;
  ::PublicAggreDealsV3Api* _internal_mutable_publicaggredeals();
  public:
  void unsafe_arena_set_allocated_publicaggredeals(
      ::PublicAggreDealsV3Api* publicaggredeals);
  ::PublicAggreDealsV3Api* unsafe_arena_release_publicaggredeals();

  // .PublicAggreBookTickerV3Api publicAggreBookTicker = 315;
  bool has_publicaggrebookticker() const;
  private:
  bool _internal_has_publicaggrebookticker() const;
  public:
  void clear_publicaggrebookticker();
  const ::PublicAggreBookTickerV3Api& publicaggrebookticker() const;
  PROTOBUF_NODISCARD ::PublicAggreBookTickerV3Api* release_publicaggrebookticker();
  ::PublicAggreBookTickerV3Api* mutable_publicaggrebookticker();
  void set_allocated_publicaggrebookticker(::PublicAggreBookTickerV3Api* publicaggrebookticker);
  private:
  const ::PublicAggreBookTickerV3Api& _internal_publicaggrebookticker() const;
  ::PublicAggreBookTickerV3Api* _internal_mutable_publicaggrebookticker();
  public:
  void unsafe_arena_set_allocated_publicaggrebookticker(
      ::PublicAggreBookTickerV3Api* publicaggrebookticker);
  ::PublicAggreBookTickerV3Api* unsafe_arena_release_publicaggrebookticker();

  void clear_body();
  BodyCase body_case() const;
  // @@protoc_insertion_point(class_scope:PushDataV3ApiWrapper)
 private:
  class _Internal;
  void set_has_publicdeals();
  void set_has_publicincreasedepths();
  void set_has_publiclimitdepths();
  void set_has_privateorders();
  void set_has_publicbookticker();
  void set_has_privatedeals();
  void set_has_privateaccount();
  void set_has_publicspotkline();
  void set_has_publicminiticker();
  void set_has_publicminitickers();
  void set_has_publicbooktickerbatch();
  void set_has_publicincreasedepthsbatch();
  void set_has_publicaggredepths();
  void set_has_publicaggredeals();
  void set_has_publicaggrebookticker();

  inline bool has_body() const;
  inline void clear_has_body();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr channel_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr symbol_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr symbolid_;
    int64_t createtime_;
    int64_t sendtime_;
    union BodyUnion {
      constexpr BodyUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PublicDealsV3Api* publicdeals_;
      ::PublicIncreaseDepthsV3Api* publicincreasedepths_;
      ::PublicLimitDepthsV3Api* publiclimitdepths_;
      ::PrivateOrdersV3Api* privateorders_;
      ::PublicBookTickerV3Api* publicbookticker_;
      ::PrivateDealsV3Api* privatedeals_;
      ::PrivateAccountV3Api* privateaccount_;
      ::PublicSpotKlineV3Api* publicspotkline_;
      ::PublicMiniTickerV3Api* publicminiticker_;
      ::PublicMiniTickersV3Api* publicminitickers_;
      ::PublicBookTickerBatchV3Api* publicbooktickerbatch_;
      ::PublicIncreaseDepthsBatchV3Api* publicincreasedepthsbatch_;
      ::PublicAggreDepthsV3Api* publicaggredepths_;
      ::PublicAggreDealsV3Api* publicaggredeals_;
      ::PublicAggreBookTickerV3Api* publicaggrebookticker_;
    } body_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PushDataV3ApiWrapper_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PushDataV3ApiWrapper

// string channel = 1;
inline void PushDataV3ApiWrapper::clear_channel() {
  _impl_.channel_.ClearToEmpty();
}
inline const std::string& PushDataV3ApiWrapper::channel() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.channel)
  return _internal_channel();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PushDataV3ApiWrapper::set_channel(ArgT0&& arg0, ArgT... args) {
 
 _impl_.channel_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PushDataV3ApiWrapper.channel)
}
inline std::string* PushDataV3ApiWrapper::mutable_channel() {
  std::string* _s = _internal_mutable_channel();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.channel)
  return _s;
}
inline const std::string& PushDataV3ApiWrapper::_internal_channel() const {
  return _impl_.channel_.Get();
}
inline void PushDataV3ApiWrapper::_internal_set_channel(const std::string& value) {
  
  _impl_.channel_.Set(value, GetArenaForAllocation());
}
inline std::string* PushDataV3ApiWrapper::_internal_mutable_channel() {
  
  return _impl_.channel_.Mutable(GetArenaForAllocation());
}
inline std::string* PushDataV3ApiWrapper::release_channel() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.channel)
  return _impl_.channel_.Release();
}
inline void PushDataV3ApiWrapper::set_allocated_channel(std::string* channel) {
  if (channel != nullptr) {
    
  } else {
    
  }
  _impl_.channel_.SetAllocated(channel, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.channel_.IsDefault()) {
    _impl_.channel_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.channel)
}

// .PublicDealsV3Api publicDeals = 301;
inline bool PushDataV3ApiWrapper::_internal_has_publicdeals() const {
  return body_case() == kPublicDeals;
}
inline bool PushDataV3ApiWrapper::has_publicdeals() const {
  return _internal_has_publicdeals();
}
inline void PushDataV3ApiWrapper::set_has_publicdeals() {
  _impl_._oneof_case_[0] = kPublicDeals;
}
inline ::PublicDealsV3Api* PushDataV3ApiWrapper::release_publicdeals() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.publicDeals)
  if (_internal_has_publicdeals()) {
    clear_has_body();
    ::PublicDealsV3Api* temp = _impl_.body_.publicdeals_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.publicdeals_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PublicDealsV3Api& PushDataV3ApiWrapper::_internal_publicdeals() const {
  return _internal_has_publicdeals()
      ? *_impl_.body_.publicdeals_
      : reinterpret_cast< ::PublicDealsV3Api&>(::_PublicDealsV3Api_default_instance_);
}
inline const ::PublicDealsV3Api& PushDataV3ApiWrapper::publicdeals() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.publicDeals)
  return _internal_publicdeals();
}
inline ::PublicDealsV3Api* PushDataV3ApiWrapper::unsafe_arena_release_publicdeals() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.publicDeals)
  if (_internal_has_publicdeals()) {
    clear_has_body();
    ::PublicDealsV3Api* temp = _impl_.body_.publicdeals_;
    _impl_.body_.publicdeals_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_publicdeals(::PublicDealsV3Api* publicdeals) {
  clear_body();
  if (publicdeals) {
    set_has_publicdeals();
    _impl_.body_.publicdeals_ = publicdeals;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.publicDeals)
}
inline ::PublicDealsV3Api* PushDataV3ApiWrapper::_internal_mutable_publicdeals() {
  if (!_internal_has_publicdeals()) {
    clear_body();
    set_has_publicdeals();
    _impl_.body_.publicdeals_ = CreateMaybeMessage< ::PublicDealsV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.publicdeals_;
}
inline ::PublicDealsV3Api* PushDataV3ApiWrapper::mutable_publicdeals() {
  ::PublicDealsV3Api* _msg = _internal_mutable_publicdeals();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.publicDeals)
  return _msg;
}

// .PublicIncreaseDepthsV3Api publicIncreaseDepths = 302;
inline bool PushDataV3ApiWrapper::_internal_has_publicincreasedepths() const {
  return body_case() == kPublicIncreaseDepths;
}
inline bool PushDataV3ApiWrapper::has_publicincreasedepths() const {
  return _internal_has_publicincreasedepths();
}
inline void PushDataV3ApiWrapper::set_has_publicincreasedepths() {
  _impl_._oneof_case_[0] = kPublicIncreaseDepths;
}
inline ::PublicIncreaseDepthsV3Api* PushDataV3ApiWrapper::release_publicincreasedepths() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.publicIncreaseDepths)
  if (_internal_has_publicincreasedepths()) {
    clear_has_body();
    ::PublicIncreaseDepthsV3Api* temp = _impl_.body_.publicincreasedepths_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.publicincreasedepths_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PublicIncreaseDepthsV3Api& PushDataV3ApiWrapper::_internal_publicincreasedepths() const {
  return _internal_has_publicincreasedepths()
      ? *_impl_.body_.publicincreasedepths_
      : reinterpret_cast< ::PublicIncreaseDepthsV3Api&>(::_PublicIncreaseDepthsV3Api_default_instance_);
}
inline const ::PublicIncreaseDepthsV3Api& PushDataV3ApiWrapper::publicincreasedepths() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.publicIncreaseDepths)
  return _internal_publicincreasedepths();
}
inline ::PublicIncreaseDepthsV3Api* PushDataV3ApiWrapper::unsafe_arena_release_publicincreasedepths() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.publicIncreaseDepths)
  if (_internal_has_publicincreasedepths()) {
    clear_has_body();
    ::PublicIncreaseDepthsV3Api* temp = _impl_.body_.publicincreasedepths_;
    _impl_.body_.publicincreasedepths_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_publicincreasedepths(::PublicIncreaseDepthsV3Api* publicincreasedepths) {
  clear_body();
  if (publicincreasedepths) {
    set_has_publicincreasedepths();
    _impl_.body_.publicincreasedepths_ = publicincreasedepths;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.publicIncreaseDepths)
}
inline ::PublicIncreaseDepthsV3Api* PushDataV3ApiWrapper::_internal_mutable_publicincreasedepths() {
  if (!_internal_has_publicincreasedepths()) {
    clear_body();
    set_has_publicincreasedepths();
    _impl_.body_.publicincreasedepths_ = CreateMaybeMessage< ::PublicIncreaseDepthsV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.publicincreasedepths_;
}
inline ::PublicIncreaseDepthsV3Api* PushDataV3ApiWrapper::mutable_publicincreasedepths() {
  ::PublicIncreaseDepthsV3Api* _msg = _internal_mutable_publicincreasedepths();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.publicIncreaseDepths)
  return _msg;
}

// .PublicLimitDepthsV3Api publicLimitDepths = 303;
inline bool PushDataV3ApiWrapper::_internal_has_publiclimitdepths() const {
  return body_case() == kPublicLimitDepths;
}
inline bool PushDataV3ApiWrapper::has_publiclimitdepths() const {
  return _internal_has_publiclimitdepths();
}
inline void PushDataV3ApiWrapper::set_has_publiclimitdepths() {
  _impl_._oneof_case_[0] = kPublicLimitDepths;
}
inline ::PublicLimitDepthsV3Api* PushDataV3ApiWrapper::release_publiclimitdepths() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.publicLimitDepths)
  if (_internal_has_publiclimitdepths()) {
    clear_has_body();
    ::PublicLimitDepthsV3Api* temp = _impl_.body_.publiclimitdepths_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.publiclimitdepths_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PublicLimitDepthsV3Api& PushDataV3ApiWrapper::_internal_publiclimitdepths() const {
  return _internal_has_publiclimitdepths()
      ? *_impl_.body_.publiclimitdepths_
      : reinterpret_cast< ::PublicLimitDepthsV3Api&>(::_PublicLimitDepthsV3Api_default_instance_);
}
inline const ::PublicLimitDepthsV3Api& PushDataV3ApiWrapper::publiclimitdepths() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.publicLimitDepths)
  return _internal_publiclimitdepths();
}
inline ::PublicLimitDepthsV3Api* PushDataV3ApiWrapper::unsafe_arena_release_publiclimitdepths() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.publicLimitDepths)
  if (_internal_has_publiclimitdepths()) {
    clear_has_body();
    ::PublicLimitDepthsV3Api* temp = _impl_.body_.publiclimitdepths_;
    _impl_.body_.publiclimitdepths_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_publiclimitdepths(::PublicLimitDepthsV3Api* publiclimitdepths) {
  clear_body();
  if (publiclimitdepths) {
    set_has_publiclimitdepths();
    _impl_.body_.publiclimitdepths_ = publiclimitdepths;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.publicLimitDepths)
}
inline ::PublicLimitDepthsV3Api* PushDataV3ApiWrapper::_internal_mutable_publiclimitdepths() {
  if (!_internal_has_publiclimitdepths()) {
    clear_body();
    set_has_publiclimitdepths();
    _impl_.body_.publiclimitdepths_ = CreateMaybeMessage< ::PublicLimitDepthsV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.publiclimitdepths_;
}
inline ::PublicLimitDepthsV3Api* PushDataV3ApiWrapper::mutable_publiclimitdepths() {
  ::PublicLimitDepthsV3Api* _msg = _internal_mutable_publiclimitdepths();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.publicLimitDepths)
  return _msg;
}

// .PrivateOrdersV3Api privateOrders = 304;
inline bool PushDataV3ApiWrapper::_internal_has_privateorders() const {
  return body_case() == kPrivateOrders;
}
inline bool PushDataV3ApiWrapper::has_privateorders() const {
  return _internal_has_privateorders();
}
inline void PushDataV3ApiWrapper::set_has_privateorders() {
  _impl_._oneof_case_[0] = kPrivateOrders;
}
inline ::PrivateOrdersV3Api* PushDataV3ApiWrapper::release_privateorders() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.privateOrders)
  if (_internal_has_privateorders()) {
    clear_has_body();
    ::PrivateOrdersV3Api* temp = _impl_.body_.privateorders_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.privateorders_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PrivateOrdersV3Api& PushDataV3ApiWrapper::_internal_privateorders() const {
  return _internal_has_privateorders()
      ? *_impl_.body_.privateorders_
      : reinterpret_cast< ::PrivateOrdersV3Api&>(::_PrivateOrdersV3Api_default_instance_);
}
inline const ::PrivateOrdersV3Api& PushDataV3ApiWrapper::privateorders() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.privateOrders)
  return _internal_privateorders();
}
inline ::PrivateOrdersV3Api* PushDataV3ApiWrapper::unsafe_arena_release_privateorders() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.privateOrders)
  if (_internal_has_privateorders()) {
    clear_has_body();
    ::PrivateOrdersV3Api* temp = _impl_.body_.privateorders_;
    _impl_.body_.privateorders_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_privateorders(::PrivateOrdersV3Api* privateorders) {
  clear_body();
  if (privateorders) {
    set_has_privateorders();
    _impl_.body_.privateorders_ = privateorders;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.privateOrders)
}
inline ::PrivateOrdersV3Api* PushDataV3ApiWrapper::_internal_mutable_privateorders() {
  if (!_internal_has_privateorders()) {
    clear_body();
    set_has_privateorders();
    _impl_.body_.privateorders_ = CreateMaybeMessage< ::PrivateOrdersV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.privateorders_;
}
inline ::PrivateOrdersV3Api* PushDataV3ApiWrapper::mutable_privateorders() {
  ::PrivateOrdersV3Api* _msg = _internal_mutable_privateorders();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.privateOrders)
  return _msg;
}

// .PublicBookTickerV3Api publicBookTicker = 305;
inline bool PushDataV3ApiWrapper::_internal_has_publicbookticker() const {
  return body_case() == kPublicBookTicker;
}
inline bool PushDataV3ApiWrapper::has_publicbookticker() const {
  return _internal_has_publicbookticker();
}
inline void PushDataV3ApiWrapper::set_has_publicbookticker() {
  _impl_._oneof_case_[0] = kPublicBookTicker;
}
inline ::PublicBookTickerV3Api* PushDataV3ApiWrapper::release_publicbookticker() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.publicBookTicker)
  if (_internal_has_publicbookticker()) {
    clear_has_body();
    ::PublicBookTickerV3Api* temp = _impl_.body_.publicbookticker_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.publicbookticker_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PublicBookTickerV3Api& PushDataV3ApiWrapper::_internal_publicbookticker() const {
  return _internal_has_publicbookticker()
      ? *_impl_.body_.publicbookticker_
      : reinterpret_cast< ::PublicBookTickerV3Api&>(::_PublicBookTickerV3Api_default_instance_);
}
inline const ::PublicBookTickerV3Api& PushDataV3ApiWrapper::publicbookticker() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.publicBookTicker)
  return _internal_publicbookticker();
}
inline ::PublicBookTickerV3Api* PushDataV3ApiWrapper::unsafe_arena_release_publicbookticker() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.publicBookTicker)
  if (_internal_has_publicbookticker()) {
    clear_has_body();
    ::PublicBookTickerV3Api* temp = _impl_.body_.publicbookticker_;
    _impl_.body_.publicbookticker_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_publicbookticker(::PublicBookTickerV3Api* publicbookticker) {
  clear_body();
  if (publicbookticker) {
    set_has_publicbookticker();
    _impl_.body_.publicbookticker_ = publicbookticker;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.publicBookTicker)
}
inline ::PublicBookTickerV3Api* PushDataV3ApiWrapper::_internal_mutable_publicbookticker() {
  if (!_internal_has_publicbookticker()) {
    clear_body();
    set_has_publicbookticker();
    _impl_.body_.publicbookticker_ = CreateMaybeMessage< ::PublicBookTickerV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.publicbookticker_;
}
inline ::PublicBookTickerV3Api* PushDataV3ApiWrapper::mutable_publicbookticker() {
  ::PublicBookTickerV3Api* _msg = _internal_mutable_publicbookticker();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.publicBookTicker)
  return _msg;
}

// .PrivateDealsV3Api privateDeals = 306;
inline bool PushDataV3ApiWrapper::_internal_has_privatedeals() const {
  return body_case() == kPrivateDeals;
}
inline bool PushDataV3ApiWrapper::has_privatedeals() const {
  return _internal_has_privatedeals();
}
inline void PushDataV3ApiWrapper::set_has_privatedeals() {
  _impl_._oneof_case_[0] = kPrivateDeals;
}
inline ::PrivateDealsV3Api* PushDataV3ApiWrapper::release_privatedeals() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.privateDeals)
  if (_internal_has_privatedeals()) {
    clear_has_body();
    ::PrivateDealsV3Api* temp = _impl_.body_.privatedeals_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.privatedeals_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PrivateDealsV3Api& PushDataV3ApiWrapper::_internal_privatedeals() const {
  return _internal_has_privatedeals()
      ? *_impl_.body_.privatedeals_
      : reinterpret_cast< ::PrivateDealsV3Api&>(::_PrivateDealsV3Api_default_instance_);
}
inline const ::PrivateDealsV3Api& PushDataV3ApiWrapper::privatedeals() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.privateDeals)
  return _internal_privatedeals();
}
inline ::PrivateDealsV3Api* PushDataV3ApiWrapper::unsafe_arena_release_privatedeals() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.privateDeals)
  if (_internal_has_privatedeals()) {
    clear_has_body();
    ::PrivateDealsV3Api* temp = _impl_.body_.privatedeals_;
    _impl_.body_.privatedeals_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_privatedeals(::PrivateDealsV3Api* privatedeals) {
  clear_body();
  if (privatedeals) {
    set_has_privatedeals();
    _impl_.body_.privatedeals_ = privatedeals;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.privateDeals)
}
inline ::PrivateDealsV3Api* PushDataV3ApiWrapper::_internal_mutable_privatedeals() {
  if (!_internal_has_privatedeals()) {
    clear_body();
    set_has_privatedeals();
    _impl_.body_.privatedeals_ = CreateMaybeMessage< ::PrivateDealsV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.privatedeals_;
}
inline ::PrivateDealsV3Api* PushDataV3ApiWrapper::mutable_privatedeals() {
  ::PrivateDealsV3Api* _msg = _internal_mutable_privatedeals();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.privateDeals)
  return _msg;
}

// .PrivateAccountV3Api privateAccount = 307;
inline bool PushDataV3ApiWrapper::_internal_has_privateaccount() const {
  return body_case() == kPrivateAccount;
}
inline bool PushDataV3ApiWrapper::has_privateaccount() const {
  return _internal_has_privateaccount();
}
inline void PushDataV3ApiWrapper::set_has_privateaccount() {
  _impl_._oneof_case_[0] = kPrivateAccount;
}
inline ::PrivateAccountV3Api* PushDataV3ApiWrapper::release_privateaccount() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.privateAccount)
  if (_internal_has_privateaccount()) {
    clear_has_body();
    ::PrivateAccountV3Api* temp = _impl_.body_.privateaccount_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.privateaccount_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PrivateAccountV3Api& PushDataV3ApiWrapper::_internal_privateaccount() const {
  return _internal_has_privateaccount()
      ? *_impl_.body_.privateaccount_
      : reinterpret_cast< ::PrivateAccountV3Api&>(::_PrivateAccountV3Api_default_instance_);
}
inline const ::PrivateAccountV3Api& PushDataV3ApiWrapper::privateaccount() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.privateAccount)
  return _internal_privateaccount();
}
inline ::PrivateAccountV3Api* PushDataV3ApiWrapper::unsafe_arena_release_privateaccount() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.privateAccount)
  if (_internal_has_privateaccount()) {
    clear_has_body();
    ::PrivateAccountV3Api* temp = _impl_.body_.privateaccount_;
    _impl_.body_.privateaccount_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_privateaccount(::PrivateAccountV3Api* privateaccount) {
  clear_body();
  if (privateaccount) {
    set_has_privateaccount();
    _impl_.body_.privateaccount_ = privateaccount;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.privateAccount)
}
inline ::PrivateAccountV3Api* PushDataV3ApiWrapper::_internal_mutable_privateaccount() {
  if (!_internal_has_privateaccount()) {
    clear_body();
    set_has_privateaccount();
    _impl_.body_.privateaccount_ = CreateMaybeMessage< ::PrivateAccountV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.privateaccount_;
}
inline ::PrivateAccountV3Api* PushDataV3ApiWrapper::mutable_privateaccount() {
  ::PrivateAccountV3Api* _msg = _internal_mutable_privateaccount();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.privateAccount)
  return _msg;
}

// .PublicSpotKlineV3Api publicSpotKline = 308;
inline bool PushDataV3ApiWrapper::_internal_has_publicspotkline() const {
  return body_case() == kPublicSpotKline;
}
inline bool PushDataV3ApiWrapper::has_publicspotkline() const {
  return _internal_has_publicspotkline();
}
inline void PushDataV3ApiWrapper::set_has_publicspotkline() {
  _impl_._oneof_case_[0] = kPublicSpotKline;
}
inline ::PublicSpotKlineV3Api* PushDataV3ApiWrapper::release_publicspotkline() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.publicSpotKline)
  if (_internal_has_publicspotkline()) {
    clear_has_body();
    ::PublicSpotKlineV3Api* temp = _impl_.body_.publicspotkline_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.publicspotkline_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PublicSpotKlineV3Api& PushDataV3ApiWrapper::_internal_publicspotkline() const {
  return _internal_has_publicspotkline()
      ? *_impl_.body_.publicspotkline_
      : reinterpret_cast< ::PublicSpotKlineV3Api&>(::_PublicSpotKlineV3Api_default_instance_);
}
inline const ::PublicSpotKlineV3Api& PushDataV3ApiWrapper::publicspotkline() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.publicSpotKline)
  return _internal_publicspotkline();
}
inline ::PublicSpotKlineV3Api* PushDataV3ApiWrapper::unsafe_arena_release_publicspotkline() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.publicSpotKline)
  if (_internal_has_publicspotkline()) {
    clear_has_body();
    ::PublicSpotKlineV3Api* temp = _impl_.body_.publicspotkline_;
    _impl_.body_.publicspotkline_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_publicspotkline(::PublicSpotKlineV3Api* publicspotkline) {
  clear_body();
  if (publicspotkline) {
    set_has_publicspotkline();
    _impl_.body_.publicspotkline_ = publicspotkline;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.publicSpotKline)
}
inline ::PublicSpotKlineV3Api* PushDataV3ApiWrapper::_internal_mutable_publicspotkline() {
  if (!_internal_has_publicspotkline()) {
    clear_body();
    set_has_publicspotkline();
    _impl_.body_.publicspotkline_ = CreateMaybeMessage< ::PublicSpotKlineV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.publicspotkline_;
}
inline ::PublicSpotKlineV3Api* PushDataV3ApiWrapper::mutable_publicspotkline() {
  ::PublicSpotKlineV3Api* _msg = _internal_mutable_publicspotkline();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.publicSpotKline)
  return _msg;
}

// .PublicMiniTickerV3Api publicMiniTicker = 309;
inline bool PushDataV3ApiWrapper::_internal_has_publicminiticker() const {
  return body_case() == kPublicMiniTicker;
}
inline bool PushDataV3ApiWrapper::has_publicminiticker() const {
  return _internal_has_publicminiticker();
}
inline void PushDataV3ApiWrapper::set_has_publicminiticker() {
  _impl_._oneof_case_[0] = kPublicMiniTicker;
}
inline ::PublicMiniTickerV3Api* PushDataV3ApiWrapper::release_publicminiticker() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.publicMiniTicker)
  if (_internal_has_publicminiticker()) {
    clear_has_body();
    ::PublicMiniTickerV3Api* temp = _impl_.body_.publicminiticker_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.publicminiticker_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PublicMiniTickerV3Api& PushDataV3ApiWrapper::_internal_publicminiticker() const {
  return _internal_has_publicminiticker()
      ? *_impl_.body_.publicminiticker_
      : reinterpret_cast< ::PublicMiniTickerV3Api&>(::_PublicMiniTickerV3Api_default_instance_);
}
inline const ::PublicMiniTickerV3Api& PushDataV3ApiWrapper::publicminiticker() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.publicMiniTicker)
  return _internal_publicminiticker();
}
inline ::PublicMiniTickerV3Api* PushDataV3ApiWrapper::unsafe_arena_release_publicminiticker() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.publicMiniTicker)
  if (_internal_has_publicminiticker()) {
    clear_has_body();
    ::PublicMiniTickerV3Api* temp = _impl_.body_.publicminiticker_;
    _impl_.body_.publicminiticker_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_publicminiticker(::PublicMiniTickerV3Api* publicminiticker) {
  clear_body();
  if (publicminiticker) {
    set_has_publicminiticker();
    _impl_.body_.publicminiticker_ = publicminiticker;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.publicMiniTicker)
}
inline ::PublicMiniTickerV3Api* PushDataV3ApiWrapper::_internal_mutable_publicminiticker() {
  if (!_internal_has_publicminiticker()) {
    clear_body();
    set_has_publicminiticker();
    _impl_.body_.publicminiticker_ = CreateMaybeMessage< ::PublicMiniTickerV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.publicminiticker_;
}
inline ::PublicMiniTickerV3Api* PushDataV3ApiWrapper::mutable_publicminiticker() {
  ::PublicMiniTickerV3Api* _msg = _internal_mutable_publicminiticker();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.publicMiniTicker)
  return _msg;
}

// .PublicMiniTickersV3Api publicMiniTickers = 310;
inline bool PushDataV3ApiWrapper::_internal_has_publicminitickers() const {
  return body_case() == kPublicMiniTickers;
}
inline bool PushDataV3ApiWrapper::has_publicminitickers() const {
  return _internal_has_publicminitickers();
}
inline void PushDataV3ApiWrapper::set_has_publicminitickers() {
  _impl_._oneof_case_[0] = kPublicMiniTickers;
}
inline ::PublicMiniTickersV3Api* PushDataV3ApiWrapper::release_publicminitickers() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.publicMiniTickers)
  if (_internal_has_publicminitickers()) {
    clear_has_body();
    ::PublicMiniTickersV3Api* temp = _impl_.body_.publicminitickers_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.publicminitickers_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PublicMiniTickersV3Api& PushDataV3ApiWrapper::_internal_publicminitickers() const {
  return _internal_has_publicminitickers()
      ? *_impl_.body_.publicminitickers_
      : reinterpret_cast< ::PublicMiniTickersV3Api&>(::_PublicMiniTickersV3Api_default_instance_);
}
inline const ::PublicMiniTickersV3Api& PushDataV3ApiWrapper::publicminitickers() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.publicMiniTickers)
  return _internal_publicminitickers();
}
inline ::PublicMiniTickersV3Api* PushDataV3ApiWrapper::unsafe_arena_release_publicminitickers() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.publicMiniTickers)
  if (_internal_has_publicminitickers()) {
    clear_has_body();
    ::PublicMiniTickersV3Api* temp = _impl_.body_.publicminitickers_;
    _impl_.body_.publicminitickers_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_publicminitickers(::PublicMiniTickersV3Api* publicminitickers) {
  clear_body();
  if (publicminitickers) {
    set_has_publicminitickers();
    _impl_.body_.publicminitickers_ = publicminitickers;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.publicMiniTickers)
}
inline ::PublicMiniTickersV3Api* PushDataV3ApiWrapper::_internal_mutable_publicminitickers() {
  if (!_internal_has_publicminitickers()) {
    clear_body();
    set_has_publicminitickers();
    _impl_.body_.publicminitickers_ = CreateMaybeMessage< ::PublicMiniTickersV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.publicminitickers_;
}
inline ::PublicMiniTickersV3Api* PushDataV3ApiWrapper::mutable_publicminitickers() {
  ::PublicMiniTickersV3Api* _msg = _internal_mutable_publicminitickers();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.publicMiniTickers)
  return _msg;
}

// .PublicBookTickerBatchV3Api publicBookTickerBatch = 311;
inline bool PushDataV3ApiWrapper::_internal_has_publicbooktickerbatch() const {
  return body_case() == kPublicBookTickerBatch;
}
inline bool PushDataV3ApiWrapper::has_publicbooktickerbatch() const {
  return _internal_has_publicbooktickerbatch();
}
inline void PushDataV3ApiWrapper::set_has_publicbooktickerbatch() {
  _impl_._oneof_case_[0] = kPublicBookTickerBatch;
}
inline ::PublicBookTickerBatchV3Api* PushDataV3ApiWrapper::release_publicbooktickerbatch() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.publicBookTickerBatch)
  if (_internal_has_publicbooktickerbatch()) {
    clear_has_body();
    ::PublicBookTickerBatchV3Api* temp = _impl_.body_.publicbooktickerbatch_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.publicbooktickerbatch_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PublicBookTickerBatchV3Api& PushDataV3ApiWrapper::_internal_publicbooktickerbatch() const {
  return _internal_has_publicbooktickerbatch()
      ? *_impl_.body_.publicbooktickerbatch_
      : reinterpret_cast< ::PublicBookTickerBatchV3Api&>(::_PublicBookTickerBatchV3Api_default_instance_);
}
inline const ::PublicBookTickerBatchV3Api& PushDataV3ApiWrapper::publicbooktickerbatch() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.publicBookTickerBatch)
  return _internal_publicbooktickerbatch();
}
inline ::PublicBookTickerBatchV3Api* PushDataV3ApiWrapper::unsafe_arena_release_publicbooktickerbatch() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.publicBookTickerBatch)
  if (_internal_has_publicbooktickerbatch()) {
    clear_has_body();
    ::PublicBookTickerBatchV3Api* temp = _impl_.body_.publicbooktickerbatch_;
    _impl_.body_.publicbooktickerbatch_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_publicbooktickerbatch(::PublicBookTickerBatchV3Api* publicbooktickerbatch) {
  clear_body();
  if (publicbooktickerbatch) {
    set_has_publicbooktickerbatch();
    _impl_.body_.publicbooktickerbatch_ = publicbooktickerbatch;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.publicBookTickerBatch)
}
inline ::PublicBookTickerBatchV3Api* PushDataV3ApiWrapper::_internal_mutable_publicbooktickerbatch() {
  if (!_internal_has_publicbooktickerbatch()) {
    clear_body();
    set_has_publicbooktickerbatch();
    _impl_.body_.publicbooktickerbatch_ = CreateMaybeMessage< ::PublicBookTickerBatchV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.publicbooktickerbatch_;
}
inline ::PublicBookTickerBatchV3Api* PushDataV3ApiWrapper::mutable_publicbooktickerbatch() {
  ::PublicBookTickerBatchV3Api* _msg = _internal_mutable_publicbooktickerbatch();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.publicBookTickerBatch)
  return _msg;
}

// .PublicIncreaseDepthsBatchV3Api publicIncreaseDepthsBatch = 312;
inline bool PushDataV3ApiWrapper::_internal_has_publicincreasedepthsbatch() const {
  return body_case() == kPublicIncreaseDepthsBatch;
}
inline bool PushDataV3ApiWrapper::has_publicincreasedepthsbatch() const {
  return _internal_has_publicincreasedepthsbatch();
}
inline void PushDataV3ApiWrapper::set_has_publicincreasedepthsbatch() {
  _impl_._oneof_case_[0] = kPublicIncreaseDepthsBatch;
}
inline ::PublicIncreaseDepthsBatchV3Api* PushDataV3ApiWrapper::release_publicincreasedepthsbatch() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.publicIncreaseDepthsBatch)
  if (_internal_has_publicincreasedepthsbatch()) {
    clear_has_body();
    ::PublicIncreaseDepthsBatchV3Api* temp = _impl_.body_.publicincreasedepthsbatch_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.publicincreasedepthsbatch_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PublicIncreaseDepthsBatchV3Api& PushDataV3ApiWrapper::_internal_publicincreasedepthsbatch() const {
  return _internal_has_publicincreasedepthsbatch()
      ? *_impl_.body_.publicincreasedepthsbatch_
      : reinterpret_cast< ::PublicIncreaseDepthsBatchV3Api&>(::_PublicIncreaseDepthsBatchV3Api_default_instance_);
}
inline const ::PublicIncreaseDepthsBatchV3Api& PushDataV3ApiWrapper::publicincreasedepthsbatch() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.publicIncreaseDepthsBatch)
  return _internal_publicincreasedepthsbatch();
}
inline ::PublicIncreaseDepthsBatchV3Api* PushDataV3ApiWrapper::unsafe_arena_release_publicincreasedepthsbatch() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.publicIncreaseDepthsBatch)
  if (_internal_has_publicincreasedepthsbatch()) {
    clear_has_body();
    ::PublicIncreaseDepthsBatchV3Api* temp = _impl_.body_.publicincreasedepthsbatch_;
    _impl_.body_.publicincreasedepthsbatch_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_publicincreasedepthsbatch(::PublicIncreaseDepthsBatchV3Api* publicincreasedepthsbatch) {
  clear_body();
  if (publicincreasedepthsbatch) {
    set_has_publicincreasedepthsbatch();
    _impl_.body_.publicincreasedepthsbatch_ = publicincreasedepthsbatch;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.publicIncreaseDepthsBatch)
}
inline ::PublicIncreaseDepthsBatchV3Api* PushDataV3ApiWrapper::_internal_mutable_publicincreasedepthsbatch() {
  if (!_internal_has_publicincreasedepthsbatch()) {
    clear_body();
    set_has_publicincreasedepthsbatch();
    _impl_.body_.publicincreasedepthsbatch_ = CreateMaybeMessage< ::PublicIncreaseDepthsBatchV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.publicincreasedepthsbatch_;
}
inline ::PublicIncreaseDepthsBatchV3Api* PushDataV3ApiWrapper::mutable_publicincreasedepthsbatch() {
  ::PublicIncreaseDepthsBatchV3Api* _msg = _internal_mutable_publicincreasedepthsbatch();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.publicIncreaseDepthsBatch)
  return _msg;
}

// .PublicAggreDepthsV3Api publicAggreDepths = 313;
inline bool PushDataV3ApiWrapper::_internal_has_publicaggredepths() const {
  return body_case() == kPublicAggreDepths;
}
inline bool PushDataV3ApiWrapper::has_publicaggredepths() const {
  return _internal_has_publicaggredepths();
}
inline void PushDataV3ApiWrapper::set_has_publicaggredepths() {
  _impl_._oneof_case_[0] = kPublicAggreDepths;
}
inline ::PublicAggreDepthsV3Api* PushDataV3ApiWrapper::release_publicaggredepths() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.publicAggreDepths)
  if (_internal_has_publicaggredepths()) {
    clear_has_body();
    ::PublicAggreDepthsV3Api* temp = _impl_.body_.publicaggredepths_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.publicaggredepths_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PublicAggreDepthsV3Api& PushDataV3ApiWrapper::_internal_publicaggredepths() const {
  return _internal_has_publicaggredepths()
      ? *_impl_.body_.publicaggredepths_
      : reinterpret_cast< ::PublicAggreDepthsV3Api&>(::_PublicAggreDepthsV3Api_default_instance_);
}
inline const ::PublicAggreDepthsV3Api& PushDataV3ApiWrapper::publicaggredepths() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.publicAggreDepths)
  return _internal_publicaggredepths();
}
inline ::PublicAggreDepthsV3Api* PushDataV3ApiWrapper::unsafe_arena_release_publicaggredepths() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.publicAggreDepths)
  if (_internal_has_publicaggredepths()) {
    clear_has_body();
    ::PublicAggreDepthsV3Api* temp = _impl_.body_.publicaggredepths_;
    _impl_.body_.publicaggredepths_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_publicaggredepths(::PublicAggreDepthsV3Api* publicaggredepths) {
  clear_body();
  if (publicaggredepths) {
    set_has_publicaggredepths();
    _impl_.body_.publicaggredepths_ = publicaggredepths;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.publicAggreDepths)
}
inline ::PublicAggreDepthsV3Api* PushDataV3ApiWrapper::_internal_mutable_publicaggredepths() {
  if (!_internal_has_publicaggredepths()) {
    clear_body();
    set_has_publicaggredepths();
    _impl_.body_.publicaggredepths_ = CreateMaybeMessage< ::PublicAggreDepthsV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.publicaggredepths_;
}
inline ::PublicAggreDepthsV3Api* PushDataV3ApiWrapper::mutable_publicaggredepths() {
  ::PublicAggreDepthsV3Api* _msg = _internal_mutable_publicaggredepths();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.publicAggreDepths)
  return _msg;
}

// .PublicAggreDealsV3Api publicAggreDeals = 314;
inline bool PushDataV3ApiWrapper::_internal_has_publicaggredeals() const {
  return body_case() == kPublicAggreDeals;
}
inline bool PushDataV3ApiWrapper::has_publicaggredeals() const {
  return _internal_has_publicaggredeals();
}
inline void PushDataV3ApiWrapper::set_has_publicaggredeals() {
  _impl_._oneof_case_[0] = kPublicAggreDeals;
}
inline ::PublicAggreDealsV3Api* PushDataV3ApiWrapper::release_publicaggredeals() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.publicAggreDeals)
  if (_internal_has_publicaggredeals()) {
    clear_has_body();
    ::PublicAggreDealsV3Api* temp = _impl_.body_.publicaggredeals_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.publicaggredeals_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PublicAggreDealsV3Api& PushDataV3ApiWrapper::_internal_publicaggredeals() const {
  return _internal_has_publicaggredeals()
      ? *_impl_.body_.publicaggredeals_
      : reinterpret_cast< ::PublicAggreDealsV3Api&>(::_PublicAggreDealsV3Api_default_instance_);
}
inline const ::PublicAggreDealsV3Api& PushDataV3ApiWrapper::publicaggredeals() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.publicAggreDeals)
  return _internal_publicaggredeals();
}
inline ::PublicAggreDealsV3Api* PushDataV3ApiWrapper::unsafe_arena_release_publicaggredeals() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.publicAggreDeals)
  if (_internal_has_publicaggredeals()) {
    clear_has_body();
    ::PublicAggreDealsV3Api* temp = _impl_.body_.publicaggredeals_;
    _impl_.body_.publicaggredeals_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_publicaggredeals(::PublicAggreDealsV3Api* publicaggredeals) {
  clear_body();
  if (publicaggredeals) {
    set_has_publicaggredeals();
    _impl_.body_.publicaggredeals_ = publicaggredeals;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.publicAggreDeals)
}
inline ::PublicAggreDealsV3Api* PushDataV3ApiWrapper::_internal_mutable_publicaggredeals() {
  if (!_internal_has_publicaggredeals()) {
    clear_body();
    set_has_publicaggredeals();
    _impl_.body_.publicaggredeals_ = CreateMaybeMessage< ::PublicAggreDealsV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.publicaggredeals_;
}
inline ::PublicAggreDealsV3Api* PushDataV3ApiWrapper::mutable_publicaggredeals() {
  ::PublicAggreDealsV3Api* _msg = _internal_mutable_publicaggredeals();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.publicAggreDeals)
  return _msg;
}

// .PublicAggreBookTickerV3Api publicAggreBookTicker = 315;
inline bool PushDataV3ApiWrapper::_internal_has_publicaggrebookticker() const {
  return body_case() == kPublicAggreBookTicker;
}
inline bool PushDataV3ApiWrapper::has_publicaggrebookticker() const {
  return _internal_has_publicaggrebookticker();
}
inline void PushDataV3ApiWrapper::set_has_publicaggrebookticker() {
  _impl_._oneof_case_[0] = kPublicAggreBookTicker;
}
inline ::PublicAggreBookTickerV3Api* PushDataV3ApiWrapper::release_publicaggrebookticker() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.publicAggreBookTicker)
  if (_internal_has_publicaggrebookticker()) {
    clear_has_body();
    ::PublicAggreBookTickerV3Api* temp = _impl_.body_.publicaggrebookticker_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.publicaggrebookticker_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PublicAggreBookTickerV3Api& PushDataV3ApiWrapper::_internal_publicaggrebookticker() const {
  return _internal_has_publicaggrebookticker()
      ? *_impl_.body_.publicaggrebookticker_
      : reinterpret_cast< ::PublicAggreBookTickerV3Api&>(::_PublicAggreBookTickerV3Api_default_instance_);
}
inline const ::PublicAggreBookTickerV3Api& PushDataV3ApiWrapper::publicaggrebookticker() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.publicAggreBookTicker)
  return _internal_publicaggrebookticker();
}
inline ::PublicAggreBookTickerV3Api* PushDataV3ApiWrapper::unsafe_arena_release_publicaggrebookticker() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PushDataV3ApiWrapper.publicAggreBookTicker)
  if (_internal_has_publicaggrebookticker()) {
    clear_has_body();
    ::PublicAggreBookTickerV3Api* temp = _impl_.body_.publicaggrebookticker_;
    _impl_.body_.publicaggrebookticker_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PushDataV3ApiWrapper::unsafe_arena_set_allocated_publicaggrebookticker(::PublicAggreBookTickerV3Api* publicaggrebookticker) {
  clear_body();
  if (publicaggrebookticker) {
    set_has_publicaggrebookticker();
    _impl_.body_.publicaggrebookticker_ = publicaggrebookticker;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PushDataV3ApiWrapper.publicAggreBookTicker)
}
inline ::PublicAggreBookTickerV3Api* PushDataV3ApiWrapper::_internal_mutable_publicaggrebookticker() {
  if (!_internal_has_publicaggrebookticker()) {
    clear_body();
    set_has_publicaggrebookticker();
    _impl_.body_.publicaggrebookticker_ = CreateMaybeMessage< ::PublicAggreBookTickerV3Api >(GetArenaForAllocation());
  }
  return _impl_.body_.publicaggrebookticker_;
}
inline ::PublicAggreBookTickerV3Api* PushDataV3ApiWrapper::mutable_publicaggrebookticker() {
  ::PublicAggreBookTickerV3Api* _msg = _internal_mutable_publicaggrebookticker();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.publicAggreBookTicker)
  return _msg;
}

// optional string symbol = 3;
inline bool PushDataV3ApiWrapper::_internal_has_symbol() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PushDataV3ApiWrapper::has_symbol() const {
  return _internal_has_symbol();
}
inline void PushDataV3ApiWrapper::clear_symbol() {
  _impl_.symbol_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PushDataV3ApiWrapper::symbol() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.symbol)
  return _internal_symbol();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PushDataV3ApiWrapper::set_symbol(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.symbol_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PushDataV3ApiWrapper.symbol)
}
inline std::string* PushDataV3ApiWrapper::mutable_symbol() {
  std::string* _s = _internal_mutable_symbol();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.symbol)
  return _s;
}
inline const std::string& PushDataV3ApiWrapper::_internal_symbol() const {
  return _impl_.symbol_.Get();
}
inline void PushDataV3ApiWrapper::_internal_set_symbol(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.symbol_.Set(value, GetArenaForAllocation());
}
inline std::string* PushDataV3ApiWrapper::_internal_mutable_symbol() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.symbol_.Mutable(GetArenaForAllocation());
}
inline std::string* PushDataV3ApiWrapper::release_symbol() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.symbol)
  if (!_internal_has_symbol()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.symbol_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.symbol_.IsDefault()) {
    _impl_.symbol_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PushDataV3ApiWrapper::set_allocated_symbol(std::string* symbol) {
  if (symbol != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.symbol_.SetAllocated(symbol, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.symbol_.IsDefault()) {
    _impl_.symbol_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.symbol)
}

// optional string symbolId = 4;
inline bool PushDataV3ApiWrapper::_internal_has_symbolid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PushDataV3ApiWrapper::has_symbolid() const {
  return _internal_has_symbolid();
}
inline void PushDataV3ApiWrapper::clear_symbolid() {
  _impl_.symbolid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& PushDataV3ApiWrapper::symbolid() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.symbolId)
  return _internal_symbolid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PushDataV3ApiWrapper::set_symbolid(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.symbolid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PushDataV3ApiWrapper.symbolId)
}
inline std::string* PushDataV3ApiWrapper::mutable_symbolid() {
  std::string* _s = _internal_mutable_symbolid();
  // @@protoc_insertion_point(field_mutable:PushDataV3ApiWrapper.symbolId)
  return _s;
}
inline const std::string& PushDataV3ApiWrapper::_internal_symbolid() const {
  return _impl_.symbolid_.Get();
}
inline void PushDataV3ApiWrapper::_internal_set_symbolid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.symbolid_.Set(value, GetArenaForAllocation());
}
inline std::string* PushDataV3ApiWrapper::_internal_mutable_symbolid() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.symbolid_.Mutable(GetArenaForAllocation());
}
inline std::string* PushDataV3ApiWrapper::release_symbolid() {
  // @@protoc_insertion_point(field_release:PushDataV3ApiWrapper.symbolId)
  if (!_internal_has_symbolid()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.symbolid_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.symbolid_.IsDefault()) {
    _impl_.symbolid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PushDataV3ApiWrapper::set_allocated_symbolid(std::string* symbolid) {
  if (symbolid != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.symbolid_.SetAllocated(symbolid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.symbolid_.IsDefault()) {
    _impl_.symbolid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.symbolId)
}

// optional int64 createTime = 5;
inline bool PushDataV3ApiWrapper::_internal_has_createtime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool PushDataV3ApiWrapper::has_createtime() const {
  return _internal_has_createtime();
}
inline void PushDataV3ApiWrapper::clear_createtime() {
  _impl_.createtime_ = int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline int64_t PushDataV3ApiWrapper::_internal_createtime() const {
  return _impl_.createtime_;
}
inline int64_t PushDataV3ApiWrapper::createtime() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.createTime)
  return _internal_createtime();
}
inline void PushDataV3ApiWrapper::_internal_set_createtime(int64_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.createtime_ = value;
}
inline void PushDataV3ApiWrapper::set_createtime(int64_t value) {
  _internal_set_createtime(value);
  // @@protoc_insertion_point(field_set:PushDataV3ApiWrapper.createTime)
}

// optional int64 sendTime = 6;
inline bool PushDataV3ApiWrapper::_internal_has_sendtime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool PushDataV3ApiWrapper::has_sendtime() const {
  return _internal_has_sendtime();
}
inline void PushDataV3ApiWrapper::clear_sendtime() {
  _impl_.sendtime_ = int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline int64_t PushDataV3ApiWrapper::_internal_sendtime() const {
  return _impl_.sendtime_;
}
inline int64_t PushDataV3ApiWrapper::sendtime() const {
  // @@protoc_insertion_point(field_get:PushDataV3ApiWrapper.sendTime)
  return _internal_sendtime();
}
inline void PushDataV3ApiWrapper::_internal_set_sendtime(int64_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.sendtime_ = value;
}
inline void PushDataV3ApiWrapper::set_sendtime(int64_t value) {
  _internal_set_sendtime(value);
  // @@protoc_insertion_point(field_set:PushDataV3ApiWrapper.sendTime)
}

inline bool PushDataV3ApiWrapper::has_body() const {
  return body_case() != BODY_NOT_SET;
}
inline void PushDataV3ApiWrapper::clear_has_body() {
  _impl_._oneof_case_[0] = BODY_NOT_SET;
}
inline PushDataV3ApiWrapper::BodyCase PushDataV3ApiWrapper::body_case() const {
  return PushDataV3ApiWrapper::BodyCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PushDataV3ApiWrapper_2eproto
