// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushDataV3ApiWrapper.proto

#include "PushDataV3ApiWrapper.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR PushDataV3ApiWrapper::PushDataV3ApiWrapper(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.channel_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.symbol_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.symbolid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.createtime_)*/int64_t{0}
  , /*decltype(_impl_.sendtime_)*/int64_t{0}
  , /*decltype(_impl_.body_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct PushDataV3ApiWrapperDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PushDataV3ApiWrapperDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PushDataV3ApiWrapperDefaultTypeInternal() {}
  union {
    PushDataV3ApiWrapper _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PushDataV3ApiWrapperDefaultTypeInternal _PushDataV3ApiWrapper_default_instance_;
static ::_pb::Metadata file_level_metadata_PushDataV3ApiWrapper_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_PushDataV3ApiWrapper_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_PushDataV3ApiWrapper_2eproto = nullptr;

const uint32_t TableStruct_PushDataV3ApiWrapper_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.channel_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.symbol_),
  PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.symbolid_),
  PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.createtime_),
  PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.sendtime_),
  PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  0,
  1,
  2,
  3,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 27, -1, sizeof(::PushDataV3ApiWrapper)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_PushDataV3ApiWrapper_default_instance_._instance,
};

const char descriptor_table_protodef_PushDataV3ApiWrapper_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032PushDataV3ApiWrapper.proto\032\026PublicDeal"
  "sV3Api.proto\032\037PublicIncreaseDepthsV3Api."
  "proto\032\034PublicLimitDepthsV3Api.proto\032\030Pri"
  "vateOrdersV3Api.proto\032\033PublicBookTickerV"
  "3Api.proto\032\027PrivateDealsV3Api.proto\032\031Pri"
  "vateAccountV3Api.proto\032\032PublicSpotKlineV"
  "3Api.proto\032\033PublicMiniTickerV3Api.proto\032"
  "\034PublicMiniTickersV3Api.proto\032 PublicBoo"
  "kTickerBatchV3Api.proto\032$PublicIncreaseD"
  "epthsBatchV3Api.proto\032\034PublicAggreDepths"
  "V3Api.proto\032\033PublicAggreDealsV3Api.proto"
  "\032 PublicAggreBookTickerV3Api.proto\"\360\007\n\024P"
  "ushDataV3ApiWrapper\022\017\n\007channel\030\001 \001(\t\022)\n\013"
  "publicDeals\030\255\002 \001(\0132\021.PublicDealsV3ApiH\000\022"
  ";\n\024publicIncreaseDepths\030\256\002 \001(\0132\032.PublicI"
  "ncreaseDepthsV3ApiH\000\0225\n\021publicLimitDepth"
  "s\030\257\002 \001(\0132\027.PublicLimitDepthsV3ApiH\000\022-\n\rp"
  "rivateOrders\030\260\002 \001(\0132\023.PrivateOrdersV3Api"
  "H\000\0223\n\020publicBookTicker\030\261\002 \001(\0132\026.PublicBo"
  "okTickerV3ApiH\000\022+\n\014privateDeals\030\262\002 \001(\0132\022"
  ".PrivateDealsV3ApiH\000\022/\n\016privateAccount\030\263"
  "\002 \001(\0132\024.PrivateAccountV3ApiH\000\0221\n\017publicS"
  "potKline\030\264\002 \001(\0132\025.PublicSpotKlineV3ApiH\000"
  "\0223\n\020publicMiniTicker\030\265\002 \001(\0132\026.PublicMini"
  "TickerV3ApiH\000\0225\n\021publicMiniTickers\030\266\002 \001("
  "\0132\027.PublicMiniTickersV3ApiH\000\022=\n\025publicBo"
  "okTickerBatch\030\267\002 \001(\0132\033.PublicBookTickerB"
  "atchV3ApiH\000\022E\n\031publicIncreaseDepthsBatch"
  "\030\270\002 \001(\0132\037.PublicIncreaseDepthsBatchV3Api"
  "H\000\0225\n\021publicAggreDepths\030\271\002 \001(\0132\027.PublicA"
  "ggreDepthsV3ApiH\000\0223\n\020publicAggreDeals\030\272\002"
  " \001(\0132\026.PublicAggreDealsV3ApiH\000\022=\n\025public"
  "AggreBookTicker\030\273\002 \001(\0132\033.PublicAggreBook"
  "TickerV3ApiH\000\022\023\n\006symbol\030\003 \001(\tH\001\210\001\001\022\025\n\010sy"
  "mbolId\030\004 \001(\tH\002\210\001\001\022\027\n\ncreateTime\030\005 \001(\003H\003\210"
  "\001\001\022\025\n\010sendTime\030\006 \001(\003H\004\210\001\001B\006\n\004bodyB\t\n\007_sy"
  "mbolB\013\n\t_symbolIdB\r\n\013_createTimeB\013\n\t_sen"
  "dTimeB=\n\034com.mxc.push.common.protobufB\031P"
  "ushDataV3ApiWrapperProtoH\001P\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_PushDataV3ApiWrapper_2eproto_deps[15] = {
  &::descriptor_table_PrivateAccountV3Api_2eproto,
  &::descriptor_table_PrivateDealsV3Api_2eproto,
  &::descriptor_table_PrivateOrdersV3Api_2eproto,
  &::descriptor_table_PublicAggreBookTickerV3Api_2eproto,
  &::descriptor_table_PublicAggreDealsV3Api_2eproto,
  &::descriptor_table_PublicAggreDepthsV3Api_2eproto,
  &::descriptor_table_PublicBookTickerBatchV3Api_2eproto,
  &::descriptor_table_PublicBookTickerV3Api_2eproto,
  &::descriptor_table_PublicDealsV3Api_2eproto,
  &::descriptor_table_PublicIncreaseDepthsBatchV3Api_2eproto,
  &::descriptor_table_PublicIncreaseDepthsV3Api_2eproto,
  &::descriptor_table_PublicLimitDepthsV3Api_2eproto,
  &::descriptor_table_PublicMiniTickerV3Api_2eproto,
  &::descriptor_table_PublicMiniTickersV3Api_2eproto,
  &::descriptor_table_PublicSpotKlineV3Api_2eproto,
};
static ::_pbi::once_flag descriptor_table_PushDataV3ApiWrapper_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_PushDataV3ApiWrapper_2eproto = {
    false, false, 1556, descriptor_table_protodef_PushDataV3ApiWrapper_2eproto,
    "PushDataV3ApiWrapper.proto",
    &descriptor_table_PushDataV3ApiWrapper_2eproto_once, descriptor_table_PushDataV3ApiWrapper_2eproto_deps, 15, 1,
    schemas, file_default_instances, TableStruct_PushDataV3ApiWrapper_2eproto::offsets,
    file_level_metadata_PushDataV3ApiWrapper_2eproto, file_level_enum_descriptors_PushDataV3ApiWrapper_2eproto,
    file_level_service_descriptors_PushDataV3ApiWrapper_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_PushDataV3ApiWrapper_2eproto_getter() {
  return &descriptor_table_PushDataV3ApiWrapper_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_PushDataV3ApiWrapper_2eproto(&descriptor_table_PushDataV3ApiWrapper_2eproto);

// ===================================================================

class PushDataV3ApiWrapper::_Internal {
 public:
  using HasBits = decltype(std::declval<PushDataV3ApiWrapper>()._impl_._has_bits_);
  static const ::PublicDealsV3Api& publicdeals(const PushDataV3ApiWrapper* msg);
  static const ::PublicIncreaseDepthsV3Api& publicincreasedepths(const PushDataV3ApiWrapper* msg);
  static const ::PublicLimitDepthsV3Api& publiclimitdepths(const PushDataV3ApiWrapper* msg);
  static const ::PrivateOrdersV3Api& privateorders(const PushDataV3ApiWrapper* msg);
  static const ::PublicBookTickerV3Api& publicbookticker(const PushDataV3ApiWrapper* msg);
  static const ::PrivateDealsV3Api& privatedeals(const PushDataV3ApiWrapper* msg);
  static const ::PrivateAccountV3Api& privateaccount(const PushDataV3ApiWrapper* msg);
  static const ::PublicSpotKlineV3Api& publicspotkline(const PushDataV3ApiWrapper* msg);
  static const ::PublicMiniTickerV3Api& publicminiticker(const PushDataV3ApiWrapper* msg);
  static const ::PublicMiniTickersV3Api& publicminitickers(const PushDataV3ApiWrapper* msg);
  static const ::PublicBookTickerBatchV3Api& publicbooktickerbatch(const PushDataV3ApiWrapper* msg);
  static const ::PublicIncreaseDepthsBatchV3Api& publicincreasedepthsbatch(const PushDataV3ApiWrapper* msg);
  static const ::PublicAggreDepthsV3Api& publicaggredepths(const PushDataV3ApiWrapper* msg);
  static const ::PublicAggreDealsV3Api& publicaggredeals(const PushDataV3ApiWrapper* msg);
  static const ::PublicAggreBookTickerV3Api& publicaggrebookticker(const PushDataV3ApiWrapper* msg);
  static void set_has_symbol(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_symbolid(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_createtime(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_sendtime(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

const ::PublicDealsV3Api&
PushDataV3ApiWrapper::_Internal::publicdeals(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.publicdeals_;
}
const ::PublicIncreaseDepthsV3Api&
PushDataV3ApiWrapper::_Internal::publicincreasedepths(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.publicincreasedepths_;
}
const ::PublicLimitDepthsV3Api&
PushDataV3ApiWrapper::_Internal::publiclimitdepths(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.publiclimitdepths_;
}
const ::PrivateOrdersV3Api&
PushDataV3ApiWrapper::_Internal::privateorders(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.privateorders_;
}
const ::PublicBookTickerV3Api&
PushDataV3ApiWrapper::_Internal::publicbookticker(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.publicbookticker_;
}
const ::PrivateDealsV3Api&
PushDataV3ApiWrapper::_Internal::privatedeals(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.privatedeals_;
}
const ::PrivateAccountV3Api&
PushDataV3ApiWrapper::_Internal::privateaccount(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.privateaccount_;
}
const ::PublicSpotKlineV3Api&
PushDataV3ApiWrapper::_Internal::publicspotkline(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.publicspotkline_;
}
const ::PublicMiniTickerV3Api&
PushDataV3ApiWrapper::_Internal::publicminiticker(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.publicminiticker_;
}
const ::PublicMiniTickersV3Api&
PushDataV3ApiWrapper::_Internal::publicminitickers(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.publicminitickers_;
}
const ::PublicBookTickerBatchV3Api&
PushDataV3ApiWrapper::_Internal::publicbooktickerbatch(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.publicbooktickerbatch_;
}
const ::PublicIncreaseDepthsBatchV3Api&
PushDataV3ApiWrapper::_Internal::publicincreasedepthsbatch(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.publicincreasedepthsbatch_;
}
const ::PublicAggreDepthsV3Api&
PushDataV3ApiWrapper::_Internal::publicaggredepths(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.publicaggredepths_;
}
const ::PublicAggreDealsV3Api&
PushDataV3ApiWrapper::_Internal::publicaggredeals(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.publicaggredeals_;
}
const ::PublicAggreBookTickerV3Api&
PushDataV3ApiWrapper::_Internal::publicaggrebookticker(const PushDataV3ApiWrapper* msg) {
  return *msg->_impl_.body_.publicaggrebookticker_;
}
void PushDataV3ApiWrapper::set_allocated_publicdeals(::PublicDealsV3Api* publicdeals) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (publicdeals) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(publicdeals));
    if (message_arena != submessage_arena) {
      publicdeals = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, publicdeals, submessage_arena);
    }
    set_has_publicdeals();
    _impl_.body_.publicdeals_ = publicdeals;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicDeals)
}
void PushDataV3ApiWrapper::clear_publicdeals() {
  if (_internal_has_publicdeals()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.publicdeals_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicincreasedepths(::PublicIncreaseDepthsV3Api* publicincreasedepths) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (publicincreasedepths) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(publicincreasedepths));
    if (message_arena != submessage_arena) {
      publicincreasedepths = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, publicincreasedepths, submessage_arena);
    }
    set_has_publicincreasedepths();
    _impl_.body_.publicincreasedepths_ = publicincreasedepths;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicIncreaseDepths)
}
void PushDataV3ApiWrapper::clear_publicincreasedepths() {
  if (_internal_has_publicincreasedepths()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.publicincreasedepths_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publiclimitdepths(::PublicLimitDepthsV3Api* publiclimitdepths) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (publiclimitdepths) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(publiclimitdepths));
    if (message_arena != submessage_arena) {
      publiclimitdepths = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, publiclimitdepths, submessage_arena);
    }
    set_has_publiclimitdepths();
    _impl_.body_.publiclimitdepths_ = publiclimitdepths;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicLimitDepths)
}
void PushDataV3ApiWrapper::clear_publiclimitdepths() {
  if (_internal_has_publiclimitdepths()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.publiclimitdepths_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_privateorders(::PrivateOrdersV3Api* privateorders) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (privateorders) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(privateorders));
    if (message_arena != submessage_arena) {
      privateorders = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, privateorders, submessage_arena);
    }
    set_has_privateorders();
    _impl_.body_.privateorders_ = privateorders;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.privateOrders)
}
void PushDataV3ApiWrapper::clear_privateorders() {
  if (_internal_has_privateorders()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.privateorders_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicbookticker(::PublicBookTickerV3Api* publicbookticker) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (publicbookticker) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(publicbookticker));
    if (message_arena != submessage_arena) {
      publicbookticker = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, publicbookticker, submessage_arena);
    }
    set_has_publicbookticker();
    _impl_.body_.publicbookticker_ = publicbookticker;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicBookTicker)
}
void PushDataV3ApiWrapper::clear_publicbookticker() {
  if (_internal_has_publicbookticker()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.publicbookticker_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_privatedeals(::PrivateDealsV3Api* privatedeals) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (privatedeals) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(privatedeals));
    if (message_arena != submessage_arena) {
      privatedeals = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, privatedeals, submessage_arena);
    }
    set_has_privatedeals();
    _impl_.body_.privatedeals_ = privatedeals;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.privateDeals)
}
void PushDataV3ApiWrapper::clear_privatedeals() {
  if (_internal_has_privatedeals()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.privatedeals_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_privateaccount(::PrivateAccountV3Api* privateaccount) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (privateaccount) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(privateaccount));
    if (message_arena != submessage_arena) {
      privateaccount = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, privateaccount, submessage_arena);
    }
    set_has_privateaccount();
    _impl_.body_.privateaccount_ = privateaccount;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.privateAccount)
}
void PushDataV3ApiWrapper::clear_privateaccount() {
  if (_internal_has_privateaccount()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.privateaccount_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicspotkline(::PublicSpotKlineV3Api* publicspotkline) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (publicspotkline) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(publicspotkline));
    if (message_arena != submessage_arena) {
      publicspotkline = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, publicspotkline, submessage_arena);
    }
    set_has_publicspotkline();
    _impl_.body_.publicspotkline_ = publicspotkline;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicSpotKline)
}
void PushDataV3ApiWrapper::clear_publicspotkline() {
  if (_internal_has_publicspotkline()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.publicspotkline_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicminiticker(::PublicMiniTickerV3Api* publicminiticker) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (publicminiticker) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(publicminiticker));
    if (message_arena != submessage_arena) {
      publicminiticker = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, publicminiticker, submessage_arena);
    }
    set_has_publicminiticker();
    _impl_.body_.publicminiticker_ = publicminiticker;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicMiniTicker)
}
void PushDataV3ApiWrapper::clear_publicminiticker() {
  if (_internal_has_publicminiticker()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.publicminiticker_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicminitickers(::PublicMiniTickersV3Api* publicminitickers) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (publicminitickers) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(publicminitickers));
    if (message_arena != submessage_arena) {
      publicminitickers = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, publicminitickers, submessage_arena);
    }
    set_has_publicminitickers();
    _impl_.body_.publicminitickers_ = publicminitickers;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicMiniTickers)
}
void PushDataV3ApiWrapper::clear_publicminitickers() {
  if (_internal_has_publicminitickers()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.publicminitickers_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicbooktickerbatch(::PublicBookTickerBatchV3Api* publicbooktickerbatch) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (publicbooktickerbatch) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(publicbooktickerbatch));
    if (message_arena != submessage_arena) {
      publicbooktickerbatch = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, publicbooktickerbatch, submessage_arena);
    }
    set_has_publicbooktickerbatch();
    _impl_.body_.publicbooktickerbatch_ = publicbooktickerbatch;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicBookTickerBatch)
}
void PushDataV3ApiWrapper::clear_publicbooktickerbatch() {
  if (_internal_has_publicbooktickerbatch()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.publicbooktickerbatch_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicincreasedepthsbatch(::PublicIncreaseDepthsBatchV3Api* publicincreasedepthsbatch) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (publicincreasedepthsbatch) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(publicincreasedepthsbatch));
    if (message_arena != submessage_arena) {
      publicincreasedepthsbatch = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, publicincreasedepthsbatch, submessage_arena);
    }
    set_has_publicincreasedepthsbatch();
    _impl_.body_.publicincreasedepthsbatch_ = publicincreasedepthsbatch;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicIncreaseDepthsBatch)
}
void PushDataV3ApiWrapper::clear_publicincreasedepthsbatch() {
  if (_internal_has_publicincreasedepthsbatch()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.publicincreasedepthsbatch_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicaggredepths(::PublicAggreDepthsV3Api* publicaggredepths) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (publicaggredepths) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(publicaggredepths));
    if (message_arena != submessage_arena) {
      publicaggredepths = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, publicaggredepths, submessage_arena);
    }
    set_has_publicaggredepths();
    _impl_.body_.publicaggredepths_ = publicaggredepths;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicAggreDepths)
}
void PushDataV3ApiWrapper::clear_publicaggredepths() {
  if (_internal_has_publicaggredepths()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.publicaggredepths_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicaggredeals(::PublicAggreDealsV3Api* publicaggredeals) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (publicaggredeals) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(publicaggredeals));
    if (message_arena != submessage_arena) {
      publicaggredeals = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, publicaggredeals, submessage_arena);
    }
    set_has_publicaggredeals();
    _impl_.body_.publicaggredeals_ = publicaggredeals;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicAggreDeals)
}
void PushDataV3ApiWrapper::clear_publicaggredeals() {
  if (_internal_has_publicaggredeals()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.publicaggredeals_;
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicaggrebookticker(::PublicAggreBookTickerV3Api* publicaggrebookticker) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_body();
  if (publicaggrebookticker) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(publicaggrebookticker));
    if (message_arena != submessage_arena) {
      publicaggrebookticker = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, publicaggrebookticker, submessage_arena);
    }
    set_has_publicaggrebookticker();
    _impl_.body_.publicaggrebookticker_ = publicaggrebookticker;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicAggreBookTicker)
}
void PushDataV3ApiWrapper::clear_publicaggrebookticker() {
  if (_internal_has_publicaggrebookticker()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.body_.publicaggrebookticker_;
    }
    clear_has_body();
  }
}
PushDataV3ApiWrapper::PushDataV3ApiWrapper(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PushDataV3ApiWrapper)
}
PushDataV3ApiWrapper::PushDataV3ApiWrapper(const PushDataV3ApiWrapper& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PushDataV3ApiWrapper* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.channel_){}
    , decltype(_impl_.symbol_){}
    , decltype(_impl_.symbolid_){}
    , decltype(_impl_.createtime_){}
    , decltype(_impl_.sendtime_){}
    , decltype(_impl_.body_){}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.channel_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.channel_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_channel().empty()) {
    _this->_impl_.channel_.Set(from._internal_channel(), 
      _this->GetArenaForAllocation());
  }
  _impl_.symbol_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.symbol_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_symbol()) {
    _this->_impl_.symbol_.Set(from._internal_symbol(), 
      _this->GetArenaForAllocation());
  }
  _impl_.symbolid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.symbolid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_symbolid()) {
    _this->_impl_.symbolid_.Set(from._internal_symbolid(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.createtime_, &from._impl_.createtime_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.sendtime_) -
    reinterpret_cast<char*>(&_impl_.createtime_)) + sizeof(_impl_.sendtime_));
  clear_has_body();
  switch (from.body_case()) {
    case kPublicDeals: {
      _this->_internal_mutable_publicdeals()->::PublicDealsV3Api::MergeFrom(
          from._internal_publicdeals());
      break;
    }
    case kPublicIncreaseDepths: {
      _this->_internal_mutable_publicincreasedepths()->::PublicIncreaseDepthsV3Api::MergeFrom(
          from._internal_publicincreasedepths());
      break;
    }
    case kPublicLimitDepths: {
      _this->_internal_mutable_publiclimitdepths()->::PublicLimitDepthsV3Api::MergeFrom(
          from._internal_publiclimitdepths());
      break;
    }
    case kPrivateOrders: {
      _this->_internal_mutable_privateorders()->::PrivateOrdersV3Api::MergeFrom(
          from._internal_privateorders());
      break;
    }
    case kPublicBookTicker: {
      _this->_internal_mutable_publicbookticker()->::PublicBookTickerV3Api::MergeFrom(
          from._internal_publicbookticker());
      break;
    }
    case kPrivateDeals: {
      _this->_internal_mutable_privatedeals()->::PrivateDealsV3Api::MergeFrom(
          from._internal_privatedeals());
      break;
    }
    case kPrivateAccount: {
      _this->_internal_mutable_privateaccount()->::PrivateAccountV3Api::MergeFrom(
          from._internal_privateaccount());
      break;
    }
    case kPublicSpotKline: {
      _this->_internal_mutable_publicspotkline()->::PublicSpotKlineV3Api::MergeFrom(
          from._internal_publicspotkline());
      break;
    }
    case kPublicMiniTicker: {
      _this->_internal_mutable_publicminiticker()->::PublicMiniTickerV3Api::MergeFrom(
          from._internal_publicminiticker());
      break;
    }
    case kPublicMiniTickers: {
      _this->_internal_mutable_publicminitickers()->::PublicMiniTickersV3Api::MergeFrom(
          from._internal_publicminitickers());
      break;
    }
    case kPublicBookTickerBatch: {
      _this->_internal_mutable_publicbooktickerbatch()->::PublicBookTickerBatchV3Api::MergeFrom(
          from._internal_publicbooktickerbatch());
      break;
    }
    case kPublicIncreaseDepthsBatch: {
      _this->_internal_mutable_publicincreasedepthsbatch()->::PublicIncreaseDepthsBatchV3Api::MergeFrom(
          from._internal_publicincreasedepthsbatch());
      break;
    }
    case kPublicAggreDepths: {
      _this->_internal_mutable_publicaggredepths()->::PublicAggreDepthsV3Api::MergeFrom(
          from._internal_publicaggredepths());
      break;
    }
    case kPublicAggreDeals: {
      _this->_internal_mutable_publicaggredeals()->::PublicAggreDealsV3Api::MergeFrom(
          from._internal_publicaggredeals());
      break;
    }
    case kPublicAggreBookTicker: {
      _this->_internal_mutable_publicaggrebookticker()->::PublicAggreBookTickerV3Api::MergeFrom(
          from._internal_publicaggrebookticker());
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:PushDataV3ApiWrapper)
}

inline void PushDataV3ApiWrapper::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.channel_){}
    , decltype(_impl_.symbol_){}
    , decltype(_impl_.symbolid_){}
    , decltype(_impl_.createtime_){int64_t{0}}
    , decltype(_impl_.sendtime_){int64_t{0}}
    , decltype(_impl_.body_){}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.channel_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.channel_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.symbol_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.symbol_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.symbolid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.symbolid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_body();
}

PushDataV3ApiWrapper::~PushDataV3ApiWrapper() {
  // @@protoc_insertion_point(destructor:PushDataV3ApiWrapper)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PushDataV3ApiWrapper::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.channel_.Destroy();
  _impl_.symbol_.Destroy();
  _impl_.symbolid_.Destroy();
  if (has_body()) {
    clear_body();
  }
}

void PushDataV3ApiWrapper::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PushDataV3ApiWrapper::clear_body() {
// @@protoc_insertion_point(one_of_clear_start:PushDataV3ApiWrapper)
  switch (body_case()) {
    case kPublicDeals: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.publicdeals_;
      }
      break;
    }
    case kPublicIncreaseDepths: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.publicincreasedepths_;
      }
      break;
    }
    case kPublicLimitDepths: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.publiclimitdepths_;
      }
      break;
    }
    case kPrivateOrders: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.privateorders_;
      }
      break;
    }
    case kPublicBookTicker: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.publicbookticker_;
      }
      break;
    }
    case kPrivateDeals: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.privatedeals_;
      }
      break;
    }
    case kPrivateAccount: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.privateaccount_;
      }
      break;
    }
    case kPublicSpotKline: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.publicspotkline_;
      }
      break;
    }
    case kPublicMiniTicker: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.publicminiticker_;
      }
      break;
    }
    case kPublicMiniTickers: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.publicminitickers_;
      }
      break;
    }
    case kPublicBookTickerBatch: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.publicbooktickerbatch_;
      }
      break;
    }
    case kPublicIncreaseDepthsBatch: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.publicincreasedepthsbatch_;
      }
      break;
    }
    case kPublicAggreDepths: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.publicaggredepths_;
      }
      break;
    }
    case kPublicAggreDeals: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.publicaggredeals_;
      }
      break;
    }
    case kPublicAggreBookTicker: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.body_.publicaggrebookticker_;
      }
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = BODY_NOT_SET;
}


void PushDataV3ApiWrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:PushDataV3ApiWrapper)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.channel_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.symbol_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.symbolid_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x0000000cu) {
    ::memset(&_impl_.createtime_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.sendtime_) -
        reinterpret_cast<char*>(&_impl_.createtime_)) + sizeof(_impl_.sendtime_));
  }
  clear_body();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PushDataV3ApiWrapper::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string channel = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_channel();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PushDataV3ApiWrapper.channel"));
        } else
          goto handle_unusual;
        continue;
      // optional string symbol = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_symbol();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PushDataV3ApiWrapper.symbol"));
        } else
          goto handle_unusual;
        continue;
      // optional string symbolId = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_symbolid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PushDataV3ApiWrapper.symbolId"));
        } else
          goto handle_unusual;
        continue;
      // optional int64 createTime = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _Internal::set_has_createtime(&has_bits);
          _impl_.createtime_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int64 sendTime = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_sendtime(&has_bits);
          _impl_.sendtime_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PublicDealsV3Api publicDeals = 301;
      case 301:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          ptr = ctx->ParseMessage(_internal_mutable_publicdeals(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PublicIncreaseDepthsV3Api publicIncreaseDepths = 302;
      case 302:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 114)) {
          ptr = ctx->ParseMessage(_internal_mutable_publicincreasedepths(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PublicLimitDepthsV3Api publicLimitDepths = 303;
      case 303:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 122)) {
          ptr = ctx->ParseMessage(_internal_mutable_publiclimitdepths(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PrivateOrdersV3Api privateOrders = 304;
      case 304:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 130)) {
          ptr = ctx->ParseMessage(_internal_mutable_privateorders(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PublicBookTickerV3Api publicBookTicker = 305;
      case 305:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 138)) {
          ptr = ctx->ParseMessage(_internal_mutable_publicbookticker(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PrivateDealsV3Api privateDeals = 306;
      case 306:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 146)) {
          ptr = ctx->ParseMessage(_internal_mutable_privatedeals(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PrivateAccountV3Api privateAccount = 307;
      case 307:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 154)) {
          ptr = ctx->ParseMessage(_internal_mutable_privateaccount(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PublicSpotKlineV3Api publicSpotKline = 308;
      case 308:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 162)) {
          ptr = ctx->ParseMessage(_internal_mutable_publicspotkline(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PublicMiniTickerV3Api publicMiniTicker = 309;
      case 309:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 170)) {
          ptr = ctx->ParseMessage(_internal_mutable_publicminiticker(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PublicMiniTickersV3Api publicMiniTickers = 310;
      case 310:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 178)) {
          ptr = ctx->ParseMessage(_internal_mutable_publicminitickers(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PublicBookTickerBatchV3Api publicBookTickerBatch = 311;
      case 311:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 186)) {
          ptr = ctx->ParseMessage(_internal_mutable_publicbooktickerbatch(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PublicIncreaseDepthsBatchV3Api publicIncreaseDepthsBatch = 312;
      case 312:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 194)) {
          ptr = ctx->ParseMessage(_internal_mutable_publicincreasedepthsbatch(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PublicAggreDepthsV3Api publicAggreDepths = 313;
      case 313:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 202)) {
          ptr = ctx->ParseMessage(_internal_mutable_publicaggredepths(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PublicAggreDealsV3Api publicAggreDeals = 314;
      case 314:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 210)) {
          ptr = ctx->ParseMessage(_internal_mutable_publicaggredeals(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .PublicAggreBookTickerV3Api publicAggreBookTicker = 315;
      case 315:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 218)) {
          ptr = ctx->ParseMessage(_internal_mutable_publicaggrebookticker(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PushDataV3ApiWrapper::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PushDataV3ApiWrapper)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string channel = 1;
  if (!this->_internal_channel().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_channel().data(), static_cast<int>(this->_internal_channel().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PushDataV3ApiWrapper.channel");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_channel(), target);
  }

  // optional string symbol = 3;
  if (_internal_has_symbol()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_symbol().data(), static_cast<int>(this->_internal_symbol().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PushDataV3ApiWrapper.symbol");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_symbol(), target);
  }

  // optional string symbolId = 4;
  if (_internal_has_symbolid()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_symbolid().data(), static_cast<int>(this->_internal_symbolid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PushDataV3ApiWrapper.symbolId");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_symbolid(), target);
  }

  // optional int64 createTime = 5;
  if (_internal_has_createtime()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(5, this->_internal_createtime(), target);
  }

  // optional int64 sendTime = 6;
  if (_internal_has_sendtime()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(6, this->_internal_sendtime(), target);
  }

  // .PublicDealsV3Api publicDeals = 301;
  if (_internal_has_publicdeals()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(301, _Internal::publicdeals(this),
        _Internal::publicdeals(this).GetCachedSize(), target, stream);
  }

  // .PublicIncreaseDepthsV3Api publicIncreaseDepths = 302;
  if (_internal_has_publicincreasedepths()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(302, _Internal::publicincreasedepths(this),
        _Internal::publicincreasedepths(this).GetCachedSize(), target, stream);
  }

  // .PublicLimitDepthsV3Api publicLimitDepths = 303;
  if (_internal_has_publiclimitdepths()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(303, _Internal::publiclimitdepths(this),
        _Internal::publiclimitdepths(this).GetCachedSize(), target, stream);
  }

  // .PrivateOrdersV3Api privateOrders = 304;
  if (_internal_has_privateorders()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(304, _Internal::privateorders(this),
        _Internal::privateorders(this).GetCachedSize(), target, stream);
  }

  // .PublicBookTickerV3Api publicBookTicker = 305;
  if (_internal_has_publicbookticker()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(305, _Internal::publicbookticker(this),
        _Internal::publicbookticker(this).GetCachedSize(), target, stream);
  }

  // .PrivateDealsV3Api privateDeals = 306;
  if (_internal_has_privatedeals()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(306, _Internal::privatedeals(this),
        _Internal::privatedeals(this).GetCachedSize(), target, stream);
  }

  // .PrivateAccountV3Api privateAccount = 307;
  if (_internal_has_privateaccount()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(307, _Internal::privateaccount(this),
        _Internal::privateaccount(this).GetCachedSize(), target, stream);
  }

  // .PublicSpotKlineV3Api publicSpotKline = 308;
  if (_internal_has_publicspotkline()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(308, _Internal::publicspotkline(this),
        _Internal::publicspotkline(this).GetCachedSize(), target, stream);
  }

  // .PublicMiniTickerV3Api publicMiniTicker = 309;
  if (_internal_has_publicminiticker()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(309, _Internal::publicminiticker(this),
        _Internal::publicminiticker(this).GetCachedSize(), target, stream);
  }

  // .PublicMiniTickersV3Api publicMiniTickers = 310;
  if (_internal_has_publicminitickers()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(310, _Internal::publicminitickers(this),
        _Internal::publicminitickers(this).GetCachedSize(), target, stream);
  }

  // .PublicBookTickerBatchV3Api publicBookTickerBatch = 311;
  if (_internal_has_publicbooktickerbatch()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(311, _Internal::publicbooktickerbatch(this),
        _Internal::publicbooktickerbatch(this).GetCachedSize(), target, stream);
  }

  // .PublicIncreaseDepthsBatchV3Api publicIncreaseDepthsBatch = 312;
  if (_internal_has_publicincreasedepthsbatch()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(312, _Internal::publicincreasedepthsbatch(this),
        _Internal::publicincreasedepthsbatch(this).GetCachedSize(), target, stream);
  }

  // .PublicAggreDepthsV3Api publicAggreDepths = 313;
  if (_internal_has_publicaggredepths()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(313, _Internal::publicaggredepths(this),
        _Internal::publicaggredepths(this).GetCachedSize(), target, stream);
  }

  // .PublicAggreDealsV3Api publicAggreDeals = 314;
  if (_internal_has_publicaggredeals()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(314, _Internal::publicaggredeals(this),
        _Internal::publicaggredeals(this).GetCachedSize(), target, stream);
  }

  // .PublicAggreBookTickerV3Api publicAggreBookTicker = 315;
  if (_internal_has_publicaggrebookticker()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(315, _Internal::publicaggrebookticker(this),
        _Internal::publicaggrebookticker(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PushDataV3ApiWrapper)
  return target;
}

size_t PushDataV3ApiWrapper::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PushDataV3ApiWrapper)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string channel = 1;
  if (!this->_internal_channel().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_channel());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional string symbol = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_symbol());
    }

    // optional string symbolId = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_symbolid());
    }

    // optional int64 createTime = 5;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_createtime());
    }

    // optional int64 sendTime = 6;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_sendtime());
    }

  }
  switch (body_case()) {
    // .PublicDealsV3Api publicDeals = 301;
    case kPublicDeals: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.publicdeals_);
      break;
    }
    // .PublicIncreaseDepthsV3Api publicIncreaseDepths = 302;
    case kPublicIncreaseDepths: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.publicincreasedepths_);
      break;
    }
    // .PublicLimitDepthsV3Api publicLimitDepths = 303;
    case kPublicLimitDepths: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.publiclimitdepths_);
      break;
    }
    // .PrivateOrdersV3Api privateOrders = 304;
    case kPrivateOrders: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.privateorders_);
      break;
    }
    // .PublicBookTickerV3Api publicBookTicker = 305;
    case kPublicBookTicker: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.publicbookticker_);
      break;
    }
    // .PrivateDealsV3Api privateDeals = 306;
    case kPrivateDeals: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.privatedeals_);
      break;
    }
    // .PrivateAccountV3Api privateAccount = 307;
    case kPrivateAccount: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.privateaccount_);
      break;
    }
    // .PublicSpotKlineV3Api publicSpotKline = 308;
    case kPublicSpotKline: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.publicspotkline_);
      break;
    }
    // .PublicMiniTickerV3Api publicMiniTicker = 309;
    case kPublicMiniTicker: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.publicminiticker_);
      break;
    }
    // .PublicMiniTickersV3Api publicMiniTickers = 310;
    case kPublicMiniTickers: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.publicminitickers_);
      break;
    }
    // .PublicBookTickerBatchV3Api publicBookTickerBatch = 311;
    case kPublicBookTickerBatch: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.publicbooktickerbatch_);
      break;
    }
    // .PublicIncreaseDepthsBatchV3Api publicIncreaseDepthsBatch = 312;
    case kPublicIncreaseDepthsBatch: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.publicincreasedepthsbatch_);
      break;
    }
    // .PublicAggreDepthsV3Api publicAggreDepths = 313;
    case kPublicAggreDepths: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.publicaggredepths_);
      break;
    }
    // .PublicAggreDealsV3Api publicAggreDeals = 314;
    case kPublicAggreDeals: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.publicaggredeals_);
      break;
    }
    // .PublicAggreBookTickerV3Api publicAggreBookTicker = 315;
    case kPublicAggreBookTicker: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.body_.publicaggrebookticker_);
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PushDataV3ApiWrapper::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PushDataV3ApiWrapper::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PushDataV3ApiWrapper::GetClassData() const { return &_class_data_; }


void PushDataV3ApiWrapper::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PushDataV3ApiWrapper*>(&to_msg);
  auto& from = static_cast<const PushDataV3ApiWrapper&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PushDataV3ApiWrapper)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_channel().empty()) {
    _this->_internal_set_channel(from._internal_channel());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_symbol(from._internal_symbol());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_symbolid(from._internal_symbolid());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.createtime_ = from._impl_.createtime_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.sendtime_ = from._impl_.sendtime_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  switch (from.body_case()) {
    case kPublicDeals: {
      _this->_internal_mutable_publicdeals()->::PublicDealsV3Api::MergeFrom(
          from._internal_publicdeals());
      break;
    }
    case kPublicIncreaseDepths: {
      _this->_internal_mutable_publicincreasedepths()->::PublicIncreaseDepthsV3Api::MergeFrom(
          from._internal_publicincreasedepths());
      break;
    }
    case kPublicLimitDepths: {
      _this->_internal_mutable_publiclimitdepths()->::PublicLimitDepthsV3Api::MergeFrom(
          from._internal_publiclimitdepths());
      break;
    }
    case kPrivateOrders: {
      _this->_internal_mutable_privateorders()->::PrivateOrdersV3Api::MergeFrom(
          from._internal_privateorders());
      break;
    }
    case kPublicBookTicker: {
      _this->_internal_mutable_publicbookticker()->::PublicBookTickerV3Api::MergeFrom(
          from._internal_publicbookticker());
      break;
    }
    case kPrivateDeals: {
      _this->_internal_mutable_privatedeals()->::PrivateDealsV3Api::MergeFrom(
          from._internal_privatedeals());
      break;
    }
    case kPrivateAccount: {
      _this->_internal_mutable_privateaccount()->::PrivateAccountV3Api::MergeFrom(
          from._internal_privateaccount());
      break;
    }
    case kPublicSpotKline: {
      _this->_internal_mutable_publicspotkline()->::PublicSpotKlineV3Api::MergeFrom(
          from._internal_publicspotkline());
      break;
    }
    case kPublicMiniTicker: {
      _this->_internal_mutable_publicminiticker()->::PublicMiniTickerV3Api::MergeFrom(
          from._internal_publicminiticker());
      break;
    }
    case kPublicMiniTickers: {
      _this->_internal_mutable_publicminitickers()->::PublicMiniTickersV3Api::MergeFrom(
          from._internal_publicminitickers());
      break;
    }
    case kPublicBookTickerBatch: {
      _this->_internal_mutable_publicbooktickerbatch()->::PublicBookTickerBatchV3Api::MergeFrom(
          from._internal_publicbooktickerbatch());
      break;
    }
    case kPublicIncreaseDepthsBatch: {
      _this->_internal_mutable_publicincreasedepthsbatch()->::PublicIncreaseDepthsBatchV3Api::MergeFrom(
          from._internal_publicincreasedepthsbatch());
      break;
    }
    case kPublicAggreDepths: {
      _this->_internal_mutable_publicaggredepths()->::PublicAggreDepthsV3Api::MergeFrom(
          from._internal_publicaggredepths());
      break;
    }
    case kPublicAggreDeals: {
      _this->_internal_mutable_publicaggredeals()->::PublicAggreDealsV3Api::MergeFrom(
          from._internal_publicaggredeals());
      break;
    }
    case kPublicAggreBookTicker: {
      _this->_internal_mutable_publicaggrebookticker()->::PublicAggreBookTickerV3Api::MergeFrom(
          from._internal_publicaggrebookticker());
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PushDataV3ApiWrapper::CopyFrom(const PushDataV3ApiWrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PushDataV3ApiWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PushDataV3ApiWrapper::IsInitialized() const {
  return true;
}

void PushDataV3ApiWrapper::InternalSwap(PushDataV3ApiWrapper* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.channel_, lhs_arena,
      &other->_impl_.channel_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.symbol_, lhs_arena,
      &other->_impl_.symbol_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.symbolid_, lhs_arena,
      &other->_impl_.symbolid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.sendtime_)
      + sizeof(PushDataV3ApiWrapper::_impl_.sendtime_)
      - PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.createtime_)>(
          reinterpret_cast<char*>(&_impl_.createtime_),
          reinterpret_cast<char*>(&other->_impl_.createtime_));
  swap(_impl_.body_, other->_impl_.body_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata PushDataV3ApiWrapper::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PushDataV3ApiWrapper_2eproto_getter, &descriptor_table_PushDataV3ApiWrapper_2eproto_once,
      file_level_metadata_PushDataV3ApiWrapper_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PushDataV3ApiWrapper*
Arena::CreateMaybeMessage< ::PushDataV3ApiWrapper >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PushDataV3ApiWrapper >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
